version: "2"
linters:
  default: standard
  enable:
    - staticcheck
    - unconvert
    - usestdlibvars
  disable:
    - errcheck
  settings:
    staticcheck:
      checks:
        - all
        - -ST1003
      dot-import-whitelist:
        - github.com/ipfs/kubo/test/cli/testutils