# Hadolint configuration for Kubo Docker image
# https://github.com/hadolint/hadolint

# Ignore specific rules
ignored:
  # DL3008: Pin versions in apt-get install
  # We use stable base images and prefer smaller layers over version pinning
  - DL3008

# Trust base images from these registries
trustedRegistries:
  - docker.io
  - gcr.io

# Set error level for specific rules
override:
  error:
    # Ensure we use COPY instead of ADD for files
    - DL3020
  warning:
    # Warn about multiple consecutive RUN instructions
    - DL3059