version: '3.8'
services:
  ipfs:
    build: .
    restart: unless-stopped
    volumes:
      - ipfs_path:/data/ipfs
      - ipfs_fuse:/ipfs
      - ipns_fuse:/ipns
    environment:
      - IPFS_PATH=/data/ipfs
    ports:
      - 4001:4001/tcp
      - 4001:4001/udp
      - 5001:5001
      - 8080:8080
      - 8081:8081
volumes:
  ipfs_path:
  ipfs_fuse:
  ipns_fuse:
