// Code generated by protoc-gen-gogo.
// source: request.proto
// DO NOT EDIT!

/*
Package service is a generated protocol buffer package.

It is generated from these files:
	request.proto

It has these top-level messages:
	PBRequest
*/
package service

import proto "github.com/jbenet/go-ipfs/Godeps/_workspace/src/code.google.com/p/gogoprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type PBRequest struct {
	Data             []byte `protobuf:"bytes,1,req" json:"Data,omitempty"`
	Tag              []byte `protobuf:"bytes,3,opt" json:"Tag,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PBRequest) Reset()         { *m = PBRequest{} }
func (m *PBRequest) String() string { return proto.CompactTextString(m) }
func (*PBRequest) ProtoMessage()    {}

func (m *PBRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *PBRequest) GetTag() []byte {
	if m != nil {
		return m.Tag
	}
	return nil
}

func init() {
}
