// Code generated by tools/gen-rpc-client; DO NOT EDIT.

package rpc

import (
	"context"
	"io"
)

type KeyGenResponse struct {
	Name string `json:"Name,omitempty"`
	Id   string `json:"Id,omitempty"`
}

type KeyImportResponse struct {
	Name string `json:"Name,omitempty"`
	Id   string `json:"Id,omitempty"`
}

type KeyListResponse struct {
	Keys []KeyListResponseKeys `json:"Keys,omitempty"`
}

type KeyListResponseKeys struct {
	Name string `json:"Name,omitempty"`
	Id   string `json:"Id,omitempty"`
}

type KeyLsResponse struct {
	Keys []KeyLsResponseKeys `json:"Keys,omitempty"`
}

type KeyLsResponseKeys struct {
	Name string `json:"Name,omitempty"`
	Id   string `json:"Id,omitempty"`
}

type KeyRenameResponse struct {
	Was       string `json:"Was,omitempty"`
	Now       string `json:"Now,omitempty"`
	Id        string `json:"Id,omitempty"`
	Overwrite bool   `json:"Overwrite,omitempty"`
}

type KeyRmResponse struct {
	Keys []KeyRmResponseKeys `json:"Keys,omitempty"`
}

type KeyRmResponseKeys struct {
	Name string `json:"Name,omitempty"`
	Id   string `json:"Id,omitempty"`
}

type KeySignResponse struct {
	Key       KeySignResponseKey `json:"Key,omitempty"`
	Signature string             `json:"Signature,omitempty"`
}

type KeySignResponseKey struct {
	Name string `json:"Name,omitempty"`
	Id   string `json:"Id,omitempty"`
}

type KeyVerifyResponse struct {
	Key            KeyVerifyResponseKey `json:"Key,omitempty"`
	SignatureValid bool                 `json:"SignatureValid,omitempty"`
}

type KeyVerifyResponseKey struct {
	Name string `json:"Name,omitempty"`
	Id   string `json:"Id,omitempty"`
}

// KeyGenOption configures the key/gen command.
type KeyGenOption func(RequestBuilder)

// KeyGenType sets the type option.
// type of the key to create: rsa, ed25519. Default: ed25519.
func KeyGenType(v string) KeyGenOption {
	return func(rb RequestBuilder) { rb.Option("type", v) }
}

// KeyGenSize sets the size option.
// size of the key to generate.
func KeyGenSize(v int) KeyGenOption {
	return func(rb RequestBuilder) { rb.Option("size", v) }
}

// KeyGenIpnsBase sets the ipns-base option.
// Encoding used for keys: Can either be a multibase encoded CID or a base58btc encoded multihash. Takes {b58mh|base36|k|base32|b...}. Default: base36.
func KeyGenIpnsBase(v string) KeyGenOption {
	return func(rb RequestBuilder) { rb.Option("ipns-base", v) }
}

// KeyGen create a new keypair.
func (a *HttpApi) KeyGen(ctx context.Context, name string, opts ...KeyGenOption) (*KeyGenResponse, error) {
	req := a.Request("key/gen", name)
	for _, o := range opts {
		o(req)
	}
	var resp KeyGenResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// KeyImportOption configures the key/import command.
type KeyImportOption func(RequestBuilder)

// KeyImportIpnsBase sets the ipns-base option.
// Encoding used for keys: Can either be a multibase encoded CID or a base58btc encoded multihash. Takes {b58mh|base36|k|base32|b...}. Default: base36.
func KeyImportIpnsBase(v string) KeyImportOption {
	return func(rb RequestBuilder) { rb.Option("ipns-base", v) }
}

// KeyImportFormat sets the format option.
// The format of the private key to import, libp2p-protobuf-cleartext or pem-pkcs8-cleartext. Default: libp2p-protobuf-cleartext.
func KeyImportFormat(v string) KeyImportOption {
	return func(rb RequestBuilder) { rb.Option("format", v) }
}

// KeyImportAllowAnyKeyType sets the allow-any-key-type option.
// Allow importing any key type. Default: false.
func KeyImportAllowAnyKeyType(v bool) KeyImportOption {
	return func(rb RequestBuilder) { rb.Option("allow-any-key-type", v) }
}

// KeyImport import a key and prints imported key id.
func (a *HttpApi) KeyImport(ctx context.Context, name string, key io.Reader, opts ...KeyImportOption) (*KeyImportResponse, error) {
	req := a.Request("key/import", name)
	req = req.FileBody(key).(RequestBuilder)
	for _, o := range opts {
		o(req)
	}
	var resp KeyImportResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// KeyListOption configures the key/list command.
type KeyListOption func(RequestBuilder)

// KeyListL sets the l option.
// Show extra information about keys.
func KeyListL(v bool) KeyListOption {
	return func(rb RequestBuilder) { rb.Option("l", v) }
}

// KeyListIpnsBase sets the ipns-base option.
// Encoding used for keys: Can either be a multibase encoded CID or a base58btc encoded multihash. Takes {b58mh|base36|k|base32|b...}. Default: base36.
func KeyListIpnsBase(v string) KeyListOption {
	return func(rb RequestBuilder) { rb.Option("ipns-base", v) }
}

// Deprecated: KeyList may be removed in a future release.
// KeyList deprecated: use 'ipfs key ls' instead..
func (a *HttpApi) KeyList(ctx context.Context, opts ...KeyListOption) (*KeyListResponse, error) {
	req := a.Request("key/list")
	for _, o := range opts {
		o(req)
	}
	var resp KeyListResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// KeyLsOption configures the key/ls command.
type KeyLsOption func(RequestBuilder)

// KeyLsL sets the l option.
// Show extra information about keys.
func KeyLsL(v bool) KeyLsOption {
	return func(rb RequestBuilder) { rb.Option("l", v) }
}

// KeyLsIpnsBase sets the ipns-base option.
// Encoding used for keys: Can either be a multibase encoded CID or a base58btc encoded multihash. Takes {b58mh|base36|k|base32|b...}. Default: base36.
func KeyLsIpnsBase(v string) KeyLsOption {
	return func(rb RequestBuilder) { rb.Option("ipns-base", v) }
}

// KeyLs list all local keypairs..
func (a *HttpApi) KeyLs(ctx context.Context, opts ...KeyLsOption) (*KeyLsResponse, error) {
	req := a.Request("key/ls")
	for _, o := range opts {
		o(req)
	}
	var resp KeyLsResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// KeyRenameOption configures the key/rename command.
type KeyRenameOption func(RequestBuilder)

// KeyRenameForce sets the force option.
// Allow to overwrite an existing key.
func KeyRenameForce(v bool) KeyRenameOption {
	return func(rb RequestBuilder) { rb.Option("force", v) }
}

// KeyRenameIpnsBase sets the ipns-base option.
// Encoding used for keys: Can either be a multibase encoded CID or a base58btc encoded multihash. Takes {b58mh|base36|k|base32|b...}. Default: base36.
func KeyRenameIpnsBase(v string) KeyRenameOption {
	return func(rb RequestBuilder) { rb.Option("ipns-base", v) }
}

// KeyRename rename a keypair..
func (a *HttpApi) KeyRename(ctx context.Context, name string, newName string, opts ...KeyRenameOption) (*KeyRenameResponse, error) {
	req := a.Request("key/rename", name, newName)
	for _, o := range opts {
		o(req)
	}
	var resp KeyRenameResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// KeyRmOption configures the key/rm command.
type KeyRmOption func(RequestBuilder)

// KeyRmL sets the l option.
// Show extra information about keys.
func KeyRmL(v bool) KeyRmOption {
	return func(rb RequestBuilder) { rb.Option("l", v) }
}

// KeyRmIpnsBase sets the ipns-base option.
// Encoding used for keys: Can either be a multibase encoded CID or a base58btc encoded multihash. Takes {b58mh|base36|k|base32|b...}. Default: base36.
func KeyRmIpnsBase(v string) KeyRmOption {
	return func(rb RequestBuilder) { rb.Option("ipns-base", v) }
}

// KeyRm remove a keypair..
func (a *HttpApi) KeyRm(ctx context.Context, name []string, opts ...KeyRmOption) (*KeyRmResponse, error) {
	req := a.Request("key/rm").Arguments(name...)
	for _, o := range opts {
		o(req)
	}
	var resp KeyRmResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// KeySignOption configures the key/sign command.
type KeySignOption func(RequestBuilder)

// KeySignKey sets the key option.
// The name of the key to use for signing.
func KeySignKey(v string) KeySignOption {
	return func(rb RequestBuilder) { rb.Option("key", v) }
}

// KeySignIpnsBase sets the ipns-base option.
// Encoding used for keys: Can either be a multibase encoded CID or a base58btc encoded multihash. Takes {b58mh|base36|k|base32|b...}. Default: base36.
func KeySignIpnsBase(v string) KeySignOption {
	return func(rb RequestBuilder) { rb.Option("ipns-base", v) }
}

// Experimental: KeySign is not yet stable.
// KeySign generates a signature for the given data with a specified key. Useful for proving the key ownership..
func (a *HttpApi) KeySign(ctx context.Context, data io.Reader, opts ...KeySignOption) (*KeySignResponse, error) {
	req := a.Request("key/sign")
	req = req.FileBody(data).(RequestBuilder)
	for _, o := range opts {
		o(req)
	}
	var resp KeySignResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// KeyVerifyOption configures the key/verify command.
type KeyVerifyOption func(RequestBuilder)

// KeyVerifyKey sets the key option.
// The name of the key to use for verifying.
func KeyVerifyKey(v string) KeyVerifyOption {
	return func(rb RequestBuilder) { rb.Option("key", v) }
}

// KeyVerifySignature sets the signature option.
// Multibase-encoded signature to verify.
func KeyVerifySignature(v string) KeyVerifyOption {
	return func(rb RequestBuilder) { rb.Option("signature", v) }
}

// KeyVerifyIpnsBase sets the ipns-base option.
// Encoding used for keys: Can either be a multibase encoded CID or a base58btc encoded multihash. Takes {b58mh|base36|k|base32|b...}. Default: base36.
func KeyVerifyIpnsBase(v string) KeyVerifyOption {
	return func(rb RequestBuilder) { rb.Option("ipns-base", v) }
}

// Experimental: KeyVerify is not yet stable.
// KeyVerify verify that the given data and signature match..
func (a *HttpApi) KeyVerify(ctx context.Context, data io.Reader, opts ...KeyVerifyOption) (*KeyVerifyResponse, error) {
	req := a.Request("key/verify")
	req = req.FileBody(data).(RequestBuilder)
	for _, o := range opts {
		o(req)
	}
	var resp KeyVerifyResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
