// Code generated by tools/gen-rpc-client; DO NOT EDIT.

package rpc

import (
	"context"
	"encoding/json"
	"iter"
)

type SwarmAddrsAutonatResponse struct {
	Reachability string   `json:"reachability"`
	Reachable    []string `json:"reachable,omitempty"`
	Unreachable  []string `json:"unreachable,omitempty"`
	Unknown      []string `json:"unknown,omitempty"`
}

type SwarmAddrsListenResponse struct {
	Strings []string `json:"Strings,omitempty"`
}

type SwarmAddrsLocalResponse struct {
	Strings []string `json:"Strings,omitempty"`
}

type SwarmAddrsResponse struct {
	Addrs map[string][]string `json:"Addrs,omitempty"`
}

type SwarmConnectResponse struct {
	Strings []string `json:"Strings,omitempty"`
}

type SwarmDisconnectResponse struct {
	Strings []string `json:"Strings,omitempty"`
}

type SwarmFiltersAddResponse struct {
	Strings []string `json:"Strings,omitempty"`
}

type SwarmFiltersResponse struct {
	Strings []string `json:"Strings,omitempty"`
}

type SwarmFiltersRmResponse struct {
	Strings []string `json:"Strings,omitempty"`
}

type SwarmPeeringAddResponse struct {
	ID     string `json:"ID,omitempty"`
	Status string `json:"Status,omitempty"`
}

type SwarmPeeringLsResponse struct {
	Peers []SwarmPeeringLsResponsePeers `json:"Peers,omitempty"`
}

type SwarmPeeringLsResponsePeers struct {
	ID    string   `json:"ID,omitempty"`
	Addrs []string `json:"Addrs,omitempty"`
}

type SwarmPeeringRmResponse struct {
	ID     string `json:"ID,omitempty"`
	Status string `json:"Status,omitempty"`
}

type SwarmPeersResponse struct {
	Peers []SwarmPeersResponsePeers `json:"Peers,omitempty"`
}

type SwarmPeersResponsePeers struct {
	Addr      string                           `json:",omitempty"`
	Peer      string                           `json:",omitempty"`
	Latency   string                           `json:",omitempty"`
	Muxer     string                           `json:",omitempty"`
	Direction int                              `json:",omitempty"`
	Streams   []SwarmPeersResponsePeersStreams `json:",omitempty"`
	Identify  SwarmPeersResponsePeersIdentify  `json:"Identify,omitempty"`
}

type SwarmPeersResponsePeersIdentify struct {
	ID           string   `json:"ID,omitempty"`
	PublicKey    string   `json:"PublicKey,omitempty"`
	Addresses    []string `json:"Addresses,omitempty"`
	AgentVersion string   `json:"AgentVersion,omitempty"`
	Protocols    []string `json:"Protocols,omitempty"`
}

type SwarmPeersResponsePeersStreams struct {
	Protocol string `json:"Protocol,omitempty"`
}

type SwarmResourcesResponse struct {
	System    SwarmResourcesResponseSystem `json:"System,omitempty"`
	Transient json.RawMessage              `json:"Transient,omitempty"`
	Services  map[string]json.RawMessage   `json:",omitempty"`
	Protocols map[string]json.RawMessage   `json:",omitempty"`
	Peers     map[string]json.RawMessage   `json:",omitempty"`
}

type SwarmResourcesResponseSystem struct {
	Memory               int64 `json:"Memory,omitempty"`
	MemoryUsage          int64 `json:"MemoryUsage,omitempty"`
	FD                   int   `json:"FD,omitempty"`
	FDUsage              int   `json:"FDUsage,omitempty"`
	Conns                int   `json:"Conns,omitempty"`
	ConnsUsage           int   `json:"ConnsUsage,omitempty"`
	ConnsInbound         int   `json:"ConnsInbound,omitempty"`
	ConnsInboundUsage    int   `json:"ConnsInboundUsage,omitempty"`
	ConnsOutbound        int   `json:"ConnsOutbound,omitempty"`
	ConnsOutboundUsage   int   `json:"ConnsOutboundUsage,omitempty"`
	Streams              int   `json:"Streams,omitempty"`
	StreamsUsage         int   `json:"StreamsUsage,omitempty"`
	StreamsInbound       int   `json:"StreamsInbound,omitempty"`
	StreamsInboundUsage  int   `json:"StreamsInboundUsage,omitempty"`
	StreamsOutbound      int   `json:"StreamsOutbound,omitempty"`
	StreamsOutboundUsage int   `json:"StreamsOutboundUsage,omitempty"`
}

// SwarmAddrs list known addresses. Useful for debugging..
func (a *HttpApi) SwarmAddrs(ctx context.Context) (*SwarmAddrsResponse, error) {
	req := a.Request("swarm/addrs")
	var resp SwarmAddrsResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// SwarmAddrsAutonat show address reachability as determined by AutoNAT V2..
func (a *HttpApi) SwarmAddrsAutonat(ctx context.Context) (*SwarmAddrsAutonatResponse, error) {
	req := a.Request("swarm/addrs/autonat")
	var resp SwarmAddrsAutonatResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// SwarmAddrsListen list interface listening addresses..
func (a *HttpApi) SwarmAddrsListen(ctx context.Context) (*SwarmAddrsListenResponse, error) {
	req := a.Request("swarm/addrs/listen")
	var resp SwarmAddrsListenResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// SwarmAddrsLocalOption configures the swarm/addrs/local command.
type SwarmAddrsLocalOption func(RequestBuilder)

// SwarmAddrsLocalId sets the id option.
// Show peer ID in addresses.
func SwarmAddrsLocalId(v bool) SwarmAddrsLocalOption {
	return func(rb RequestBuilder) { rb.Option("id", v) }
}

// SwarmAddrsLocal list local addresses..
func (a *HttpApi) SwarmAddrsLocal(ctx context.Context, opts ...SwarmAddrsLocalOption) (*SwarmAddrsLocalResponse, error) {
	req := a.Request("swarm/addrs/local")
	for _, o := range opts {
		o(req)
	}
	var resp SwarmAddrsLocalResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// SwarmConnect open connection to a given peer..
func (a *HttpApi) SwarmConnect(ctx context.Context, address ...string) (*SwarmConnectResponse, error) {
	req := a.Request("swarm/connect").Arguments(address...)
	var resp SwarmConnectResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// SwarmDisconnect close connection to a given address..
func (a *HttpApi) SwarmDisconnect(ctx context.Context, address ...string) (*SwarmDisconnectResponse, error) {
	req := a.Request("swarm/disconnect").Arguments(address...)
	var resp SwarmDisconnectResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// SwarmFilters manipulate address filters..
func (a *HttpApi) SwarmFilters(ctx context.Context) (*SwarmFiltersResponse, error) {
	req := a.Request("swarm/filters")
	var resp SwarmFiltersResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// SwarmFiltersAdd add an address filter..
func (a *HttpApi) SwarmFiltersAdd(ctx context.Context, address ...string) (*SwarmFiltersAddResponse, error) {
	req := a.Request("swarm/filters/add").Arguments(address...)
	var resp SwarmFiltersAddResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// SwarmFiltersRm remove an address filter..
func (a *HttpApi) SwarmFiltersRm(ctx context.Context, address ...string) (*SwarmFiltersRmResponse, error) {
	req := a.Request("swarm/filters/rm").Arguments(address...)
	var resp SwarmFiltersRmResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// SwarmPeeringAdd add peers into the peering subsystem..
func (a *HttpApi) SwarmPeeringAdd(ctx context.Context, address ...string) iter.Seq2[SwarmPeeringAddResponse, error] {
	return func(yield func(SwarmPeeringAddResponse, error) bool) {
		req := a.Request("swarm/peering/add").Arguments(address...)
		resp, err := req.Send(ctx)
		if err != nil {
			yield(SwarmPeeringAddResponse{}, err)
			return
		}
		defer resp.Close()
		if resp.Error != nil {
			yield(SwarmPeeringAddResponse{}, resp.Error)
			return
		}
		dec := json.NewDecoder(resp.Output)
		for dec.More() {
			var item SwarmPeeringAddResponse
			if err := dec.Decode(&item); err != nil {
				yield(SwarmPeeringAddResponse{}, err)
				return
			}
			if !yield(item, nil) {
				return
			}
		}
	}
}

// SwarmPeeringLs list peers registered in the peering subsystem..
func (a *HttpApi) SwarmPeeringLs(ctx context.Context) (*SwarmPeeringLsResponse, error) {
	req := a.Request("swarm/peering/ls")
	var resp SwarmPeeringLsResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// SwarmPeeringRm remove a peer from the peering subsystem..
func (a *HttpApi) SwarmPeeringRm(ctx context.Context, ID ...string) (*SwarmPeeringRmResponse, error) {
	req := a.Request("swarm/peering/rm").Arguments(ID...)
	var resp SwarmPeeringRmResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// SwarmPeersOption configures the swarm/peers command.
type SwarmPeersOption func(RequestBuilder)

// SwarmPeersVerbose sets the verbose option.
// display all extra information.
func SwarmPeersVerbose(v bool) SwarmPeersOption {
	return func(rb RequestBuilder) { rb.Option("verbose", v) }
}

// SwarmPeersStreams sets the streams option.
// Also list information about open streams for each peer.
func SwarmPeersStreams(v bool) SwarmPeersOption {
	return func(rb RequestBuilder) { rb.Option("streams", v) }
}

// SwarmPeersLatency sets the latency option.
// Also list information about latency to each peer.
func SwarmPeersLatency(v bool) SwarmPeersOption {
	return func(rb RequestBuilder) { rb.Option("latency", v) }
}

// SwarmPeersDirection sets the direction option.
// Also list information about the direction of connection.
func SwarmPeersDirection(v bool) SwarmPeersOption {
	return func(rb RequestBuilder) { rb.Option("direction", v) }
}

// SwarmPeersIdentify sets the identify option.
// Also list information about peers identify.
func SwarmPeersIdentify(v bool) SwarmPeersOption {
	return func(rb RequestBuilder) { rb.Option("identify", v) }
}

// SwarmPeers list peers with open connections..
func (a *HttpApi) SwarmPeers(ctx context.Context, opts ...SwarmPeersOption) (*SwarmPeersResponse, error) {
	req := a.Request("swarm/peers")
	for _, o := range opts {
		o(req)
	}
	var resp SwarmPeersResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// Experimental: SwarmResources is not yet stable.
// SwarmResources get a summary of all resources accounted for by the libp2p Resource Manager..
func (a *HttpApi) SwarmResources(ctx context.Context) (*SwarmResourcesResponse, error) {
	req := a.Request("swarm/resources")
	var resp SwarmResourcesResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
