// Code generated by tools/gen-rpc-client; DO NOT EDIT.

package rpc

import (
	"context"
)

type MountResponse struct {
	IPFS           string `json:"IPFS,omitempty"`
	IPNS           string `json:"IPNS,omitempty"`
	MFS            string `json:"MFS,omitempty"`
	FuseAllowOther bool   `json:"FuseAllowOther,omitempty"`
}

// MountOption configures the mount command.
type MountOption func(RequestBuilder)

// MountIpfsPath sets the ipfs-path option.
// The path where IPFS should be mounted.
func MountIpfsPath(v string) MountOption {
	return func(rb RequestBuilder) { rb.Option("ipfs-path", v) }
}

// MountIpnsPath sets the ipns-path option.
// The path where IPNS should be mounted.
func MountIpnsPath(v string) MountOption {
	return func(rb RequestBuilder) { rb.Option("ipns-path", v) }
}

// MountMfsPath sets the mfs-path option.
// The path where MFS should be mounted.
func MountMfsPath(v string) MountOption {
	return func(rb RequestBuilder) { rb.Option("mfs-path", v) }
}

// Experimental: Mount is not yet stable.
// Mount mounts IPFS to the filesystem (read-only)..
func (a *HttpApi) Mount(ctx context.Context, opts ...MountOption) (*MountResponse, error) {
	req := a.Request("mount")
	for _, o := range opts {
		o(req)
	}
	var resp MountResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
