// Code generated by tools/gen-rpc-client; DO NOT EDIT.

package rpc

import (
	"context"
)

// GetOption configures the get command.
type GetOption func(RequestBuilder)

// GetOutput sets the output option.
// The path where the output should be stored.
func GetOutput(v string) GetOption {
	return func(rb RequestBuilder) { rb.Option("output", v) }
}

// GetArchive sets the archive option.
// Output a TAR archive.
func GetArchive(v bool) GetOption {
	return func(rb RequestBuilder) { rb.Option("archive", v) }
}

// GetCompress sets the compress option.
// Compress the output with GZIP compression.
func GetCompress(v bool) GetOption {
	return func(rb RequestBuilder) { rb.Option("compress", v) }
}

// GetCompressionLevel sets the compression-level option.
// The level of compression (1-9).
func GetCompressionLevel(v int) GetOption {
	return func(rb RequestBuilder) { rb.Option("compression-level", v) }
}

// GetProgress sets the progress option.
// Stream progress data. Default: true.
func GetProgress(v bool) GetOption {
	return func(rb RequestBuilder) { rb.Option("progress", v) }
}

// Get download IPFS objects..
func (a *HttpApi) Get(ctx context.Context, ipfs_path string, opts ...GetOption) (*Response, error) {
	req := a.Request("get", ipfs_path)
	for _, o := range opts {
		o(req)
	}
	resp, err := req.Send(ctx)
	if err != nil {
		return nil, err
	}
	if resp.Error != nil {
		resp.Close()
		return nil, resp.Error
	}
	return resp, nil
}
