// Code generated by tools/gen-rpc-client; DO NOT EDIT.

package rpc

import (
	"context"
	"encoding/json"
	"iter"
)

type RefsLocalResponse struct {
	Ref string `json:"Ref,omitempty"`
	Err string `json:"Err,omitempty"`
}

type RefsResponse struct {
	Ref string `json:"Ref,omitempty"`
	Err string `json:"Err,omitempty"`
}

// RefsOption configures the refs command.
type RefsOption func(RequestBuilder)

// RefsFormat sets the format option.
// Emit edges with given format. Available tokens: <src> <dst> <linkname>. Default: <dst>.
func RefsFormat(v string) RefsOption {
	return func(rb RequestBuilder) { rb.Option("format", v) }
}

// RefsEdges sets the edges option.
// Emit edge format: `<from> -> <to>`.
func RefsEdges(v bool) RefsOption {
	return func(rb RequestBuilder) { rb.Option("edges", v) }
}

// RefsUnique sets the unique option.
// Omit duplicate refs from output.
func RefsUnique(v bool) RefsOption {
	return func(rb RequestBuilder) { rb.Option("unique", v) }
}

// RefsRecursive sets the recursive option.
// Recursively list links of child nodes.
func RefsRecursive(v bool) RefsOption {
	return func(rb RequestBuilder) { rb.Option("recursive", v) }
}

// RefsMaxDepth sets the max-depth option.
// Only for recursive refs, limits fetch and listing to the given depth. Default: -1.
func RefsMaxDepth(v int) RefsOption {
	return func(rb RequestBuilder) { rb.Option("max-depth", v) }
}

// Refs list links (references) from an object..
func (a *HttpApi) Refs(ctx context.Context, ipfs_path []string, opts ...RefsOption) iter.Seq2[RefsResponse, error] {
	return func(yield func(RefsResponse, error) bool) {
		req := a.Request("refs").Arguments(ipfs_path...)
		for _, o := range opts {
			o(req)
		}
		resp, err := req.Send(ctx)
		if err != nil {
			yield(RefsResponse{}, err)
			return
		}
		defer resp.Close()
		if resp.Error != nil {
			yield(RefsResponse{}, resp.Error)
			return
		}
		dec := json.NewDecoder(resp.Output)
		for dec.More() {
			var item RefsResponse
			if err := dec.Decode(&item); err != nil {
				yield(RefsResponse{}, err)
				return
			}
			if !yield(item, nil) {
				return
			}
		}
	}
}

// RefsLocal list all local references..
func (a *HttpApi) RefsLocal(ctx context.Context) iter.Seq2[RefsLocalResponse, error] {
	return func(yield func(RefsLocalResponse, error) bool) {
		req := a.Request("refs/local")
		resp, err := req.Send(ctx)
		if err != nil {
			yield(RefsLocalResponse{}, err)
			return
		}
		defer resp.Close()
		if resp.Error != nil {
			yield(RefsLocalResponse{}, resp.Error)
			return
		}
		dec := json.NewDecoder(resp.Output)
		for dec.More() {
			var item RefsLocalResponse
			if err := dec.Decode(&item); err != nil {
				yield(RefsLocalResponse{}, err)
				return
			}
			if !yield(item, nil) {
				return
			}
		}
	}
}
