// Code generated by tools/gen-rpc-client; DO NOT EDIT.

package rpc

import (
	"context"
)

type BootstrapAddResponse struct {
	Peers []string `json:"Peers,omitempty"`
}

type BootstrapListResponse struct {
	Peers []string `json:"Peers,omitempty"`
}

type BootstrapResponse struct {
	Peers []string `json:"Peers,omitempty"`
}

type BootstrapRmAllResponse struct {
	Peers []string `json:"Peers,omitempty"`
}

type BootstrapRmResponse struct {
	Peers []string `json:"Peers,omitempty"`
}

// Bootstrap show or edit the list of bootstrap peers..
func (a *HttpApi) Bootstrap(ctx context.Context) (*BootstrapResponse, error) {
	req := a.Request("bootstrap")
	var resp BootstrapResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// BootstrapAdd add peers to the bootstrap list..
func (a *HttpApi) BootstrapAdd(ctx context.Context, peer ...string) (*BootstrapAddResponse, error) {
	req := a.Request("bootstrap/add").Arguments(peer...)
	var resp BootstrapAddResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// BootstrapListOption configures the bootstrap/list command.
type BootstrapListOption func(RequestBuilder)

// BootstrapListExpandAuto sets the expand-auto option.
// Expand 'auto' placeholders from AutoConf service.
func BootstrapListExpandAuto(v bool) BootstrapListOption {
	return func(rb RequestBuilder) { rb.Option("expand-auto", v) }
}

// BootstrapList show peers in the bootstrap list..
func (a *HttpApi) BootstrapList(ctx context.Context, opts ...BootstrapListOption) (*BootstrapListResponse, error) {
	req := a.Request("bootstrap/list")
	for _, o := range opts {
		o(req)
	}
	var resp BootstrapListResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// BootstrapRmOption configures the bootstrap/rm command.
type BootstrapRmOption func(RequestBuilder)

// BootstrapRmAll sets the all option.
// Remove all bootstrap peers. (Deprecated, use 'all' subcommand).
func BootstrapRmAll(v bool) BootstrapRmOption {
	return func(rb RequestBuilder) { rb.Option("all", v) }
}

// BootstrapRm remove peers from the bootstrap list..
func (a *HttpApi) BootstrapRm(ctx context.Context, peer []string, opts ...BootstrapRmOption) (*BootstrapRmResponse, error) {
	req := a.Request("bootstrap/rm").Arguments(peer...)
	for _, o := range opts {
		o(req)
	}
	var resp BootstrapRmResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// BootstrapRmAll remove all peers from the bootstrap list..
func (a *HttpApi) BootstrapRmAll(ctx context.Context) (*BootstrapRmAllResponse, error) {
	req := a.Request("bootstrap/rm/all")
	var resp BootstrapRmAllResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
