// Code generated by tools/gen-rpc-client; DO NOT EDIT.

package rpc

import (
	"context"
	"io"
)

type MultibaseListItem struct {
	Code int    `json:"Code,omitempty"`
	Name string `json:"Name,omitempty"`
}

// MultibaseDecode decode multibase string.
func (a *HttpApi) MultibaseDecode(ctx context.Context, encoded_file io.Reader) (*Response, error) {
	req := a.Request("multibase/decode")
	req = req.FileBody(encoded_file).(RequestBuilder)
	resp, err := req.Send(ctx)
	if err != nil {
		return nil, err
	}
	if resp.Error != nil {
		resp.Close()
		return nil, resp.Error
	}
	return resp, nil
}

// MultibaseEncodeOption configures the multibase/encode command.
type MultibaseEncodeOption func(RequestBuilder)

// MultibaseEncodeB sets the b option.
// multibase encoding. Default: base64url.
func MultibaseEncodeB(v string) MultibaseEncodeOption {
	return func(rb RequestBuilder) { rb.Option("b", v) }
}

// MultibaseEncode encode data into multibase string.
func (a *HttpApi) MultibaseEncode(ctx context.Context, file io.Reader, opts ...MultibaseEncodeOption) (*Response, error) {
	req := a.Request("multibase/encode")
	req = req.FileBody(file).(RequestBuilder)
	for _, o := range opts {
		o(req)
	}
	resp, err := req.Send(ctx)
	if err != nil {
		return nil, err
	}
	if resp.Error != nil {
		resp.Close()
		return nil, resp.Error
	}
	return resp, nil
}

// MultibaseListOption configures the multibase/list command.
type MultibaseListOption func(RequestBuilder)

// MultibaseListPrefix sets the prefix option.
// also include the single letter prefixes in addition to the code.
func MultibaseListPrefix(v bool) MultibaseListOption {
	return func(rb RequestBuilder) { rb.Option("prefix", v) }
}

// MultibaseListNumeric sets the numeric option.
// also include numeric codes.
func MultibaseListNumeric(v bool) MultibaseListOption {
	return func(rb RequestBuilder) { rb.Option("numeric", v) }
}

// MultibaseList list available multibase encodings..
func (a *HttpApi) MultibaseList(ctx context.Context, opts ...MultibaseListOption) ([]MultibaseListItem, error) {
	req := a.Request("multibase/list")
	for _, o := range opts {
		o(req)
	}
	var resp []MultibaseListItem
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return resp, nil
}

// MultibaseTranscodeOption configures the multibase/transcode command.
type MultibaseTranscodeOption func(RequestBuilder)

// MultibaseTranscodeB sets the b option.
// multibase encoding. Default: base64url.
func MultibaseTranscodeB(v string) MultibaseTranscodeOption {
	return func(rb RequestBuilder) { rb.Option("b", v) }
}

// MultibaseTranscode transcode multibase string between bases.
func (a *HttpApi) MultibaseTranscode(ctx context.Context, encoded_file io.Reader, opts ...MultibaseTranscodeOption) (*Response, error) {
	req := a.Request("multibase/transcode")
	req = req.FileBody(encoded_file).(RequestBuilder)
	for _, o := range opts {
		o(req)
	}
	resp, err := req.Send(ctx)
	if err != nil {
		return nil, err
	}
	if resp.Error != nil {
		resp.Close()
		return nil, resp.Error
	}
	return resp, nil
}
