// Code generated by tools/gen-rpc-client; DO NOT EDIT.

package rpc

import (
	"context"
	"encoding/json"
	"iter"
)

type PinAddResponse struct {
	Pins     []string `json:",omitempty"`
	Progress int      `json:",omitempty"`
	Bytes    uint64   `json:",omitempty"`
}

type PinLsResponse struct {
	Keys map[string]PinLsResponseKeysVal `json:",omitempty"`
	Cid  string                          `json:",omitempty"`
	Name string                          `json:",omitempty"`
	Type string                          `json:",omitempty"`
}

type PinLsResponseKeysVal struct {
	Type string `json:"Type,omitempty"`
	Name string `json:"Name,omitempty"`
}

type PinRemoteAddResponse struct {
	Status string `json:"Status,omitempty"`
	Cid    string `json:"Cid,omitempty"`
	Name   string `json:"Name,omitempty"`
}

type PinRemoteLsResponse struct {
	Status string `json:"Status,omitempty"`
	Cid    string `json:"Cid,omitempty"`
	Name   string `json:"Name,omitempty"`
}

type PinRemoteServiceLsResponse struct {
	RemoteServices []PinRemoteServiceLsResponseRemoteServices `json:"RemoteServices,omitempty"`
}

type PinRemoteServiceLsResponseRemoteServices struct {
	Service     string                                        `json:"Service,omitempty"`
	ApiEndpoint string                                        `json:"ApiEndpoint,omitempty"`
	Stat        *PinRemoteServiceLsResponseRemoteServicesStat `json:",omitempty"`
}

type PinRemoteServiceLsResponseRemoteServicesStat struct {
	Status   string                                                `json:"Status,omitempty"`
	PinCount *PinRemoteServiceLsResponseRemoteServicesStatPinCount `json:",omitempty"`
}

type PinRemoteServiceLsResponseRemoteServicesStatPinCount struct {
	Queued  int `json:"Queued,omitempty"`
	Pinning int `json:"Pinning,omitempty"`
	Pinned  int `json:"Pinned,omitempty"`
	Failed  int `json:"Failed,omitempty"`
}

type PinRmResponse struct {
	Pins []string `json:"Pins,omitempty"`
}

type PinUpdateResponse struct {
	Pins []string `json:"Pins,omitempty"`
}

type PinVerifyResponse struct {
	Cid      string                      `json:",omitempty"`
	Err      string                      `json:",omitempty"`
	Ok       bool                        `json:",omitempty"`
	BadNodes []PinVerifyResponseBadNodes `json:",omitempty"`
}

type PinVerifyResponseBadNodes struct {
	Cid string `json:"Cid,omitempty"`
	Err string `json:"Err,omitempty"`
}

// PinAddOption configures the pin/add command.
type PinAddOption func(RequestBuilder)

// PinAddRecursive sets the recursive option.
// Recursively pin the object linked to by the specified object(s). Default: true.
func PinAddRecursive(v bool) PinAddOption {
	return func(rb RequestBuilder) { rb.Option("recursive", v) }
}

// PinAddName sets the name option.
// An optional name for created pin(s).
func PinAddName(v string) PinAddOption {
	return func(rb RequestBuilder) { rb.Option("name", v) }
}

// PinAddProgress sets the progress option.
// Show progress.
func PinAddProgress(v bool) PinAddOption {
	return func(rb RequestBuilder) { rb.Option("progress", v) }
}

// PinAdd pin objects to local storage..
func (a *HttpApi) PinAdd(ctx context.Context, ipfs_path []string, opts ...PinAddOption) iter.Seq2[PinAddResponse, error] {
	return func(yield func(PinAddResponse, error) bool) {
		req := a.Request("pin/add").Arguments(ipfs_path...)
		for _, o := range opts {
			o(req)
		}
		resp, err := req.Send(ctx)
		if err != nil {
			yield(PinAddResponse{}, err)
			return
		}
		defer resp.Close()
		if resp.Error != nil {
			yield(PinAddResponse{}, resp.Error)
			return
		}
		dec := json.NewDecoder(resp.Output)
		for dec.More() {
			var item PinAddResponse
			if err := dec.Decode(&item); err != nil {
				yield(PinAddResponse{}, err)
				return
			}
			if !yield(item, nil) {
				return
			}
		}
	}
}

// PinLsOption configures the pin/ls command.
type PinLsOption func(RequestBuilder)

// PinLsType sets the type option.
// The type of pinned keys to list. Can be "direct", "indirect", "recursive", or "all". Default: all.
func PinLsType(v string) PinLsOption {
	return func(rb RequestBuilder) { rb.Option("type", v) }
}

// PinLsQuiet sets the quiet option.
// Output only the CIDs of pins.
func PinLsQuiet(v bool) PinLsOption {
	return func(rb RequestBuilder) { rb.Option("quiet", v) }
}

// PinLsName sets the name option.
// Limit returned pins to ones with names that contain the value provided (case-sensitive, partial match). Implies --names=true.
func PinLsName(v string) PinLsOption {
	return func(rb RequestBuilder) { rb.Option("name", v) }
}

// PinLsStream sets the stream option.
// Enable streaming of pins as they are discovered.
func PinLsStream(v bool) PinLsOption {
	return func(rb RequestBuilder) { rb.Option("stream", v) }
}

// PinLsNames sets the names option.
// Include pin names in the output (slower, disabled by default).
func PinLsNames(v bool) PinLsOption {
	return func(rb RequestBuilder) { rb.Option("names", v) }
}

// PinLs list objects pinned to local storage..
func (a *HttpApi) PinLs(ctx context.Context, ipfs_path []string, opts ...PinLsOption) iter.Seq2[PinLsResponse, error] {
	return func(yield func(PinLsResponse, error) bool) {
		req := a.Request("pin/ls").Arguments(ipfs_path...)
		for _, o := range opts {
			o(req)
		}
		resp, err := req.Send(ctx)
		if err != nil {
			yield(PinLsResponse{}, err)
			return
		}
		defer resp.Close()
		if resp.Error != nil {
			yield(PinLsResponse{}, resp.Error)
			return
		}
		dec := json.NewDecoder(resp.Output)
		for dec.More() {
			var item PinLsResponse
			if err := dec.Decode(&item); err != nil {
				yield(PinLsResponse{}, err)
				return
			}
			if !yield(item, nil) {
				return
			}
		}
	}
}

// PinRemoteAddOption configures the pin/remote/add command.
type PinRemoteAddOption func(RequestBuilder)

// PinRemoteAddService sets the service option.
// Name of the remote pinning service to use (mandatory).
func PinRemoteAddService(v string) PinRemoteAddOption {
	return func(rb RequestBuilder) { rb.Option("service", v) }
}

// PinRemoteAddName sets the name option.
// An optional name for the pin.
func PinRemoteAddName(v string) PinRemoteAddOption {
	return func(rb RequestBuilder) { rb.Option("name", v) }
}

// PinRemoteAddBackground sets the background option.
// Add to the queue on the remote service and return immediately (does not wait for pinned status). Default: false.
func PinRemoteAddBackground(v bool) PinRemoteAddOption {
	return func(rb RequestBuilder) { rb.Option("background", v) }
}

// PinRemoteAdd pin object to remote pinning service..
func (a *HttpApi) PinRemoteAdd(ctx context.Context, ipfs_path string, opts ...PinRemoteAddOption) (*PinRemoteAddResponse, error) {
	req := a.Request("pin/remote/add", ipfs_path)
	for _, o := range opts {
		o(req)
	}
	var resp PinRemoteAddResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// PinRemoteLsOption configures the pin/remote/ls command.
type PinRemoteLsOption func(RequestBuilder)

// PinRemoteLsService sets the service option.
// Name of the remote pinning service to use (mandatory).
func PinRemoteLsService(v string) PinRemoteLsOption {
	return func(rb RequestBuilder) { rb.Option("service", v) }
}

// PinRemoteLsName sets the name option.
// Return pins with names that contain the value provided (case-sensitive, exact match).
func PinRemoteLsName(v string) PinRemoteLsOption {
	return func(rb RequestBuilder) { rb.Option("name", v) }
}

// PinRemoteLsCid sets the cid option.
// Return pins for the specified CIDs (comma-separated).
func PinRemoteLsCid(v []string) PinRemoteLsOption {
	return func(rb RequestBuilder) { rb.Option("cid", v) }
}

// PinRemoteLsStatus sets the status option.
// Return pins with the specified statuses (queued,pinning,pinned,failed). Default: [pinned].
func PinRemoteLsStatus(v []string) PinRemoteLsOption {
	return func(rb RequestBuilder) { rb.Option("status", v) }
}

// PinRemoteLs list objects pinned to remote pinning service..
func (a *HttpApi) PinRemoteLs(ctx context.Context, opts ...PinRemoteLsOption) (*PinRemoteLsResponse, error) {
	req := a.Request("pin/remote/ls")
	for _, o := range opts {
		o(req)
	}
	var resp PinRemoteLsResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// PinRemoteRmOption configures the pin/remote/rm command.
type PinRemoteRmOption func(RequestBuilder)

// PinRemoteRmService sets the service option.
// Name of the remote pinning service to use (mandatory).
func PinRemoteRmService(v string) PinRemoteRmOption {
	return func(rb RequestBuilder) { rb.Option("service", v) }
}

// PinRemoteRmName sets the name option.
// Remove pins with names that contain provided value (case-sensitive, exact match).
func PinRemoteRmName(v string) PinRemoteRmOption {
	return func(rb RequestBuilder) { rb.Option("name", v) }
}

// PinRemoteRmCid sets the cid option.
// Remove pins for the specified CIDs.
func PinRemoteRmCid(v []string) PinRemoteRmOption {
	return func(rb RequestBuilder) { rb.Option("cid", v) }
}

// PinRemoteRmStatus sets the status option.
// Remove pins with the specified statuses (queued,pinning,pinned,failed). Default: [pinned].
func PinRemoteRmStatus(v []string) PinRemoteRmOption {
	return func(rb RequestBuilder) { rb.Option("status", v) }
}

// PinRemoteRmForce sets the force option.
// Allow removal of multiple pins matching the query without additional confirmation. Default: false.
func PinRemoteRmForce(v bool) PinRemoteRmOption {
	return func(rb RequestBuilder) { rb.Option("force", v) }
}

// PinRemoteRm remove pins from remote pinning service..
func (a *HttpApi) PinRemoteRm(ctx context.Context, opts ...PinRemoteRmOption) (*Response, error) {
	req := a.Request("pin/remote/rm")
	for _, o := range opts {
		o(req)
	}
	resp, err := req.Send(ctx)
	if err != nil {
		return nil, err
	}
	if resp.Error != nil {
		resp.Close()
		return nil, resp.Error
	}
	return resp, nil
}

// PinRemoteServiceAdd add remote pinning service..
func (a *HttpApi) PinRemoteServiceAdd(ctx context.Context, service string, endpoint string, key string) (*Response, error) {
	req := a.Request("pin/remote/service/add", service, endpoint, key)
	resp, err := req.Send(ctx)
	if err != nil {
		return nil, err
	}
	if resp.Error != nil {
		resp.Close()
		return nil, resp.Error
	}
	return resp, nil
}

// PinRemoteServiceLsOption configures the pin/remote/service/ls command.
type PinRemoteServiceLsOption func(RequestBuilder)

// PinRemoteServiceLsStat sets the stat option.
// Try to fetch and display current pin count on remote service (queued/pinning/pinned/failed). Default: false.
func PinRemoteServiceLsStat(v bool) PinRemoteServiceLsOption {
	return func(rb RequestBuilder) { rb.Option("stat", v) }
}

// PinRemoteServiceLs list remote pinning services..
func (a *HttpApi) PinRemoteServiceLs(ctx context.Context, opts ...PinRemoteServiceLsOption) (*PinRemoteServiceLsResponse, error) {
	req := a.Request("pin/remote/service/ls")
	for _, o := range opts {
		o(req)
	}
	var resp PinRemoteServiceLsResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// PinRemoteServiceRm remove remote pinning service..
func (a *HttpApi) PinRemoteServiceRm(ctx context.Context, service string) (*Response, error) {
	req := a.Request("pin/remote/service/rm", service)
	resp, err := req.Send(ctx)
	if err != nil {
		return nil, err
	}
	if resp.Error != nil {
		resp.Close()
		return nil, resp.Error
	}
	return resp, nil
}

// PinRmOption configures the pin/rm command.
type PinRmOption func(RequestBuilder)

// PinRmRecursive sets the recursive option.
// Recursively unpin the object linked to by the specified object(s). Default: true.
func PinRmRecursive(v bool) PinRmOption {
	return func(rb RequestBuilder) { rb.Option("recursive", v) }
}

// PinRm remove object from pin-list..
func (a *HttpApi) PinRm(ctx context.Context, ipfs_path []string, opts ...PinRmOption) (*PinRmResponse, error) {
	req := a.Request("pin/rm").Arguments(ipfs_path...)
	for _, o := range opts {
		o(req)
	}
	var resp PinRmResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// PinUpdateOption configures the pin/update command.
type PinUpdateOption func(RequestBuilder)

// PinUpdateUnpin sets the unpin option.
// Remove the old pin. Default: true.
func PinUpdateUnpin(v bool) PinUpdateOption {
	return func(rb RequestBuilder) { rb.Option("unpin", v) }
}

// PinUpdate update a recursive pin..
func (a *HttpApi) PinUpdate(ctx context.Context, from_path string, to_path string, opts ...PinUpdateOption) (*PinUpdateResponse, error) {
	req := a.Request("pin/update", from_path, to_path)
	for _, o := range opts {
		o(req)
	}
	var resp PinUpdateResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// PinVerifyOption configures the pin/verify command.
type PinVerifyOption func(RequestBuilder)

// PinVerifyVerbose sets the verbose option.
// Also write the hashes of non-broken pins.
func PinVerifyVerbose(v bool) PinVerifyOption {
	return func(rb RequestBuilder) { rb.Option("verbose", v) }
}

// PinVerifyQuiet sets the quiet option.
// Write just hashes of broken pins.
func PinVerifyQuiet(v bool) PinVerifyOption {
	return func(rb RequestBuilder) { rb.Option("quiet", v) }
}

// PinVerify verify that recursive pins are complete..
func (a *HttpApi) PinVerify(ctx context.Context, opts ...PinVerifyOption) iter.Seq2[PinVerifyResponse, error] {
	return func(yield func(PinVerifyResponse, error) bool) {
		req := a.Request("pin/verify")
		for _, o := range opts {
			o(req)
		}
		resp, err := req.Send(ctx)
		if err != nil {
			yield(PinVerifyResponse{}, err)
			return
		}
		defer resp.Close()
		if resp.Error != nil {
			yield(PinVerifyResponse{}, resp.Error)
			return
		}
		dec := json.NewDecoder(resp.Output)
		for dec.More() {
			var item PinVerifyResponse
			if err := dec.Decode(&item); err != nil {
				yield(PinVerifyResponse{}, err)
				return
			}
			if !yield(item, nil) {
				return
			}
		}
	}
}
