// Code generated by tools/gen-rpc-client; DO NOT EDIT.

package rpc

import (
	"context"
)

type ResolveResponse struct {
	Path string `json:"Path,omitempty"`
}

// ResolveOption configures the resolve command.
type ResolveOption func(RequestBuilder)

// ResolveRecursive sets the recursive option.
// Resolve until the result is an IPFS name. Default: true.
func ResolveRecursive(v bool) ResolveOption {
	return func(rb RequestBuilder) { rb.Option("recursive", v) }
}

// ResolveDhtRecordCount sets the dht-record-count option.
// Number of records to request for DHT resolution.
func ResolveDhtRecordCount(v int) ResolveOption {
	return func(rb RequestBuilder) { rb.Option("dht-record-count", v) }
}

// ResolveDhtTimeout sets the dht-timeout option.
// Max time to collect values during DHT resolution e.g. "30s". Pass 0 for no timeout.
func ResolveDhtTimeout(v string) ResolveOption {
	return func(rb RequestBuilder) { rb.Option("dht-timeout", v) }
}

// Resolve resolve the value of names to IPFS..
func (a *HttpApi) Resolve(ctx context.Context, name string, opts ...ResolveOption) (*ResolveResponse, error) {
	req := a.Request("resolve", name)
	for _, o := range opts {
		o(req)
	}
	var resp ResolveResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
