// Code generated by tools/gen-rpc-client; DO NOT EDIT.

package rpc

import (
	"context"
	"encoding/json"
	"iter"
)

type LogLevelResponse struct {
	Levels  map[string]string `json:",omitempty"`
	Message string            `json:",omitempty"`
}

type LogLsResponse struct {
	Strings []string `json:"Strings,omitempty"`
}

// LogLevel change or get the logging level..
func (a *HttpApi) LogLevel(ctx context.Context, subsystem string, level string) (*LogLevelResponse, error) {
	req := a.Request("log/level", subsystem, level)
	var resp LogLevelResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// LogLs list the logging subsystems..
func (a *HttpApi) LogLs(ctx context.Context) (*LogLsResponse, error) {
	req := a.Request("log/ls")
	var resp LogLsResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// LogTailOption configures the log/tail command.
type LogTailOption func(RequestBuilder)

// LogTailLogLevel sets the log-level option.
// Log level to listen to. Default: .
func LogTailLogLevel(v string) LogTailOption {
	return func(rb RequestBuilder) { rb.Option("log-level", v) }
}

// Experimental: LogTail is not yet stable.
// LogTail read and output log messages..
func (a *HttpApi) LogTail(ctx context.Context, opts ...LogTailOption) iter.Seq2[json.RawMessage, error] {
	return func(yield func(json.RawMessage, error) bool) {
		req := a.Request("log/tail")
		for _, o := range opts {
			o(req)
		}
		resp, err := req.Send(ctx)
		if err != nil {
			yield(nil, err)
			return
		}
		defer resp.Close()
		if resp.Error != nil {
			yield(nil, resp.Error)
			return
		}
		dec := json.NewDecoder(resp.Output)
		for dec.More() {
			var item json.RawMessage
			if err := dec.Decode(&item); err != nil {
				yield(nil, err)
				return
			}
			if !yield(item, nil) {
				return
			}
		}
	}
}
