// Code generated by tools/gen-rpc-client; DO NOT EDIT.

package rpc

import (
	"context"
	"encoding/json"
)

type CommandsResponse struct {
	Name        string                    `json:"Name,omitempty"`
	Subcommands []json.RawMessage         `json:"Subcommands,omitempty"`
	Options     []CommandsResponseOptions `json:"Options,omitempty"`
}

type CommandsResponseOptions struct {
	Names []string `json:"Names,omitempty"`
}

// CommandsOption configures the commands command.
type CommandsOption func(RequestBuilder)

// CommandsFlags sets the flags option.
// Show command flags.
func CommandsFlags(v bool) CommandsOption {
	return func(rb RequestBuilder) { rb.Option("flags", v) }
}

// Commands list all available commands..
func (a *HttpApi) Commands(ctx context.Context, opts ...CommandsOption) (*CommandsResponse, error) {
	req := a.Request("commands")
	for _, o := range opts {
		o(req)
	}
	var resp CommandsResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
