// Code generated by tools/gen-rpc-client; DO NOT EDIT.

package rpc

import (
	"context"
	"strings"
	"testing"

	"github.com/ipfs/kubo/test/cli/harness"
	"github.com/stretchr/testify/require"
)

// TestGeneratedSmoke starts a daemon and calls every generated method with
// minimal arguments. It verifies that methods don't panic and that response
// deserialization works. Commands that need complex setup are skipped.
func TestGeneratedSmoke(t *testing.T) {
	t.Parallel()
	h := harness.NewT(t)
	node := h.NewNode().Init().StartDaemon("--offline")
	api, err := NewApi(node.APIAddr())
	require.NoError(t, err)
	ctx := context.Background()
	_ = strings.NewReader // ensure strings import is used

	testCID := node.IPFSAddStr("smoke test data")

	t.Run("Add", func(t *testing.T) {
		require.NotPanics(t, func() {
			for _, err := range api.Add(ctx, strings.NewReader("test data")) {
				_ = err
				break
			}
		})
	})

	t.Run("BitswapLedger", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.BitswapLedger(ctx, "")
		})
	})

	t.Run("BitswapReprovide", func(t *testing.T) {
		require.NotPanics(t, func() {
			resp, err := api.BitswapReprovide(ctx)
			if err == nil && resp != nil {
				resp.Close()
			}
		})
	})

	t.Run("BitswapStat", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.BitswapStat(ctx)
		})
	})

	t.Run("BitswapWantlist", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.BitswapWantlist(ctx)
		})
	})

	t.Run("BlockGet", func(t *testing.T) {
		require.NotPanics(t, func() {
			resp, err := api.BlockGet(ctx, testCID)
			if err == nil && resp != nil {
				resp.Close()
			}
		})
	})

	t.Run("BlockPut", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.BlockPut(ctx, strings.NewReader("test data"))
		})
	})

	t.Run("BlockRm", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.BlockRm(ctx, []string{testCID})
		})
	})

	t.Run("BlockStat", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.BlockStat(ctx, testCID)
		})
	})

	t.Run("Bootstrap", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.Bootstrap(ctx)
		})
	})

	t.Run("BootstrapAdd", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.BootstrapAdd(ctx, "")
		})
	})

	t.Run("BootstrapList", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.BootstrapList(ctx)
		})
	})

	t.Run("BootstrapRm", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.BootstrapRm(ctx, []string{""})
		})
	})

	t.Run("BootstrapRmAll", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.BootstrapRmAll(ctx)
		})
	})

	t.Run("Cat", func(t *testing.T) {
		require.NotPanics(t, func() {
			resp, err := api.Cat(ctx, []string{testCID})
			if err == nil && resp != nil {
				resp.Close()
			}
		})
	})

	t.Run("CidBase32", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.CidBase32(ctx, testCID)
		})
	})

	t.Run("CidBases", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.CidBases(ctx)
		})
	})

	t.Run("CidCodecs", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.CidCodecs(ctx)
		})
	})

	t.Run("CidFormat", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.CidFormat(ctx, []string{testCID})
		})
	})

	t.Run("CidHashes", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.CidHashes(ctx)
		})
	})

	t.Run("Commands", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.Commands(ctx)
		})
	})

	t.Run("Config", func(t *testing.T) {
		t.Skip("needs specific config key/value")
	})

	t.Run("ConfigProfileApply", func(t *testing.T) {
		t.Skip("mutates config")
	})

	t.Run("ConfigReplace", func(t *testing.T) {
		t.Skip("replaces entire config")
	})

	t.Run("ConfigShow", func(t *testing.T) {
		require.NotPanics(t, func() {
			resp, err := api.ConfigShow(ctx)
			if err == nil && resp != nil {
				resp.Close()
			}
		})
	})

	t.Run("DagExport", func(t *testing.T) {
		require.NotPanics(t, func() {
			resp, err := api.DagExport(ctx, testCID)
			if err == nil && resp != nil {
				resp.Close()
			}
		})
	})

	t.Run("DagGet", func(t *testing.T) {
		require.NotPanics(t, func() {
			resp, err := api.DagGet(ctx, testCID)
			if err == nil && resp != nil {
				resp.Close()
			}
		})
	})

	t.Run("DagImport", func(t *testing.T) {
		t.Skip("needs valid CAR file")
	})

	t.Run("DagPut", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.DagPut(ctx, strings.NewReader("{}"))
		})
	})

	t.Run("DagResolve", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.DagResolve(ctx, testCID)
		})
	})

	t.Run("DagStat", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.DagStat(ctx, []string{testCID})
		})
	})

	t.Run("DhtQuery", func(t *testing.T) {
		t.Skip("needs online peer")
	})

	t.Run("DiagCmds", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.DiagCmds(ctx)
		})
	})

	t.Run("DiagCmdsClear", func(t *testing.T) {
		require.NotPanics(t, func() {
			resp, err := api.DiagCmdsClear(ctx)
			if err == nil && resp != nil {
				resp.Close()
			}
		})
	})

	t.Run("DiagCmdsSetTime", func(t *testing.T) {
		require.NotPanics(t, func() {
			resp, err := api.DiagCmdsSetTime(ctx, "")
			if err == nil && resp != nil {
				resp.Close()
			}
		})
	})

	t.Run("DiagProfile", func(t *testing.T) {
		t.Skip("runs profiler, slow")
	})

	t.Run("DiagSys", func(t *testing.T) {
		require.NotPanics(t, func() {
			resp, err := api.DiagSys(ctx)
			if err == nil && resp != nil {
				resp.Close()
			}
		})
	})

	t.Run("FilesChcid", func(t *testing.T) {
		t.Skip("needs MFS path")
	})

	t.Run("FilesChmod", func(t *testing.T) {
		require.NotPanics(t, func() {
			resp, err := api.FilesChmod(ctx, "", testCID)
			if err == nil && resp != nil {
				resp.Close()
			}
		})
	})

	t.Run("FilesCp", func(t *testing.T) {
		t.Skip("needs MFS files")
	})

	t.Run("FilesFlush", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.FilesFlush(ctx, testCID)
		})
	})

	t.Run("FilesLs", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.FilesLs(ctx, testCID)
		})
	})

	t.Run("FilesMkdir", func(t *testing.T) {
		t.Skip("needs MFS path setup")
	})

	t.Run("FilesMv", func(t *testing.T) {
		t.Skip("needs MFS files")
	})

	t.Run("FilesRead", func(t *testing.T) {
		require.NotPanics(t, func() {
			resp, err := api.FilesRead(ctx, testCID)
			if err == nil && resp != nil {
				resp.Close()
			}
		})
	})

	t.Run("FilesRm", func(t *testing.T) {
		t.Skip("needs MFS files")
	})

	t.Run("FilesStat", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.FilesStat(ctx, testCID)
		})
	})

	t.Run("FilesTouch", func(t *testing.T) {
		require.NotPanics(t, func() {
			resp, err := api.FilesTouch(ctx, testCID)
			if err == nil && resp != nil {
				resp.Close()
			}
		})
	})

	t.Run("FilesWrite", func(t *testing.T) {
		t.Skip("needs MFS file path")
	})

	t.Run("FilestoreDups", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.FilestoreDups(ctx)
		})
	})

	t.Run("FilestoreLs", func(t *testing.T) {
		t.Skip("needs filestore content")
	})

	t.Run("FilestoreVerify", func(t *testing.T) {
		t.Skip("needs filestore content")
	})

	t.Run("Get", func(t *testing.T) {
		require.NotPanics(t, func() {
			resp, err := api.Get(ctx, testCID)
			if err == nil && resp != nil {
				resp.Close()
			}
		})
	})

	t.Run("Id", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.Id(ctx, "")
		})
	})

	t.Run("KeyGen", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.KeyGen(ctx, "")
		})
	})

	t.Run("KeyImport", func(t *testing.T) {
		t.Skip("needs valid key file")
	})

	t.Run("KeyList", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.KeyList(ctx)
		})
	})

	t.Run("KeyLs", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.KeyLs(ctx)
		})
	})

	t.Run("KeyRename", func(t *testing.T) {
		t.Skip("needs existing non-self key")
	})

	t.Run("KeyRm", func(t *testing.T) {
		t.Skip("needs existing non-self key")
	})

	t.Run("KeySign", func(t *testing.T) {
		t.Skip("needs key and data setup")
	})

	t.Run("KeyVerify", func(t *testing.T) {
		t.Skip("needs key, signature, and data")
	})

	t.Run("LogLevel", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.LogLevel(ctx, "", "")
		})
	})

	t.Run("LogLs", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.LogLs(ctx)
		})
	})

	t.Run("LogTail", func(t *testing.T) {
		t.Skip("blocks waiting for log events")
	})

	t.Run("Ls", func(t *testing.T) {
		require.NotPanics(t, func() {
			for _, err := range api.Ls(ctx, []string{testCID}) {
				_ = err
				break
			}
		})
	})

	t.Run("Mount", func(t *testing.T) {
		t.Skip("requires FUSE")
	})

	t.Run("MultibaseDecode", func(t *testing.T) {
		require.NotPanics(t, func() {
			resp, err := api.MultibaseDecode(ctx, strings.NewReader("test data"))
			if err == nil && resp != nil {
				resp.Close()
			}
		})
	})

	t.Run("MultibaseEncode", func(t *testing.T) {
		require.NotPanics(t, func() {
			resp, err := api.MultibaseEncode(ctx, strings.NewReader("test data"))
			if err == nil && resp != nil {
				resp.Close()
			}
		})
	})

	t.Run("MultibaseList", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.MultibaseList(ctx)
		})
	})

	t.Run("MultibaseTranscode", func(t *testing.T) {
		require.NotPanics(t, func() {
			resp, err := api.MultibaseTranscode(ctx, strings.NewReader("test data"))
			if err == nil && resp != nil {
				resp.Close()
			}
		})
	})

	t.Run("NameGet", func(t *testing.T) {
		t.Skip("needs published IPNS record")
	})

	t.Run("NameInspect", func(t *testing.T) {
		t.Skip("needs valid IPNS record file")
	})

	t.Run("NamePublish", func(t *testing.T) {
		t.Skip("needs IPNS key setup")
	})

	t.Run("NamePubsubCancel", func(t *testing.T) {
		t.Skip("needs active IPNS subscription")
	})

	t.Run("NamePubsubState", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.NamePubsubState(ctx)
		})
	})

	t.Run("NamePubsubSubs", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.NamePubsubSubs(ctx)
		})
	})

	t.Run("NamePut", func(t *testing.T) {
		t.Skip("needs valid IPNS record file")
	})

	t.Run("NameResolve", func(t *testing.T) {
		t.Skip("needs published IPNS record")
	})

	t.Run("ObjectDiff", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.ObjectDiff(ctx, "", "")
		})
	})

	t.Run("ObjectPatchAddLink", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.ObjectPatchAddLink(ctx, testCID, "", testCID)
		})
	})

	t.Run("ObjectPatchRmLink", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.ObjectPatchRmLink(ctx, testCID, "")
		})
	})

	t.Run("P2pClose", func(t *testing.T) {
		t.Skip("needs active p2p listeners")
	})

	t.Run("P2pForward", func(t *testing.T) {
		t.Skip("needs p2p setup")
	})

	t.Run("P2pListen", func(t *testing.T) {
		t.Skip("needs p2p setup")
	})

	t.Run("P2pLs", func(t *testing.T) {
		t.Skip("needs active p2p listeners")
	})

	t.Run("P2pStreamClose", func(t *testing.T) {
		t.Skip("needs active p2p streams")
	})

	t.Run("P2pStreamLs", func(t *testing.T) {
		t.Skip("needs active p2p streams")
	})

	t.Run("PinAdd", func(t *testing.T) {
		require.NotPanics(t, func() {
			for _, err := range api.PinAdd(ctx, []string{testCID}) {
				_ = err
				break
			}
		})
	})

	t.Run("PinLs", func(t *testing.T) {
		require.NotPanics(t, func() {
			for _, err := range api.PinLs(ctx, []string{testCID}) {
				_ = err
				break
			}
		})
	})

	t.Run("PinRemoteAdd", func(t *testing.T) {
		t.Skip("needs remote pinning service")
	})

	t.Run("PinRemoteLs", func(t *testing.T) {
		t.Skip("needs remote pinning service")
	})

	t.Run("PinRemoteRm", func(t *testing.T) {
		t.Skip("needs remote pinning service")
	})

	t.Run("PinRemoteServiceAdd", func(t *testing.T) {
		t.Skip("needs remote pinning service")
	})

	t.Run("PinRemoteServiceLs", func(t *testing.T) {
		t.Skip("needs remote pinning service")
	})

	t.Run("PinRemoteServiceRm", func(t *testing.T) {
		t.Skip("needs remote pinning service")
	})

	t.Run("PinRm", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.PinRm(ctx, []string{testCID})
		})
	})

	t.Run("PinUpdate", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.PinUpdate(ctx, testCID, testCID)
		})
	})

	t.Run("PinVerify", func(t *testing.T) {
		require.NotPanics(t, func() {
			for _, err := range api.PinVerify(ctx) {
				_ = err
				break
			}
		})
	})

	t.Run("Ping", func(t *testing.T) {
		t.Skip("needs online peer")
	})

	t.Run("ProvideClear", func(t *testing.T) {
		require.NotPanics(t, func() {
			resp, err := api.ProvideClear(ctx)
			if err == nil && resp != nil {
				resp.Close()
			}
		})
	})

	t.Run("ProvideStat", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.ProvideStat(ctx)
		})
	})

	t.Run("PubsubLs", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.PubsubLs(ctx)
		})
	})

	t.Run("PubsubPeers", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.PubsubPeers(ctx, "")
		})
	})

	t.Run("PubsubPub", func(t *testing.T) {
		t.Skip("needs topic and subscriber")
	})

	t.Run("PubsubReset", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.PubsubReset(ctx)
		})
	})

	t.Run("PubsubSub", func(t *testing.T) {
		t.Skip("blocks waiting for messages")
	})

	t.Run("Refs", func(t *testing.T) {
		require.NotPanics(t, func() {
			for _, err := range api.Refs(ctx, []string{testCID}) {
				_ = err
				break
			}
		})
	})

	t.Run("RefsLocal", func(t *testing.T) {
		require.NotPanics(t, func() {
			for _, err := range api.RefsLocal(ctx) {
				_ = err
				break
			}
		})
	})

	t.Run("RepoGc", func(t *testing.T) {
		require.NotPanics(t, func() {
			for _, err := range api.RepoGc(ctx) {
				_ = err
				break
			}
		})
	})

	t.Run("RepoLs", func(t *testing.T) {
		require.NotPanics(t, func() {
			for _, err := range api.RepoLs(ctx) {
				_ = err
				break
			}
		})
	})

	t.Run("RepoStat", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.RepoStat(ctx)
		})
	})

	t.Run("RepoVerify", func(t *testing.T) {
		require.NotPanics(t, func() {
			for _, err := range api.RepoVerify(ctx) {
				_ = err
				break
			}
		})
	})

	t.Run("RepoVersion", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.RepoVersion(ctx)
		})
	})

	t.Run("Resolve", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.Resolve(ctx, "")
		})
	})

	t.Run("RoutingFindpeer", func(t *testing.T) {
		t.Skip("needs online peer")
	})

	t.Run("RoutingFindprovs", func(t *testing.T) {
		t.Skip("needs CID with providers")
	})

	t.Run("RoutingGet", func(t *testing.T) {
		t.Skip("needs valid DHT key")
	})

	t.Run("RoutingProvide", func(t *testing.T) {
		t.Skip("needs CID and network")
	})

	t.Run("RoutingPut", func(t *testing.T) {
		t.Skip("needs valid DHT key/value pair")
	})

	t.Run("RoutingReprovide", func(t *testing.T) {
		t.Skip("needs CID and network")
	})

	t.Run("Shutdown", func(t *testing.T) {
		t.Skip("kills the daemon")
	})

	t.Run("StatsBitswap", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.StatsBitswap(ctx)
		})
	})

	t.Run("StatsBw", func(t *testing.T) {
		t.Skip("blocks polling for bandwidth stats")
	})

	t.Run("StatsDht", func(t *testing.T) {
		require.NotPanics(t, func() {
			for _, err := range api.StatsDht(ctx, "") {
				_ = err
				break
			}
		})
	})

	t.Run("StatsProvide", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.StatsProvide(ctx)
		})
	})

	t.Run("StatsRepo", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.StatsRepo(ctx)
		})
	})

	t.Run("StatsReprovide", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.StatsReprovide(ctx)
		})
	})

	t.Run("SwarmAddrs", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.SwarmAddrs(ctx)
		})
	})

	t.Run("SwarmAddrsAutonat", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.SwarmAddrsAutonat(ctx)
		})
	})

	t.Run("SwarmAddrsListen", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.SwarmAddrsListen(ctx)
		})
	})

	t.Run("SwarmAddrsLocal", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.SwarmAddrsLocal(ctx)
		})
	})

	t.Run("SwarmConnect", func(t *testing.T) {
		t.Skip("needs peer address")
	})

	t.Run("SwarmDisconnect", func(t *testing.T) {
		t.Skip("needs connected peer")
	})

	t.Run("SwarmFilters", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.SwarmFilters(ctx)
		})
	})

	t.Run("SwarmFiltersAdd", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.SwarmFiltersAdd(ctx, "")
		})
	})

	t.Run("SwarmFiltersRm", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.SwarmFiltersRm(ctx, "")
		})
	})

	t.Run("SwarmPeeringAdd", func(t *testing.T) {
		require.NotPanics(t, func() {
			for _, err := range api.SwarmPeeringAdd(ctx, "") {
				_ = err
				break
			}
		})
	})

	t.Run("SwarmPeeringLs", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.SwarmPeeringLs(ctx)
		})
	})

	t.Run("SwarmPeeringRm", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.SwarmPeeringRm(ctx, "")
		})
	})

	t.Run("SwarmPeers", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.SwarmPeers(ctx)
		})
	})

	t.Run("SwarmResources", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.SwarmResources(ctx)
		})
	})

	t.Run("Version", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.Version(ctx)
		})
	})

	t.Run("VersionCheck", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.VersionCheck(ctx)
		})
	})

	t.Run("VersionDeps", func(t *testing.T) {
		require.NotPanics(t, func() {
			_, _ = api.VersionDeps(ctx)
		})
	})

}
