// Code generated by tools/gen-rpc-client; DO NOT EDIT.

package rpc

import (
	"context"
	"io"
)

type BlockPutResponse struct {
	Key  string `json:"Key,omitempty"`
	Size int    `json:"Size,omitempty"`
}

type BlockRmResponse struct {
	Hash  string `json:",omitempty"`
	Error string `json:",omitempty"`
}

type BlockStatResponse struct {
	Key  string `json:"Key,omitempty"`
	Size int    `json:"Size,omitempty"`
}

// BlockGet get a raw IPFS block..
func (a *HttpApi) BlockGet(ctx context.Context, cid string) (*Response, error) {
	req := a.Request("block/get", cid)
	resp, err := req.Send(ctx)
	if err != nil {
		return nil, err
	}
	if resp.Error != nil {
		resp.Close()
		return nil, resp.Error
	}
	return resp, nil
}

// BlockPutOption configures the block/put command.
type BlockPutOption func(RequestBuilder)

// BlockPutCidCodec sets the cid-codec option.
// Multicodec to use in returned CID. Default: raw.
func BlockPutCidCodec(v string) BlockPutOption {
	return func(rb RequestBuilder) { rb.Option("cid-codec", v) }
}

// BlockPutMhtype sets the mhtype option.
// Multihash hash function.
func BlockPutMhtype(v string) BlockPutOption {
	return func(rb RequestBuilder) { rb.Option("mhtype", v) }
}

// BlockPutMhlen sets the mhlen option.
// Multihash hash length. Default: -1.
func BlockPutMhlen(v int) BlockPutOption {
	return func(rb RequestBuilder) { rb.Option("mhlen", v) }
}

// BlockPutPin sets the pin option.
// Pin added blocks recursively. Default: false.
func BlockPutPin(v bool) BlockPutOption {
	return func(rb RequestBuilder) { rb.Option("pin", v) }
}

// BlockPutAllowBigBlock sets the allow-big-block option.
// Disable block size check and allow creation of blocks bigger than 2MiB. WARNING: such blocks won't be transferable over the standard bitswap. Default: false.
func BlockPutAllowBigBlock(v bool) BlockPutOption {
	return func(rb RequestBuilder) { rb.Option("allow-big-block", v) }
}

// BlockPutFormat sets the format option.
// Use legacy format for returned CID (DEPRECATED).
func BlockPutFormat(v string) BlockPutOption {
	return func(rb RequestBuilder) { rb.Option("format", v) }
}

// BlockPut store input as an IPFS block..
func (a *HttpApi) BlockPut(ctx context.Context, data io.Reader, opts ...BlockPutOption) (*BlockPutResponse, error) {
	req := a.Request("block/put")
	req = req.FileBody(data).(RequestBuilder)
	for _, o := range opts {
		o(req)
	}
	var resp BlockPutResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// BlockRmOption configures the block/rm command.
type BlockRmOption func(RequestBuilder)

// BlockRmForce sets the force option.
// Ignore nonexistent blocks.
func BlockRmForce(v bool) BlockRmOption {
	return func(rb RequestBuilder) { rb.Option("force", v) }
}

// BlockRmQuiet sets the quiet option.
// Write minimal output.
func BlockRmQuiet(v bool) BlockRmOption {
	return func(rb RequestBuilder) { rb.Option("quiet", v) }
}

// BlockRm remove IPFS block(s) from the local datastore..
func (a *HttpApi) BlockRm(ctx context.Context, cid []string, opts ...BlockRmOption) (*BlockRmResponse, error) {
	req := a.Request("block/rm").Arguments(cid...)
	for _, o := range opts {
		o(req)
	}
	var resp BlockRmResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// BlockStat print information of a raw IPFS block..
func (a *HttpApi) BlockStat(ctx context.Context, cid string) (*BlockStatResponse, error) {
	req := a.Request("block/stat", cid)
	var resp BlockStatResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
