// Code generated by tools/gen-rpc-client; DO NOT EDIT.

package rpc

import (
	"context"
)

// CatOption configures the cat command.
type CatOption func(RequestBuilder)

// CatOffset sets the offset option.
// Byte offset to begin reading from.
func CatOffset(v int64) CatOption {
	return func(rb RequestBuilder) { rb.Option("offset", v) }
}

// CatLength sets the length option.
// Maximum number of bytes to read.
func CatLength(v int64) CatOption {
	return func(rb RequestBuilder) { rb.Option("length", v) }
}

// CatProgress sets the progress option.
// Stream progress data. Default: true.
func CatProgress(v bool) CatOption {
	return func(rb RequestBuilder) { rb.Option("progress", v) }
}

// Cat show IPFS object data..
func (a *HttpApi) Cat(ctx context.Context, ipfs_path []string, opts ...CatOption) (*Response, error) {
	req := a.Request("cat").Arguments(ipfs_path...)
	for _, o := range opts {
		o(req)
	}
	resp, err := req.Send(ctx)
	if err != nil {
		return nil, err
	}
	if resp.Error != nil {
		resp.Close()
		return nil, resp.Error
	}
	return resp, nil
}
