// Code generated by tools/gen-rpc-client; DO NOT EDIT.

package rpc

import (
	"context"
	"encoding/json"
	"iter"
)

type StatsBitswapResponse struct {
	Wantlist         []string `json:"Wantlist,omitempty"`
	Peers            []string `json:"Peers,omitempty"`
	BlocksReceived   uint64   `json:"BlocksReceived,omitempty"`
	DataReceived     uint64   `json:"DataReceived,omitempty"`
	DupBlksReceived  uint64   `json:"DupBlksReceived,omitempty"`
	DupDataReceived  uint64   `json:"DupDataReceived,omitempty"`
	MessagesReceived uint64   `json:"MessagesReceived,omitempty"`
	BlocksSent       uint64   `json:"BlocksSent,omitempty"`
	DataSent         uint64   `json:"DataSent,omitempty"`
}

type StatsBwResponse struct {
	TotalIn  int64   `json:"TotalIn,omitempty"`
	TotalOut int64   `json:"TotalOut,omitempty"`
	RateIn   float64 `json:"RateIn,omitempty"`
	RateOut  float64 `json:"RateOut,omitempty"`
}

type StatsDhtResponse struct {
	Name    string                    `json:"Name,omitempty"`
	Buckets []StatsDhtResponseBuckets `json:"Buckets,omitempty"`
}

type StatsDhtResponseBuckets struct {
	LastRefresh string                         `json:"LastRefresh,omitempty"`
	Peers       []StatsDhtResponseBucketsPeers `json:"Peers,omitempty"`
}

type StatsDhtResponseBucketsPeers struct {
	ID            string `json:"ID,omitempty"`
	Connected     bool   `json:"Connected,omitempty"`
	AgentVersion  string `json:"AgentVersion,omitempty"`
	LastUsefulAt  string `json:"LastUsefulAt,omitempty"`
	LastQueriedAt string `json:"LastQueriedAt,omitempty"`
}

type StatsProvideResponse struct {
	Sweep  *StatsProvideResponseSweep  `json:"Sweep,omitempty"`
	Legacy *StatsProvideResponseLegacy `json:"Legacy,omitempty"`
	FullRT bool                        `json:"FullRT,omitempty"`
}

type StatsProvideResponseLegacy struct {
	TotalReprovides        uint64 `json:"TotalReprovides,omitempty"`
	LastReprovideBatchSize uint64 `json:"LastReprovideBatchSize,omitempty"`
	ReprovideInterval      string `json:"ReprovideInterval,omitempty"`
	AvgReprovideDuration   string `json:"AvgReprovideDuration,omitempty"`
	LastReprovideDuration  string `json:"LastReprovideDuration,omitempty"`
	LastRun                string `json:"LastRun,omitempty"`
}

type StatsProvideResponseSweep struct {
	Closed       bool                                  `json:"closed"`
	Connectivity StatsProvideResponseSweepConnectivity `json:"connectivity"`
	Queues       StatsProvideResponseSweepQueues       `json:"queues"`
	Schedule     StatsProvideResponseSweepSchedule     `json:"schedule"`
	Workers      StatsProvideResponseSweepWorkers      `json:"workers"`
	Timing       StatsProvideResponseSweepTiming       `json:"timing"`
	Operations   StatsProvideResponseSweepOperations   `json:"operations"`
	Network      StatsProvideResponseSweepNetwork      `json:"network"`
}

type StatsProvideResponseSweepConnectivity struct {
	Status string `json:"status"`
	Since  string `json:"since"`
}

type StatsProvideResponseSweepNetwork struct {
	Peers                    int     `json:"peers"`
	Reachable                int     `json:"reachable"`
	CompleteKeyspaceCoverage bool    `json:"complete_keyspace_coverage"`
	AvgRegionSize            float64 `json:"avg_region_size"`
	AvgHolders               float64 `json:"avg_holders"`
	ReplicationFactor        int     `json:"replication_factor"`
}

type StatsProvideResponseSweepOperations struct {
	Ongoing StatsProvideResponseSweepOperationsOngoing `json:"ongoing"`
	Past    StatsProvideResponseSweepOperationsPast    `json:"past"`
}

type StatsProvideResponseSweepOperationsOngoing struct {
	RegionProvides   int `json:"region_provides"`
	KeyProvides      int `json:"key_provides"`
	RegionReprovides int `json:"region_reprovides"`
	KeyReprovides    int `json:"key_reprovides"`
}

type StatsProvideResponseSweepOperationsPast struct {
	RecordsProvided           int64   `json:"records_provided"`
	KeysProvided              int64   `json:"keys_provided"`
	KeysFailed                int64   `json:"keys_failed"`
	KeysProvidedPerMinute     float64 `json:"keys_provided_per_minute"`
	KeysReprovidedPerMinute   float64 `json:"keys_reprovided_per_minute"`
	RegionReprovideDuration   string  `json:"reprovide_duration"`
	AvgKeysPerReprovide       float64 `json:"avg_keys_per_reprovide"`
	RegionReprovidedLastCycle int64   `json:"regions_reprovided_last_cycle"`
}

type StatsProvideResponseSweepQueues struct {
	PendingKeyProvides      int64 `json:"pending_key_provides"`
	PendingRegionProvides   int64 `json:"pending_region_provides"`
	PendingRegionReprovides int64 `json:"pending_region_reprovides"`
}

type StatsProvideResponseSweepSchedule struct {
	Keys                int64   `json:"keys"`
	Regions             int64   `json:"regions"`
	AvgPrefixLength     float64 `json:"avg_prefix_length"`
	NextReprovideAt     string  `json:"next_reprovide_at"`
	NextReprovidePrefix string  `json:"next_reprovide_prefix"`
}

type StatsProvideResponseSweepTiming struct {
	Uptime             string `json:"uptime"`
	ReprovidesInterval string `json:"reprovides_interval"`
	CycleStart         string `json:"cycle_start"`
	CurrentTimeOffset  string `json:"current_time_offset"`
	MaxReprovideDelay  string `json:"max_reprovide_delay"`
}

type StatsProvideResponseSweepWorkers struct {
	Max                      int `json:"max"`
	Active                   int `json:"active"`
	ActivePeriodic           int `json:"active_periodic"`
	ActiveBurst              int `json:"active_burst"`
	DedicatedPeriodic        int `json:"dedicated_periodic"`
	DedicatedBurst           int `json:"dedicated_burst"`
	QueuedPeriodic           int `json:"queued_periodic"`
	QueuedBurst              int `json:"queued_burst"`
	MaxProvideConnsPerWorker int `json:"max_provide_conns_per_worker"`
}

type StatsRepoResponse struct {
	RepoSize   uint64 `json:"RepoSize,omitempty"`
	StorageMax uint64 `json:"StorageMax,omitempty"`
	NumObjects uint64 `json:"NumObjects,omitempty"`
	RepoPath   string `json:"RepoPath,omitempty"`
	Version    string `json:"Version,omitempty"`
}

type StatsReprovideResponse struct {
	Sweep  *StatsReprovideResponseSweep  `json:"Sweep,omitempty"`
	Legacy *StatsReprovideResponseLegacy `json:"Legacy,omitempty"`
	FullRT bool                          `json:"FullRT,omitempty"`
}

type StatsReprovideResponseLegacy struct {
	TotalReprovides        uint64 `json:"TotalReprovides,omitempty"`
	LastReprovideBatchSize uint64 `json:"LastReprovideBatchSize,omitempty"`
	ReprovideInterval      string `json:"ReprovideInterval,omitempty"`
	AvgReprovideDuration   string `json:"AvgReprovideDuration,omitempty"`
	LastReprovideDuration  string `json:"LastReprovideDuration,omitempty"`
	LastRun                string `json:"LastRun,omitempty"`
}

type StatsReprovideResponseSweep struct {
	Closed       bool                                    `json:"closed"`
	Connectivity StatsReprovideResponseSweepConnectivity `json:"connectivity"`
	Queues       StatsReprovideResponseSweepQueues       `json:"queues"`
	Schedule     StatsReprovideResponseSweepSchedule     `json:"schedule"`
	Workers      StatsReprovideResponseSweepWorkers      `json:"workers"`
	Timing       StatsReprovideResponseSweepTiming       `json:"timing"`
	Operations   StatsReprovideResponseSweepOperations   `json:"operations"`
	Network      StatsReprovideResponseSweepNetwork      `json:"network"`
}

type StatsReprovideResponseSweepConnectivity struct {
	Status string `json:"status"`
	Since  string `json:"since"`
}

type StatsReprovideResponseSweepNetwork struct {
	Peers                    int     `json:"peers"`
	Reachable                int     `json:"reachable"`
	CompleteKeyspaceCoverage bool    `json:"complete_keyspace_coverage"`
	AvgRegionSize            float64 `json:"avg_region_size"`
	AvgHolders               float64 `json:"avg_holders"`
	ReplicationFactor        int     `json:"replication_factor"`
}

type StatsReprovideResponseSweepOperations struct {
	Ongoing StatsReprovideResponseSweepOperationsOngoing `json:"ongoing"`
	Past    StatsReprovideResponseSweepOperationsPast    `json:"past"`
}

type StatsReprovideResponseSweepOperationsOngoing struct {
	RegionProvides   int `json:"region_provides"`
	KeyProvides      int `json:"key_provides"`
	RegionReprovides int `json:"region_reprovides"`
	KeyReprovides    int `json:"key_reprovides"`
}

type StatsReprovideResponseSweepOperationsPast struct {
	RecordsProvided           int64   `json:"records_provided"`
	KeysProvided              int64   `json:"keys_provided"`
	KeysFailed                int64   `json:"keys_failed"`
	KeysProvidedPerMinute     float64 `json:"keys_provided_per_minute"`
	KeysReprovidedPerMinute   float64 `json:"keys_reprovided_per_minute"`
	RegionReprovideDuration   string  `json:"reprovide_duration"`
	AvgKeysPerReprovide       float64 `json:"avg_keys_per_reprovide"`
	RegionReprovidedLastCycle int64   `json:"regions_reprovided_last_cycle"`
}

type StatsReprovideResponseSweepQueues struct {
	PendingKeyProvides      int64 `json:"pending_key_provides"`
	PendingRegionProvides   int64 `json:"pending_region_provides"`
	PendingRegionReprovides int64 `json:"pending_region_reprovides"`
}

type StatsReprovideResponseSweepSchedule struct {
	Keys                int64   `json:"keys"`
	Regions             int64   `json:"regions"`
	AvgPrefixLength     float64 `json:"avg_prefix_length"`
	NextReprovideAt     string  `json:"next_reprovide_at"`
	NextReprovidePrefix string  `json:"next_reprovide_prefix"`
}

type StatsReprovideResponseSweepTiming struct {
	Uptime             string `json:"uptime"`
	ReprovidesInterval string `json:"reprovides_interval"`
	CycleStart         string `json:"cycle_start"`
	CurrentTimeOffset  string `json:"current_time_offset"`
	MaxReprovideDelay  string `json:"max_reprovide_delay"`
}

type StatsReprovideResponseSweepWorkers struct {
	Max                      int `json:"max"`
	Active                   int `json:"active"`
	ActivePeriodic           int `json:"active_periodic"`
	ActiveBurst              int `json:"active_burst"`
	DedicatedPeriodic        int `json:"dedicated_periodic"`
	DedicatedBurst           int `json:"dedicated_burst"`
	QueuedPeriodic           int `json:"queued_periodic"`
	QueuedBurst              int `json:"queued_burst"`
	MaxProvideConnsPerWorker int `json:"max_provide_conns_per_worker"`
}

// StatsBitswapOption configures the stats/bitswap command.
type StatsBitswapOption func(RequestBuilder)

// StatsBitswapVerbose sets the verbose option.
// Print extra information.
func StatsBitswapVerbose(v bool) StatsBitswapOption {
	return func(rb RequestBuilder) { rb.Option("verbose", v) }
}

// StatsBitswapHuman sets the human option.
// Print sizes in human readable format (e.g., 1K 234M 2G).
func StatsBitswapHuman(v bool) StatsBitswapOption {
	return func(rb RequestBuilder) { rb.Option("human", v) }
}

// StatsBitswap show some diagnostic information on the bitswap agent..
func (a *HttpApi) StatsBitswap(ctx context.Context, opts ...StatsBitswapOption) (*StatsBitswapResponse, error) {
	req := a.Request("stats/bitswap")
	for _, o := range opts {
		o(req)
	}
	var resp StatsBitswapResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// StatsBwOption configures the stats/bw command.
type StatsBwOption func(RequestBuilder)

// StatsBwPeer sets the peer option.
// Specify a peer to print bandwidth for.
func StatsBwPeer(v string) StatsBwOption {
	return func(rb RequestBuilder) { rb.Option("peer", v) }
}

// StatsBwProto sets the proto option.
// Specify a protocol to print bandwidth for.
func StatsBwProto(v string) StatsBwOption {
	return func(rb RequestBuilder) { rb.Option("proto", v) }
}

// StatsBwPoll sets the poll option.
// Print bandwidth at an interval.
func StatsBwPoll(v bool) StatsBwOption {
	return func(rb RequestBuilder) { rb.Option("poll", v) }
}

// StatsBwInterval sets the interval option.
// Time interval to wait between updating output, if 'poll' is true.      This accepts durations such as "300s", "1.5h" or "2h45m". Valid time units are:     "ns", "us" (or "µs"), "ms", "s", "m", "h". Default: 1s.
func StatsBwInterval(v string) StatsBwOption {
	return func(rb RequestBuilder) { rb.Option("interval", v) }
}

// StatsBw print IPFS bandwidth information..
func (a *HttpApi) StatsBw(ctx context.Context, opts ...StatsBwOption) iter.Seq2[StatsBwResponse, error] {
	return func(yield func(StatsBwResponse, error) bool) {
		req := a.Request("stats/bw")
		for _, o := range opts {
			o(req)
		}
		resp, err := req.Send(ctx)
		if err != nil {
			yield(StatsBwResponse{}, err)
			return
		}
		defer resp.Close()
		if resp.Error != nil {
			yield(StatsBwResponse{}, resp.Error)
			return
		}
		dec := json.NewDecoder(resp.Output)
		for dec.More() {
			var item StatsBwResponse
			if err := dec.Decode(&item); err != nil {
				yield(StatsBwResponse{}, err)
				return
			}
			if !yield(item, nil) {
				return
			}
		}
	}
}

// StatsDht returns statistics about the node's DHT(s)..
func (a *HttpApi) StatsDht(ctx context.Context, dht ...string) iter.Seq2[StatsDhtResponse, error] {
	return func(yield func(StatsDhtResponse, error) bool) {
		req := a.Request("stats/dht").Arguments(dht...)
		resp, err := req.Send(ctx)
		if err != nil {
			yield(StatsDhtResponse{}, err)
			return
		}
		defer resp.Close()
		if resp.Error != nil {
			yield(StatsDhtResponse{}, resp.Error)
			return
		}
		dec := json.NewDecoder(resp.Output)
		for dec.More() {
			var item StatsDhtResponse
			if err := dec.Decode(&item); err != nil {
				yield(StatsDhtResponse{}, err)
				return
			}
			if !yield(item, nil) {
				return
			}
		}
	}
}

// StatsProvideOption configures the stats/provide command.
type StatsProvideOption func(RequestBuilder)

// StatsProvideLan sets the lan option.
// Show stats for LAN DHT only (for Sweep+Dual DHT only).
func StatsProvideLan(v bool) StatsProvideOption {
	return func(rb RequestBuilder) { rb.Option("lan", v) }
}

// StatsProvideAll sets the all option.
// Display all provide sweep stats.
func StatsProvideAll(v bool) StatsProvideOption {
	return func(rb RequestBuilder) { rb.Option("all", v) }
}

// StatsProvideCompact sets the compact option.
// Display stats in 2-column layout (requires --all).
func StatsProvideCompact(v bool) StatsProvideOption {
	return func(rb RequestBuilder) { rb.Option("compact", v) }
}

// StatsProvideConnectivity sets the connectivity option.
// Display DHT connectivity status.
func StatsProvideConnectivity(v bool) StatsProvideOption {
	return func(rb RequestBuilder) { rb.Option("connectivity", v) }
}

// StatsProvideNetwork sets the network option.
// Display network stats (peers, reachability, region size).
func StatsProvideNetwork(v bool) StatsProvideOption {
	return func(rb RequestBuilder) { rb.Option("network", v) }
}

// StatsProvideSchedule sets the schedule option.
// Display reprovide schedule (CIDs/regions scheduled, next reprovide time).
func StatsProvideSchedule(v bool) StatsProvideOption {
	return func(rb RequestBuilder) { rb.Option("schedule", v) }
}

// StatsProvideTimings sets the timings option.
// Display timing information (uptime, cycle start, reprovide interval).
func StatsProvideTimings(v bool) StatsProvideOption {
	return func(rb RequestBuilder) { rb.Option("timings", v) }
}

// StatsProvideWorkers sets the workers option.
// Display worker pool stats (active/available/queued workers).
func StatsProvideWorkers(v bool) StatsProvideOption {
	return func(rb RequestBuilder) { rb.Option("workers", v) }
}

// StatsProvideOperations sets the operations option.
// Display operation stats (ongoing/past provides, rates, errors).
func StatsProvideOperations(v bool) StatsProvideOption {
	return func(rb RequestBuilder) { rb.Option("operations", v) }
}

// StatsProvideQueues sets the queues option.
// Display provide and reprovide queue sizes.
func StatsProvideQueues(v bool) StatsProvideOption {
	return func(rb RequestBuilder) { rb.Option("queues", v) }
}

// Deprecated: StatsProvide may be removed in a future release.
// StatsProvide deprecated command, use 'ipfs provide stat' instead..
func (a *HttpApi) StatsProvide(ctx context.Context, opts ...StatsProvideOption) (*StatsProvideResponse, error) {
	req := a.Request("stats/provide")
	for _, o := range opts {
		o(req)
	}
	var resp StatsProvideResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// StatsRepoOption configures the stats/repo command.
type StatsRepoOption func(RequestBuilder)

// StatsRepoSizeOnly sets the size-only option.
// Only report RepoSize and StorageMax.
func StatsRepoSizeOnly(v bool) StatsRepoOption {
	return func(rb RequestBuilder) { rb.Option("size-only", v) }
}

// StatsRepoHuman sets the human option.
// Print sizes in human readable format (e.g., 1K 234M 2G).
func StatsRepoHuman(v bool) StatsRepoOption {
	return func(rb RequestBuilder) { rb.Option("human", v) }
}

// StatsRepo get stats for the currently used repo..
func (a *HttpApi) StatsRepo(ctx context.Context, opts ...StatsRepoOption) (*StatsRepoResponse, error) {
	req := a.Request("stats/repo")
	for _, o := range opts {
		o(req)
	}
	var resp StatsRepoResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// StatsReprovideOption configures the stats/reprovide command.
type StatsReprovideOption func(RequestBuilder)

// StatsReprovideLan sets the lan option.
// Show stats for LAN DHT only (for Sweep+Dual DHT only).
func StatsReprovideLan(v bool) StatsReprovideOption {
	return func(rb RequestBuilder) { rb.Option("lan", v) }
}

// StatsReprovideAll sets the all option.
// Display all provide sweep stats.
func StatsReprovideAll(v bool) StatsReprovideOption {
	return func(rb RequestBuilder) { rb.Option("all", v) }
}

// StatsReprovideCompact sets the compact option.
// Display stats in 2-column layout (requires --all).
func StatsReprovideCompact(v bool) StatsReprovideOption {
	return func(rb RequestBuilder) { rb.Option("compact", v) }
}

// StatsReprovideConnectivity sets the connectivity option.
// Display DHT connectivity status.
func StatsReprovideConnectivity(v bool) StatsReprovideOption {
	return func(rb RequestBuilder) { rb.Option("connectivity", v) }
}

// StatsReprovideNetwork sets the network option.
// Display network stats (peers, reachability, region size).
func StatsReprovideNetwork(v bool) StatsReprovideOption {
	return func(rb RequestBuilder) { rb.Option("network", v) }
}

// StatsReprovideSchedule sets the schedule option.
// Display reprovide schedule (CIDs/regions scheduled, next reprovide time).
func StatsReprovideSchedule(v bool) StatsReprovideOption {
	return func(rb RequestBuilder) { rb.Option("schedule", v) }
}

// StatsReprovideTimings sets the timings option.
// Display timing information (uptime, cycle start, reprovide interval).
func StatsReprovideTimings(v bool) StatsReprovideOption {
	return func(rb RequestBuilder) { rb.Option("timings", v) }
}

// StatsReprovideWorkers sets the workers option.
// Display worker pool stats (active/available/queued workers).
func StatsReprovideWorkers(v bool) StatsReprovideOption {
	return func(rb RequestBuilder) { rb.Option("workers", v) }
}

// StatsReprovideOperations sets the operations option.
// Display operation stats (ongoing/past provides, rates, errors).
func StatsReprovideOperations(v bool) StatsReprovideOption {
	return func(rb RequestBuilder) { rb.Option("operations", v) }
}

// StatsReprovideQueues sets the queues option.
// Display provide and reprovide queue sizes.
func StatsReprovideQueues(v bool) StatsReprovideOption {
	return func(rb RequestBuilder) { rb.Option("queues", v) }
}

// Deprecated: StatsReprovide may be removed in a future release.
// StatsReprovide deprecated command, use 'ipfs provide stat' instead..
func (a *HttpApi) StatsReprovide(ctx context.Context, opts ...StatsReprovideOption) (*StatsReprovideResponse, error) {
	req := a.Request("stats/reprovide")
	for _, o := range opts {
		o(req)
	}
	var resp StatsReprovideResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
