// Code generated by tools/gen-rpc-client; DO NOT EDIT.

package rpc

import (
	"context"
	"io"
)

type NameInspectResponse struct {
	Entry         NameInspectResponseEntry       `json:"Entry,omitempty"`
	PbSize        int                            `json:"PbSize,omitempty"`
	SignatureType string                         `json:"SignatureType,omitempty"`
	HexDump       string                         `json:"HexDump,omitempty"`
	Validation    *NameInspectResponseValidation `json:"Validation,omitempty"`
}

type NameInspectResponseEntry struct {
	Value        string  `json:"Value,omitempty"`
	ValidityType *int64  `json:"ValidityType,omitempty"`
	Validity     *string `json:"Validity,omitempty"`
	Sequence     *uint64 `json:"Sequence,omitempty"`
	TTL          *string `json:"TTL,omitempty"`
}

type NameInspectResponseValidation struct {
	Valid  bool   `json:"Valid,omitempty"`
	Reason string `json:"Reason,omitempty"`
	Name   string `json:"Name,omitempty"`
}

type NamePublishResponse struct {
	Name  string `json:"Name,omitempty"`
	Value string `json:"Value,omitempty"`
}

type NamePubsubCancelResponse struct {
	Canceled bool `json:"Canceled,omitempty"`
}

type NamePubsubStateResponse struct {
	Enabled bool `json:"Enabled,omitempty"`
}

type NamePubsubSubsResponse struct {
	Strings []string `json:"Strings,omitempty"`
}

type NamePutResponse struct {
	Name  string `json:"Name,omitempty"`
	Value string `json:"Value,omitempty"`
}

type NameResolveResponse struct {
	Path string `json:"Path,omitempty"`
}

// Experimental: NameGet is not yet stable.
// NameGet retrieve a signed IPNS record..
func (a *HttpApi) NameGet(ctx context.Context, name string) (*Response, error) {
	req := a.Request("name/get", name)
	resp, err := req.Send(ctx)
	if err != nil {
		return nil, err
	}
	if resp.Error != nil {
		resp.Close()
		return nil, resp.Error
	}
	return resp, nil
}

// NameInspectOption configures the name/inspect command.
type NameInspectOption func(RequestBuilder)

// NameInspectVerify sets the verify option.
// CID of the public IPNS key to validate against.
func NameInspectVerify(v string) NameInspectOption {
	return func(rb RequestBuilder) { rb.Option("verify", v) }
}

// NameInspectDump sets the dump option.
// Include a full hex dump of the raw Protobuf record. Default: true.
func NameInspectDump(v bool) NameInspectOption {
	return func(rb RequestBuilder) { rb.Option("dump", v) }
}

// Experimental: NameInspect is not yet stable.
// NameInspect inspects an IPNS Record.
func (a *HttpApi) NameInspect(ctx context.Context, record io.Reader, opts ...NameInspectOption) (*NameInspectResponse, error) {
	req := a.Request("name/inspect")
	req = req.FileBody(record).(RequestBuilder)
	for _, o := range opts {
		o(req)
	}
	var resp NameInspectResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// NamePublishOption configures the name/publish command.
type NamePublishOption func(RequestBuilder)

// NamePublishKey sets the key option.
// Name of the key to be used or a valid PeerID, as listed by 'ipfs key list -l'. Default: self.
func NamePublishKey(v string) NamePublishOption {
	return func(rb RequestBuilder) { rb.Option("key", v) }
}

// NamePublishResolve sets the resolve option.
// Check if the given path can be resolved before publishing. Default: true.
func NamePublishResolve(v bool) NamePublishOption {
	return func(rb RequestBuilder) { rb.Option("resolve", v) }
}

// NamePublishLifetime sets the lifetime option.
// Time duration the signed record will be valid for. Accepts durations such as "300s", "1.5h" or "7d2h45m". Default: 48h0m0s.
func NamePublishLifetime(v string) NamePublishOption {
	return func(rb RequestBuilder) { rb.Option("lifetime", v) }
}

// NamePublishTtl sets the ttl option.
// Time duration hint, akin to --lifetime, indicating how long to cache this record before checking for updates. Default: 5m0s.
func NamePublishTtl(v string) NamePublishOption {
	return func(rb RequestBuilder) { rb.Option("ttl", v) }
}

// NamePublishQuieter sets the quieter option.
// Write only final IPNS Name encoded as CIDv1 (for use in /ipns content paths).
func NamePublishQuieter(v bool) NamePublishOption {
	return func(rb RequestBuilder) { rb.Option("quieter", v) }
}

// NamePublishV1compat sets the v1compat option.
// Produce a backward-compatible IPNS Record by including fields for both V1 and V2 signatures. Default: true.
func NamePublishV1compat(v bool) NamePublishOption {
	return func(rb RequestBuilder) { rb.Option("v1compat", v) }
}

// NamePublishAllowOffline sets the allow-offline option.
// Allow publishing when offline - publishes to local datastore without requiring network connectivity.
func NamePublishAllowOffline(v bool) NamePublishOption {
	return func(rb RequestBuilder) { rb.Option("allow-offline", v) }
}

// NamePublishAllowDelegated sets the allow-delegated option.
// Allow publishing without DHT connectivity - uses local datastore and HTTP delegated publishers only.
func NamePublishAllowDelegated(v bool) NamePublishOption {
	return func(rb RequestBuilder) { rb.Option("allow-delegated", v) }
}

// NamePublishSequence sets the sequence option.
// Set a custom sequence number for the IPNS record (must be higher than current).
func NamePublishSequence(v uint64) NamePublishOption {
	return func(rb RequestBuilder) { rb.Option("sequence", v) }
}

// NamePublishIpnsBase sets the ipns-base option.
// Encoding used for keys: Can either be a multibase encoded CID or a base58btc encoded multihash. Takes {b58mh|base36|k|base32|b...}. Default: base36.
func NamePublishIpnsBase(v string) NamePublishOption {
	return func(rb RequestBuilder) { rb.Option("ipns-base", v) }
}

// NamePublish publish IPNS names..
func (a *HttpApi) NamePublish(ctx context.Context, ipfs_path string, opts ...NamePublishOption) (*NamePublishResponse, error) {
	req := a.Request("name/publish", ipfs_path)
	for _, o := range opts {
		o(req)
	}
	var resp NamePublishResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// Experimental: NamePubsubCancel is not yet stable.
// NamePubsubCancel cancel a name subscription..
func (a *HttpApi) NamePubsubCancel(ctx context.Context, name string) (*NamePubsubCancelResponse, error) {
	req := a.Request("name/pubsub/cancel", name)
	var resp NamePubsubCancelResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// Experimental: NamePubsubState is not yet stable.
// NamePubsubState query the state of IPNS pubsub..
func (a *HttpApi) NamePubsubState(ctx context.Context) (*NamePubsubStateResponse, error) {
	req := a.Request("name/pubsub/state")
	var resp NamePubsubStateResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// NamePubsubSubsOption configures the name/pubsub/subs command.
type NamePubsubSubsOption func(RequestBuilder)

// NamePubsubSubsIpnsBase sets the ipns-base option.
// Encoding used for keys: Can either be a multibase encoded CID or a base58btc encoded multihash. Takes {b58mh|base36|k|base32|b...}. Default: base36.
func NamePubsubSubsIpnsBase(v string) NamePubsubSubsOption {
	return func(rb RequestBuilder) { rb.Option("ipns-base", v) }
}

// Experimental: NamePubsubSubs is not yet stable.
// NamePubsubSubs show current name subscriptions..
func (a *HttpApi) NamePubsubSubs(ctx context.Context, opts ...NamePubsubSubsOption) (*NamePubsubSubsResponse, error) {
	req := a.Request("name/pubsub/subs")
	for _, o := range opts {
		o(req)
	}
	var resp NamePubsubSubsResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// NamePutOption configures the name/put command.
type NamePutOption func(RequestBuilder)

// NamePutForce sets the force option.
// Skip validation (signature, sequence, size).
func NamePutForce(v bool) NamePutOption {
	return func(rb RequestBuilder) { rb.Option("force", v) }
}

// NamePutAllowOffline sets the allow-offline option.
// Store locally without broadcasting to the network.
func NamePutAllowOffline(v bool) NamePutOption {
	return func(rb RequestBuilder) { rb.Option("allow-offline", v) }
}

// NamePutAllowDelegated sets the allow-delegated option.
// Publish via HTTP delegated publishers only (no DHT).
func NamePutAllowDelegated(v bool) NamePutOption {
	return func(rb RequestBuilder) { rb.Option("allow-delegated", v) }
}

// NamePutQuiet sets the quiet option.
// Write no output.
func NamePutQuiet(v bool) NamePutOption {
	return func(rb RequestBuilder) { rb.Option("quiet", v) }
}

// Experimental: NamePut is not yet stable.
// NamePut store a pre-signed IPNS record in the routing system..
func (a *HttpApi) NamePut(ctx context.Context, name string, record io.Reader, opts ...NamePutOption) (*NamePutResponse, error) {
	req := a.Request("name/put", name)
	req = req.FileBody(record).(RequestBuilder)
	for _, o := range opts {
		o(req)
	}
	var resp NamePutResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// NameResolveOption configures the name/resolve command.
type NameResolveOption func(RequestBuilder)

// NameResolveRecursive sets the recursive option.
// Resolve until the result is not an IPNS name. Default: true.
func NameResolveRecursive(v bool) NameResolveOption {
	return func(rb RequestBuilder) { rb.Option("recursive", v) }
}

// NameResolveNocache sets the nocache option.
// Do not use cached entries.
func NameResolveNocache(v bool) NameResolveOption {
	return func(rb RequestBuilder) { rb.Option("nocache", v) }
}

// NameResolveDhtRecordCount sets the dht-record-count option.
// Number of records to request for DHT resolution. Default: 16.
func NameResolveDhtRecordCount(v uint) NameResolveOption {
	return func(rb RequestBuilder) { rb.Option("dht-record-count", v) }
}

// NameResolveDhtTimeout sets the dht-timeout option.
// Max time to collect values during DHT resolution e.g. "30s". Pass 0 for no timeout. Default: 1m0s.
func NameResolveDhtTimeout(v string) NameResolveOption {
	return func(rb RequestBuilder) { rb.Option("dht-timeout", v) }
}

// NameResolveStream sets the stream option.
// Stream entries as they are found.
func NameResolveStream(v bool) NameResolveOption {
	return func(rb RequestBuilder) { rb.Option("stream", v) }
}

// NameResolve resolve IPNS names..
func (a *HttpApi) NameResolve(ctx context.Context, name string, opts ...NameResolveOption) (*NameResolveResponse, error) {
	req := a.Request("name/resolve", name)
	for _, o := range opts {
		o(req)
	}
	var resp NameResolveResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
