// Code generated by tools/gen-rpc-client; DO NOT EDIT.

package rpc

import (
	"context"
	"encoding/json"
	"iter"
)

type PingResponse struct {
	Success bool   `json:"Success,omitempty"`
	Time    string `json:"Time,omitempty"`
	Text    string `json:"Text,omitempty"`
}

// PingOption configures the ping command.
type PingOption func(RequestBuilder)

// PingCount sets the count option.
// Number of ping messages to send. Default: 10.
func PingCount(v int) PingOption {
	return func(rb RequestBuilder) { rb.Option("count", v) }
}

// Ping send echo request packets to IPFS hosts..
func (a *HttpApi) Ping(ctx context.Context, peer_ID []string, opts ...PingOption) iter.Seq2[PingResponse, error] {
	return func(yield func(PingResponse, error) bool) {
		req := a.Request("ping").Arguments(peer_ID...)
		for _, o := range opts {
			o(req)
		}
		resp, err := req.Send(ctx)
		if err != nil {
			yield(PingResponse{}, err)
			return
		}
		defer resp.Close()
		if resp.Error != nil {
			yield(PingResponse{}, resp.Error)
			return
		}
		dec := json.NewDecoder(resp.Output)
		for dec.More() {
			var item PingResponse
			if err := dec.Decode(&item); err != nil {
				yield(PingResponse{}, err)
				return
			}
			if !yield(item, nil) {
				return
			}
		}
	}
}
