// Code generated by tools/gen-rpc-client; DO NOT EDIT.

package rpc

import (
	"context"
)

type ObjectDiffResponse struct {
	Changes []*ObjectDiffResponseChanges `json:"Changes,omitempty"`
}

type ObjectDiffResponseChanges struct {
	Type   int    `json:"Type,omitempty"`
	Path   string `json:"Path,omitempty"`
	Before string `json:"Before,omitempty"`
	After  string `json:"After,omitempty"`
}

type ObjectPatchAddLinkResponse struct {
	Hash  string                            `json:"Hash,omitempty"`
	Links []ObjectPatchAddLinkResponseLinks `json:"Links,omitempty"`
}

type ObjectPatchAddLinkResponseLinks struct {
	Name string `json:"Name,omitempty"`
	Hash string `json:"Hash,omitempty"`
	Size uint64 `json:"Size,omitempty"`
}

type ObjectPatchRmLinkResponse struct {
	Hash  string                           `json:"Hash,omitempty"`
	Links []ObjectPatchRmLinkResponseLinks `json:"Links,omitempty"`
}

type ObjectPatchRmLinkResponseLinks struct {
	Name string `json:"Name,omitempty"`
	Hash string `json:"Hash,omitempty"`
	Size uint64 `json:"Size,omitempty"`
}

// ObjectDiffOption configures the object/diff command.
type ObjectDiffOption func(RequestBuilder)

// ObjectDiffVerbose sets the verbose option.
// Print extra information.
func ObjectDiffVerbose(v bool) ObjectDiffOption {
	return func(rb RequestBuilder) { rb.Option("verbose", v) }
}

// Deprecated: ObjectDiff may be removed in a future release.
// ObjectDiff display the diff between two IPFS objects..
func (a *HttpApi) ObjectDiff(ctx context.Context, obj_a string, obj_b string, opts ...ObjectDiffOption) (*ObjectDiffResponse, error) {
	req := a.Request("object/diff", obj_a, obj_b)
	for _, o := range opts {
		o(req)
	}
	var resp ObjectDiffResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// ObjectPatchAddLinkOption configures the object/patch/add-link command.
type ObjectPatchAddLinkOption func(RequestBuilder)

// ObjectPatchAddLinkCreate sets the create option.
// Create intermediary nodes.
func ObjectPatchAddLinkCreate(v bool) ObjectPatchAddLinkOption {
	return func(rb RequestBuilder) { rb.Option("create", v) }
}

// Deprecated: ObjectPatchAddLink may be removed in a future release.
// ObjectPatchAddLink deprecated way to add a link to a given dag-pb..
func (a *HttpApi) ObjectPatchAddLink(ctx context.Context, root string, name string, ref string, opts ...ObjectPatchAddLinkOption) (*ObjectPatchAddLinkResponse, error) {
	req := a.Request("object/patch/add-link", root, name, ref)
	for _, o := range opts {
		o(req)
	}
	var resp ObjectPatchAddLinkResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// Deprecated: ObjectPatchRmLink may be removed in a future release.
// ObjectPatchRmLink deprecated way to remove a link from dag-pb object..
func (a *HttpApi) ObjectPatchRmLink(ctx context.Context, root string, name string) (*ObjectPatchRmLinkResponse, error) {
	req := a.Request("object/patch/rm-link", root, name)
	var resp ObjectPatchRmLinkResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
