// Code generated by tools/gen-rpc-client; DO NOT EDIT.

package rpc

import (
	"context"
	"encoding/json"
)

type DiagCmdsItem struct {
	StartTime string                     `json:"StartTime,omitempty"`
	EndTime   string                     `json:"EndTime,omitempty"`
	Active    bool                       `json:"Active,omitempty"`
	Command   string                     `json:"Command,omitempty"`
	Options   map[string]json.RawMessage `json:"Options,omitempty"`
	Args      []string                   `json:"Args,omitempty"`
	ID        int                        `json:"ID,omitempty"`
}

// DiagCmdsOption configures the diag/cmds command.
type DiagCmdsOption func(RequestBuilder)

// DiagCmdsVerbose sets the verbose option.
// Print extra information.
func DiagCmdsVerbose(v bool) DiagCmdsOption {
	return func(rb RequestBuilder) { rb.Option("verbose", v) }
}

// DiagCmds list commands run on this IPFS node..
func (a *HttpApi) DiagCmds(ctx context.Context, opts ...DiagCmdsOption) ([]DiagCmdsItem, error) {
	req := a.Request("diag/cmds")
	for _, o := range opts {
		o(req)
	}
	var resp []DiagCmdsItem
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return resp, nil
}

// DiagCmdsClear clear inactive requests from the log..
func (a *HttpApi) DiagCmdsClear(ctx context.Context) (*Response, error) {
	req := a.Request("diag/cmds/clear")
	resp, err := req.Send(ctx)
	if err != nil {
		return nil, err
	}
	if resp.Error != nil {
		resp.Close()
		return nil, resp.Error
	}
	return resp, nil
}

// DiagCmdsSetTime set how long to keep inactive requests in the log..
func (a *HttpApi) DiagCmdsSetTime(ctx context.Context, time string) (*Response, error) {
	req := a.Request("diag/cmds/set-time", time)
	resp, err := req.Send(ctx)
	if err != nil {
		return nil, err
	}
	if resp.Error != nil {
		resp.Close()
		return nil, resp.Error
	}
	return resp, nil
}

// DiagProfileOption configures the diag/profile command.
type DiagProfileOption func(RequestBuilder)

// DiagProfileOutput sets the output option.
// The path where the output .zip should be stored. Default: ./ipfs-profile-[timestamp].zip.
func DiagProfileOutput(v string) DiagProfileOption {
	return func(rb RequestBuilder) { rb.Option("output", v) }
}

// DiagProfileCollectors sets the collectors option.
// The list of collectors to use for collecting diagnostic data. Default: [goroutines-stack goroutines-pprof version heap allocs bin cpu mutex block trace].
func DiagProfileCollectors(v []string) DiagProfileOption {
	return func(rb RequestBuilder) { rb.Option("collectors", v) }
}

// DiagProfileProfileTime sets the profile-time option.
// The amount of time spent profiling. If this is set to 0, then sampling profiles are skipped. Default: 30s.
func DiagProfileProfileTime(v string) DiagProfileOption {
	return func(rb RequestBuilder) { rb.Option("profile-time", v) }
}

// DiagProfileMutexProfileFraction sets the mutex-profile-fraction option.
// The fraction 1/n of mutex contention events that are reported in the mutex profile. Default: 4.
func DiagProfileMutexProfileFraction(v int) DiagProfileOption {
	return func(rb RequestBuilder) { rb.Option("mutex-profile-fraction", v) }
}

// DiagProfileBlockProfileRate sets the block-profile-rate option.
// The duration to wait between sampling goroutine-blocking events for the blocking profile. Default: 1ms.
func DiagProfileBlockProfileRate(v string) DiagProfileOption {
	return func(rb RequestBuilder) { rb.Option("block-profile-rate", v) }
}

// DiagProfile collect a performance profile for debugging..
func (a *HttpApi) DiagProfile(ctx context.Context, opts ...DiagProfileOption) (*Response, error) {
	req := a.Request("diag/profile")
	for _, o := range opts {
		o(req)
	}
	resp, err := req.Send(ctx)
	if err != nil {
		return nil, err
	}
	if resp.Error != nil {
		resp.Close()
		return nil, resp.Error
	}
	return resp, nil
}

// DiagSys print system diagnostic information..
func (a *HttpApi) DiagSys(ctx context.Context) (*Response, error) {
	req := a.Request("diag/sys")
	resp, err := req.Send(ctx)
	if err != nil {
		return nil, err
	}
	if resp.Error != nil {
		resp.Close()
		return nil, resp.Error
	}
	return resp, nil
}
