// Code generated by tools/gen-rpc-client; DO NOT EDIT.

package rpc

import (
	"context"
)

// Shutdown shut down the IPFS daemon..
func (a *HttpApi) Shutdown(ctx context.Context) (*Response, error) {
	req := a.Request("shutdown")
	resp, err := req.Send(ctx)
	if err != nil {
		return nil, err
	}
	if resp.Error != nil {
		resp.Close()
		return nil, resp.Error
	}
	return resp, nil
}
