// Code generated by tools/gen-rpc-client; DO NOT EDIT.

package rpc

import (
	"context"
)

type IdResponse struct {
	ID           string   `json:"ID,omitempty"`
	PublicKey    string   `json:"PublicKey,omitempty"`
	Addresses    []string `json:"Addresses,omitempty"`
	AgentVersion string   `json:"AgentVersion,omitempty"`
	Protocols    []string `json:"Protocols,omitempty"`
}

// IdOption configures the id command.
type IdOption func(RequestBuilder)

// IdFormat sets the format option.
// Optional output format.
func IdFormat(v string) IdOption {
	return func(rb RequestBuilder) { rb.Option("format", v) }
}

// IdPeeridBase sets the peerid-base option.
// Encoding used for peer IDs: Can either be a multibase encoded CID or a base58btc encoded multihash. Takes {b58mh|base36|k|base32|b...}. Default: b58mh.
func IdPeeridBase(v string) IdOption {
	return func(rb RequestBuilder) { rb.Option("peerid-base", v) }
}

// Id show IPFS node id info..
func (a *HttpApi) Id(ctx context.Context, peerid string, opts ...IdOption) (*IdResponse, error) {
	req := a.Request("id", peerid)
	for _, o := range opts {
		o(req)
	}
	var resp IdResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
