// Code generated by tools/gen-rpc-client; DO NOT EDIT.

package rpc

import (
	"context"
	"encoding/json"
	"iter"
)

type DhtQueryResponse struct {
	ID        string                       `json:"ID,omitempty"`
	Type      int                          `json:"Type,omitempty"`
	Responses []*DhtQueryResponseResponses `json:"Responses,omitempty"`
	Extra     string                       `json:"Extra,omitempty"`
}

type DhtQueryResponseResponses struct {
	ID    string   `json:"ID,omitempty"`
	Addrs []string `json:"Addrs,omitempty"`
}

// DhtQueryOption configures the dht/query command.
type DhtQueryOption func(RequestBuilder)

// DhtQueryVerbose sets the verbose option.
// Print extra information.
func DhtQueryVerbose(v bool) DhtQueryOption {
	return func(rb RequestBuilder) { rb.Option("verbose", v) }
}

// Deprecated: DhtQuery may be removed in a future release.
// DhtQuery find the closest Peer IDs to a given Peer ID by querying the DHT..
func (a *HttpApi) DhtQuery(ctx context.Context, peerID []string, opts ...DhtQueryOption) iter.Seq2[DhtQueryResponse, error] {
	return func(yield func(DhtQueryResponse, error) bool) {
		req := a.Request("dht/query").Arguments(peerID...)
		for _, o := range opts {
			o(req)
		}
		resp, err := req.Send(ctx)
		if err != nil {
			yield(DhtQueryResponse{}, err)
			return
		}
		defer resp.Close()
		if resp.Error != nil {
			yield(DhtQueryResponse{}, resp.Error)
			return
		}
		dec := json.NewDecoder(resp.Output)
		for dec.More() {
			var item DhtQueryResponse
			if err := dec.Decode(&item); err != nil {
				yield(DhtQueryResponse{}, err)
				return
			}
			if !yield(item, nil) {
				return
			}
		}
	}
}
