// Code generated by tools/gen-rpc-client; DO NOT EDIT.

package rpc

import (
	"context"
	"encoding/json"
	"io"
	"iter"
)

type DagImportResponse struct {
	Root  *DagImportResponseRoot  `json:",omitempty"`
	Stats *DagImportResponseStats `json:",omitempty"`
}

type DagImportResponseRoot struct {
	Cid         string `json:"Cid,omitempty"`
	PinErrorMsg string `json:"PinErrorMsg,omitempty"`
}

type DagImportResponseStats struct {
	BlockCount      uint64 `json:"BlockCount,omitempty"`
	BlockBytesCount uint64 `json:"BlockBytesCount,omitempty"`
}

type DagPutResponse struct {
	Cid string `json:"Cid,omitempty"`
}

type DagResolveResponse struct {
	Cid     string `json:"Cid,omitempty"`
	RemPath string `json:"RemPath,omitempty"`
}

type DagStatResponse struct {
	UniqueBlocks  int                             `json:",omitempty"`
	TotalSize     uint64                          `json:",omitempty"`
	SharedSize    uint64                          `json:",omitempty"`
	Ratio         float32                         `json:",omitempty"`
	DagStatsArray []*DagStatResponseDagStatsArray `json:"DagStats,omitempty"`
}

type DagStatResponseDagStatsArray struct {
	Cid       string `json:"Cid,omitempty"`
	Size      uint64 `json:",omitempty"`
	NumBlocks int64  `json:",omitempty"`
}

// DagExportOption configures the dag/export command.
type DagExportOption func(RequestBuilder)

// DagExportProgress sets the progress option.
// Display progress on CLI. Defaults to true when STDERR is a TTY.
func DagExportProgress(v bool) DagExportOption {
	return func(rb RequestBuilder) { rb.Option("progress", v) }
}

// DagExport streams the selected DAG as a .car stream on stdout..
func (a *HttpApi) DagExport(ctx context.Context, root string, opts ...DagExportOption) (*Response, error) {
	req := a.Request("dag/export", root)
	for _, o := range opts {
		o(req)
	}
	resp, err := req.Send(ctx)
	if err != nil {
		return nil, err
	}
	if resp.Error != nil {
		resp.Close()
		return nil, resp.Error
	}
	return resp, nil
}

// DagGetOption configures the dag/get command.
type DagGetOption func(RequestBuilder)

// DagGetOutputCodec sets the output-codec option.
// Format that the object will be encoded as. Default: dag-json.
func DagGetOutputCodec(v string) DagGetOption {
	return func(rb RequestBuilder) { rb.Option("output-codec", v) }
}

// DagGet get a DAG node from IPFS..
func (a *HttpApi) DagGet(ctx context.Context, ref string, opts ...DagGetOption) (*Response, error) {
	req := a.Request("dag/get", ref)
	for _, o := range opts {
		o(req)
	}
	resp, err := req.Send(ctx)
	if err != nil {
		return nil, err
	}
	if resp.Error != nil {
		resp.Close()
		return nil, resp.Error
	}
	return resp, nil
}

// DagImportOption configures the dag/import command.
type DagImportOption func(RequestBuilder)

// DagImportPinRoots sets the pin-roots option.
// Pin optional roots listed in the .car headers after importing. Default: true.
func DagImportPinRoots(v bool) DagImportOption {
	return func(rb RequestBuilder) { rb.Option("pin-roots", v) }
}

// DagImportSilent sets the silent option.
// No output.
func DagImportSilent(v bool) DagImportOption {
	return func(rb RequestBuilder) { rb.Option("silent", v) }
}

// DagImportStats sets the stats option.
// Output stats.
func DagImportStats(v bool) DagImportOption {
	return func(rb RequestBuilder) { rb.Option("stats", v) }
}

// DagImportFastProvideRoot sets the fast-provide-root option.
// Immediately provide root CIDs to DHT in addition to regular queue, for faster discovery. Default: Import.FastProvideRoot.
func DagImportFastProvideRoot(v bool) DagImportOption {
	return func(rb RequestBuilder) { rb.Option("fast-provide-root", v) }
}

// DagImportFastProvideWait sets the fast-provide-wait option.
// Block until the immediate provide completes before returning. Default: Import.FastProvideWait.
func DagImportFastProvideWait(v bool) DagImportOption {
	return func(rb RequestBuilder) { rb.Option("fast-provide-wait", v) }
}

// DagImportAllowBigBlock sets the allow-big-block option.
// Disable block size check and allow creation of blocks bigger than 2MiB. WARNING: such blocks won't be transferable over the standard bitswap. Default: false.
func DagImportAllowBigBlock(v bool) DagImportOption {
	return func(rb RequestBuilder) { rb.Option("allow-big-block", v) }
}

// DagImport import the contents of .car files.
func (a *HttpApi) DagImport(ctx context.Context, path io.Reader, opts ...DagImportOption) iter.Seq2[DagImportResponse, error] {
	return func(yield func(DagImportResponse, error) bool) {
		req := a.Request("dag/import")
		req = req.FileBody(path).(RequestBuilder)
		for _, o := range opts {
			o(req)
		}
		resp, err := req.Send(ctx)
		if err != nil {
			yield(DagImportResponse{}, err)
			return
		}
		defer resp.Close()
		if resp.Error != nil {
			yield(DagImportResponse{}, resp.Error)
			return
		}
		dec := json.NewDecoder(resp.Output)
		for dec.More() {
			var item DagImportResponse
			if err := dec.Decode(&item); err != nil {
				yield(DagImportResponse{}, err)
				return
			}
			if !yield(item, nil) {
				return
			}
		}
	}
}

// DagPutOption configures the dag/put command.
type DagPutOption func(RequestBuilder)

// DagPutStoreCodec sets the store-codec option.
// Codec that the stored object will be encoded with. Default: dag-cbor.
func DagPutStoreCodec(v string) DagPutOption {
	return func(rb RequestBuilder) { rb.Option("store-codec", v) }
}

// DagPutInputCodec sets the input-codec option.
// Codec that the input object is encoded in. Default: dag-json.
func DagPutInputCodec(v string) DagPutOption {
	return func(rb RequestBuilder) { rb.Option("input-codec", v) }
}

// DagPutPin sets the pin option.
// Pin this object when adding.
func DagPutPin(v bool) DagPutOption {
	return func(rb RequestBuilder) { rb.Option("pin", v) }
}

// DagPutHash sets the hash option.
// Hash function to use.
func DagPutHash(v string) DagPutOption {
	return func(rb RequestBuilder) { rb.Option("hash", v) }
}

// DagPutAllowBigBlock sets the allow-big-block option.
// Disable block size check and allow creation of blocks bigger than 2MiB. WARNING: such blocks won't be transferable over the standard bitswap. Default: false.
func DagPutAllowBigBlock(v bool) DagPutOption {
	return func(rb RequestBuilder) { rb.Option("allow-big-block", v) }
}

// DagPut add a DAG node to IPFS..
func (a *HttpApi) DagPut(ctx context.Context, object_data io.Reader, opts ...DagPutOption) (*DagPutResponse, error) {
	req := a.Request("dag/put")
	req = req.FileBody(object_data).(RequestBuilder)
	for _, o := range opts {
		o(req)
	}
	var resp DagPutResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// DagResolve resolve IPLD block..
func (a *HttpApi) DagResolve(ctx context.Context, ref string) (*DagResolveResponse, error) {
	req := a.Request("dag/resolve", ref)
	var resp DagResolveResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// DagStatOption configures the dag/stat command.
type DagStatOption func(RequestBuilder)

// DagStatProgress sets the progress option.
// Show progress on stderr. Auto-detected if stderr is a terminal.
func DagStatProgress(v bool) DagStatOption {
	return func(rb RequestBuilder) { rb.Option("progress", v) }
}

// DagStat gets stats for a DAG..
func (a *HttpApi) DagStat(ctx context.Context, root []string, opts ...DagStatOption) (*DagStatResponse, error) {
	req := a.Request("dag/stat").Arguments(root...)
	for _, o := range opts {
		o(req)
	}
	var resp DagStatResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
