// Code generated by tools/gen-rpc-client; DO NOT EDIT.

package rpc

import (
	"context"
)

type VersionCheckResponse struct {
	UpdateAvailable    bool   `json:"UpdateAvailable,omitempty"`
	RunningVersion     string `json:"RunningVersion,omitempty"`
	GreatestVersion    string `json:"GreatestVersion,omitempty"`
	PeersSampled       int    `json:"PeersSampled,omitempty"`
	WithGreaterVersion int    `json:"WithGreaterVersion,omitempty"`
}

type VersionDepsResponse struct {
	Path       string `json:"Path,omitempty"`
	Version    string `json:"Version,omitempty"`
	ReplacedBy string `json:"ReplacedBy,omitempty"`
	Sum        string `json:"Sum,omitempty"`
}

type VersionResponse struct {
	Version string `json:"Version,omitempty"`
	Commit  string `json:"Commit,omitempty"`
	Repo    string `json:"Repo,omitempty"`
	System  string `json:"System,omitempty"`
	Golang  string `json:"Golang,omitempty"`
}

// VersionOption configures the version command.
type VersionOption func(RequestBuilder)

// VersionNumber sets the number option.
// Only show the version number.
func VersionNumber(v bool) VersionOption {
	return func(rb RequestBuilder) { rb.Option("number", v) }
}

// VersionCommit sets the commit option.
// Show the commit hash.
func VersionCommit(v bool) VersionOption {
	return func(rb RequestBuilder) { rb.Option("commit", v) }
}

// VersionRepo sets the repo option.
// Show repo version.
func VersionRepo(v bool) VersionOption {
	return func(rb RequestBuilder) { rb.Option("repo", v) }
}

// VersionAll sets the all option.
// Show all version information.
func VersionAll(v bool) VersionOption {
	return func(rb RequestBuilder) { rb.Option("all", v) }
}

// Version show IPFS version information..
func (a *HttpApi) Version(ctx context.Context, opts ...VersionOption) (*VersionResponse, error) {
	req := a.Request("version")
	for _, o := range opts {
		o(req)
	}
	var resp VersionResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// VersionCheckOption configures the version/check command.
type VersionCheckOption func(RequestBuilder)

// VersionCheckMinPercent sets the min-percent option.
// Percentage (1-100) of sampled peers with the new Kubo version needed to trigger an update warning. Default: 5.
func VersionCheckMinPercent(v int) VersionCheckOption {
	return func(rb RequestBuilder) { rb.Option("min-percent", v) }
}

// VersionCheck checks Kubo version against connected peers..
func (a *HttpApi) VersionCheck(ctx context.Context, opts ...VersionCheckOption) (*VersionCheckResponse, error) {
	req := a.Request("version/check")
	for _, o := range opts {
		o(req)
	}
	var resp VersionCheckResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// VersionDeps shows information about dependencies used for build..
func (a *HttpApi) VersionDeps(ctx context.Context) (*VersionDepsResponse, error) {
	req := a.Request("version/deps")
	var resp VersionDepsResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
