// Code generated by tools/gen-rpc-client; DO NOT EDIT.

package rpc

import (
	"context"
)

type CidBase32Response struct {
	CidStr    string `json:"CidStr,omitempty"`
	Formatted string `json:"Formatted,omitempty"`
	ErrorMsg  string `json:"ErrorMsg,omitempty"`
}

type CidBasesItem struct {
	Code int    `json:"Code,omitempty"`
	Name string `json:"Name,omitempty"`
}

type CidCodecsItem struct {
	Code int    `json:"Code,omitempty"`
	Name string `json:"Name,omitempty"`
}

type CidFormatResponse struct {
	CidStr    string `json:"CidStr,omitempty"`
	Formatted string `json:"Formatted,omitempty"`
	ErrorMsg  string `json:"ErrorMsg,omitempty"`
}

type CidHashesItem struct {
	Code int    `json:"Code,omitempty"`
	Name string `json:"Name,omitempty"`
}

// CidBase32 convert CIDs to Base32 CID version 1..
func (a *HttpApi) CidBase32(ctx context.Context, cid ...string) (*CidBase32Response, error) {
	req := a.Request("cid/base32").Arguments(cid...)
	var resp CidBase32Response
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// CidBasesOption configures the cid/bases command.
type CidBasesOption func(RequestBuilder)

// CidBasesPrefix sets the prefix option.
// also include the single letter prefixes in addition to the code.
func CidBasesPrefix(v bool) CidBasesOption {
	return func(rb RequestBuilder) { rb.Option("prefix", v) }
}

// CidBasesNumeric sets the numeric option.
// also include numeric codes.
func CidBasesNumeric(v bool) CidBasesOption {
	return func(rb RequestBuilder) { rb.Option("numeric", v) }
}

// CidBases list available multibase encodings..
func (a *HttpApi) CidBases(ctx context.Context, opts ...CidBasesOption) ([]CidBasesItem, error) {
	req := a.Request("cid/bases")
	for _, o := range opts {
		o(req)
	}
	var resp []CidBasesItem
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return resp, nil
}

// CidCodecsOption configures the cid/codecs command.
type CidCodecsOption func(RequestBuilder)

// CidCodecsNumeric sets the numeric option.
// also include numeric codes.
func CidCodecsNumeric(v bool) CidCodecsOption {
	return func(rb RequestBuilder) { rb.Option("numeric", v) }
}

// CidCodecsSupported sets the supported option.
// list only codecs supported by go-ipfs commands.
func CidCodecsSupported(v bool) CidCodecsOption {
	return func(rb RequestBuilder) { rb.Option("supported", v) }
}

// CidCodecs list available CID multicodecs..
func (a *HttpApi) CidCodecs(ctx context.Context, opts ...CidCodecsOption) ([]CidCodecsItem, error) {
	req := a.Request("cid/codecs")
	for _, o := range opts {
		o(req)
	}
	var resp []CidCodecsItem
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return resp, nil
}

// CidFormatOption configures the cid/format command.
type CidFormatOption func(RequestBuilder)

// CidFormatF sets the f option.
// Printf style format string. Default: %s.
func CidFormatF(v string) CidFormatOption {
	return func(rb RequestBuilder) { rb.Option("f", v) }
}

// CidFormatV sets the v option.
// CID version to convert to.
func CidFormatV(v string) CidFormatOption {
	return func(rb RequestBuilder) { rb.Option("v", v) }
}

// CidFormatMc sets the mc option.
// CID multicodec to convert to.
func CidFormatMc(v string) CidFormatOption {
	return func(rb RequestBuilder) { rb.Option("mc", v) }
}

// CidFormatB sets the b option.
// Multibase to display CID in.
func CidFormatB(v string) CidFormatOption {
	return func(rb RequestBuilder) { rb.Option("b", v) }
}

// CidFormat format and convert a CID in various useful ways..
func (a *HttpApi) CidFormat(ctx context.Context, cid []string, opts ...CidFormatOption) (*CidFormatResponse, error) {
	req := a.Request("cid/format").Arguments(cid...)
	for _, o := range opts {
		o(req)
	}
	var resp CidFormatResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// CidHashesOption configures the cid/hashes command.
type CidHashesOption func(RequestBuilder)

// CidHashesNumeric sets the numeric option.
// also include numeric codes.
func CidHashesNumeric(v bool) CidHashesOption {
	return func(rb RequestBuilder) { rb.Option("numeric", v) }
}

// CidHashesSupported sets the supported option.
// list only codecs supported by go-ipfs commands.
func CidHashesSupported(v bool) CidHashesOption {
	return func(rb RequestBuilder) { rb.Option("supported", v) }
}

// CidHashes list available multihashes..
func (a *HttpApi) CidHashes(ctx context.Context, opts ...CidHashesOption) ([]CidHashesItem, error) {
	req := a.Request("cid/hashes")
	for _, o := range opts {
		o(req)
	}
	var resp []CidHashesItem
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return resp, nil
}
