// Code generated by tools/gen-rpc-client; DO NOT EDIT.

package rpc

import (
	"context"
	"encoding/json"
	"io"
	"iter"
)

type AddResponse struct {
	Name       string `json:"Name,omitempty"`
	Hash       string `json:",omitempty"`
	Bytes      int64  `json:",omitempty"`
	Size       string `json:",omitempty"`
	Mode       string `json:",omitempty"`
	Mtime      int64  `json:",omitempty"`
	MtimeNsecs int    `json:",omitempty"`
}

// AddOption configures the add command.
type AddOption func(RequestBuilder)

// AddRecursive sets the recursive option.
// Add directory paths recursively.
func AddRecursive(v bool) AddOption {
	return func(rb RequestBuilder) { rb.Option("recursive", v) }
}

// AddDereferenceArgs sets the dereference-args option.
// DEPRECATED: use --dereference-symlinks instead. Only dereferences symlinks in CLI arguments, not inside directories.
func AddDereferenceArgs(v bool) AddOption {
	return func(rb RequestBuilder) { rb.Option("dereference-args", v) }
}

// AddStdinName sets the stdin-name option.
// Assign a name if the file source is stdin.
func AddStdinName(v string) AddOption {
	return func(rb RequestBuilder) { rb.Option("stdin-name", v) }
}

// AddHidden sets the hidden option.
// Include files that are hidden. Only takes effect on recursive add.
func AddHidden(v bool) AddOption {
	return func(rb RequestBuilder) { rb.Option("hidden", v) }
}

// AddIgnore sets the ignore option.
// A rule (.gitignore-stype) defining which file(s) should be ignored (variadic, experimental).
func AddIgnore(v []string) AddOption {
	return func(rb RequestBuilder) { rb.Option("ignore", v) }
}

// AddIgnoreRulesPath sets the ignore-rules-path option.
// A path to a file with .gitignore-style ignore rules (experimental).
func AddIgnoreRulesPath(v string) AddOption {
	return func(rb RequestBuilder) { rb.Option("ignore-rules-path", v) }
}

// AddEmptyDirs sets the empty-dirs option.
// Include empty directories in the import. Default: true.
func AddEmptyDirs(v bool) AddOption {
	return func(rb RequestBuilder) { rb.Option("empty-dirs", v) }
}

// AddDereferenceSymlinks sets the dereference-symlinks option.
// Recursively resolve all symlinks to their target content. Works on symlinks inside directories, not just CLI arguments.
func AddDereferenceSymlinks(v bool) AddOption {
	return func(rb RequestBuilder) { rb.Option("dereference-symlinks", v) }
}

// AddQuiet sets the quiet option.
// Write minimal output.
func AddQuiet(v bool) AddOption {
	return func(rb RequestBuilder) { rb.Option("quiet", v) }
}

// AddQuieter sets the quieter option.
// Write only final hash.
func AddQuieter(v bool) AddOption {
	return func(rb RequestBuilder) { rb.Option("quieter", v) }
}

// AddSilent sets the silent option.
// Write no output.
func AddSilent(v bool) AddOption {
	return func(rb RequestBuilder) { rb.Option("silent", v) }
}

// AddProgress sets the progress option.
// Stream progress data.
func AddProgress(v bool) AddOption {
	return func(rb RequestBuilder) { rb.Option("progress", v) }
}

// AddOnlyHash sets the only-hash option.
// Only chunk and hash - do not write to disk.
func AddOnlyHash(v bool) AddOption {
	return func(rb RequestBuilder) { rb.Option("only-hash", v) }
}

// AddWrapWithDirectory sets the wrap-with-directory option.
// Wrap files with a directory object.
func AddWrapWithDirectory(v bool) AddOption {
	return func(rb RequestBuilder) { rb.Option("wrap-with-directory", v) }
}

// AddPin sets the pin option.
// Pin locally to protect added files from garbage collection. Default: true.
func AddPin(v bool) AddOption {
	return func(rb RequestBuilder) { rb.Option("pin", v) }
}

// AddPinName sets the pin-name option.
// Name to use for the pin. Requires explicit value (e.g., --pin-name=myname).
func AddPinName(v string) AddOption {
	return func(rb RequestBuilder) { rb.Option("pin-name", v) }
}

// AddToFiles sets the to-files option.
// Add reference to Files API (MFS) at the provided path.
func AddToFiles(v string) AddOption {
	return func(rb RequestBuilder) { rb.Option("to-files", v) }
}

// AddCidVersion sets the cid-version option.
// CID version (0 or 1). CIDv1 automatically enables raw-leaves and is required for non-sha2-256 hashes. Default: Import.CidVersion.
func AddCidVersion(v int) AddOption {
	return func(rb RequestBuilder) { rb.Option("cid-version", v) }
}

// AddHash sets the hash option.
// Hash function to use. Implies CIDv1 if not sha2-256. Default: Import.HashFunction.
func AddHash(v string) AddOption {
	return func(rb RequestBuilder) { rb.Option("hash", v) }
}

// AddRawLeaves sets the raw-leaves option.
// Use raw blocks for leaf nodes. Note: CIDv1 automatically enables raw-leaves. Default: false for CIDv0, true for CIDv1 (Import.UnixFSRawLeaves).
func AddRawLeaves(v bool) AddOption {
	return func(rb RequestBuilder) { rb.Option("raw-leaves", v) }
}

// AddChunker sets the chunker option.
// Chunking algorithm, size-[bytes], rabin-[min]-[avg]-[max] or buzhash. Files larger than chunk size are split into multiple blocks. Default: Import.UnixFSChunker.
func AddChunker(v string) AddOption {
	return func(rb RequestBuilder) { rb.Option("chunker", v) }
}

// AddTrickle sets the trickle option.
// Use trickle-dag format for dag generation.
func AddTrickle(v bool) AddOption {
	return func(rb RequestBuilder) { rb.Option("trickle", v) }
}

// AddMaxFileLinks sets the max-file-links option.
// Limit the maximum number of links in UnixFS file nodes to this value. WARNING: experimental. Default: Import.UnixFSFileMaxLinks.
func AddMaxFileLinks(v int) AddOption {
	return func(rb RequestBuilder) { rb.Option("max-file-links", v) }
}

// AddMaxDirectoryLinks sets the max-directory-links option.
// Limit the maximum number of links in UnixFS basic directory nodes to this value. WARNING: experimental, Import.UnixFSHAMTDirectorySizeThreshold is safer. Default: Import.UnixFSDirectoryMaxLinks.
func AddMaxDirectoryLinks(v int) AddOption {
	return func(rb RequestBuilder) { rb.Option("max-directory-links", v) }
}

// AddMaxHamtFanout sets the max-hamt-fanout option.
// Limit the maximum number of links of a UnixFS HAMT directory node to this (power of 2, multiple of 8). WARNING: experimental, Import.UnixFSHAMTDirectorySizeThreshold is safer. Default: Import.UnixFSHAMTDirectoryMaxFanout.
func AddMaxHamtFanout(v int) AddOption {
	return func(rb RequestBuilder) { rb.Option("max-hamt-fanout", v) }
}

// AddInline sets the inline option.
// Inline small blocks into CIDs. WARNING: experimental.
func AddInline(v bool) AddOption {
	return func(rb RequestBuilder) { rb.Option("inline", v) }
}

// AddInlineLimit sets the inline-limit option.
// Maximum block size to inline. Maximum: 128 bytes. WARNING: experimental. Default: 32.
func AddInlineLimit(v int) AddOption {
	return func(rb RequestBuilder) { rb.Option("inline-limit", v) }
}

// AddNocopy sets the nocopy option.
// Add the file using filestore. Implies raw-leaves. WARNING: experimental.
func AddNocopy(v bool) AddOption {
	return func(rb RequestBuilder) { rb.Option("nocopy", v) }
}

// AddFscache sets the fscache option.
// Check the filestore for pre-existing blocks. WARNING: experimental.
func AddFscache(v bool) AddOption {
	return func(rb RequestBuilder) { rb.Option("fscache", v) }
}

// AddPreserveMode sets the preserve-mode option.
// Apply existing POSIX permissions to created UnixFS entries. WARNING: experimental, forces dag-pb for root block, disables raw-leaves.
func AddPreserveMode(v bool) AddOption {
	return func(rb RequestBuilder) { rb.Option("preserve-mode", v) }
}

// AddPreserveMtime sets the preserve-mtime option.
// Apply existing POSIX modification time to created UnixFS entries. WARNING: experimental, forces dag-pb for root block, disables raw-leaves.
func AddPreserveMtime(v bool) AddOption {
	return func(rb RequestBuilder) { rb.Option("preserve-mtime", v) }
}

// AddMode sets the mode option.
// Custom POSIX file mode to store in created UnixFS entries. WARNING: experimental, forces dag-pb for root block, disables raw-leaves.
func AddMode(v uint) AddOption {
	return func(rb RequestBuilder) { rb.Option("mode", v) }
}

// AddMtime sets the mtime option.
// Custom POSIX modification time to store in created UnixFS entries (seconds before or after the Unix Epoch). WARNING: experimental, forces dag-pb for root block, disables raw-leaves.
func AddMtime(v int64) AddOption {
	return func(rb RequestBuilder) { rb.Option("mtime", v) }
}

// AddMtimeNsecs sets the mtime-nsecs option.
// Custom POSIX modification time (optional time fraction in nanoseconds).
func AddMtimeNsecs(v uint) AddOption {
	return func(rb RequestBuilder) { rb.Option("mtime-nsecs", v) }
}

// AddFastProvideRoot sets the fast-provide-root option.
// Immediately provide root CID to DHT in addition to regular queue, for faster discovery. Default: Import.FastProvideRoot.
func AddFastProvideRoot(v bool) AddOption {
	return func(rb RequestBuilder) { rb.Option("fast-provide-root", v) }
}

// AddFastProvideWait sets the fast-provide-wait option.
// Block until the immediate provide completes before returning. Default: Import.FastProvideWait.
func AddFastProvideWait(v bool) AddOption {
	return func(rb RequestBuilder) { rb.Option("fast-provide-wait", v) }
}

// Add add a file or directory to IPFS..
func (a *HttpApi) Add(ctx context.Context, path io.Reader, opts ...AddOption) iter.Seq2[AddResponse, error] {
	return func(yield func(AddResponse, error) bool) {
		req := a.Request("add")
		req = req.FileBody(path).(RequestBuilder)
		for _, o := range opts {
			o(req)
		}
		resp, err := req.Send(ctx)
		if err != nil {
			yield(AddResponse{}, err)
			return
		}
		defer resp.Close()
		if resp.Error != nil {
			yield(AddResponse{}, resp.Error)
			return
		}
		dec := json.NewDecoder(resp.Output)
		for dec.More() {
			var item AddResponse
			if err := dec.Decode(&item); err != nil {
				yield(AddResponse{}, err)
				return
			}
			if !yield(item, nil) {
				return
			}
		}
	}
}
