// Code generated by tools/gen-rpc-client; DO NOT EDIT.

package rpc

import (
	"context"
)

type BitswapLedgerResponse struct {
	Peer      string  `json:"Peer,omitempty"`
	Value     float64 `json:"Value,omitempty"`
	Sent      uint64  `json:"Sent,omitempty"`
	Recv      uint64  `json:"Recv,omitempty"`
	Exchanged uint64  `json:"Exchanged,omitempty"`
}

type BitswapStatResponse struct {
	Wantlist         []string `json:"Wantlist,omitempty"`
	Peers            []string `json:"Peers,omitempty"`
	BlocksReceived   uint64   `json:"BlocksReceived,omitempty"`
	DataReceived     uint64   `json:"DataReceived,omitempty"`
	DupBlksReceived  uint64   `json:"DupBlksReceived,omitempty"`
	DupDataReceived  uint64   `json:"DupDataReceived,omitempty"`
	MessagesReceived uint64   `json:"MessagesReceived,omitempty"`
	BlocksSent       uint64   `json:"BlocksSent,omitempty"`
	DataSent         uint64   `json:"DataSent,omitempty"`
}

type BitswapWantlistResponse struct {
	Keys []string `json:"Keys,omitempty"`
}

// BitswapLedger show the current ledger for a peer..
func (a *HttpApi) BitswapLedger(ctx context.Context, peer string) (*BitswapLedgerResponse, error) {
	req := a.Request("bitswap/ledger", peer)
	var resp BitswapLedgerResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// Deprecated: BitswapReprovide may be removed in a future release.
// BitswapReprovide deprecated command to announce to bitswap. Use 'ipfs routing reprovide' instead..
func (a *HttpApi) BitswapReprovide(ctx context.Context) (*Response, error) {
	req := a.Request("bitswap/reprovide")
	resp, err := req.Send(ctx)
	if err != nil {
		return nil, err
	}
	if resp.Error != nil {
		resp.Close()
		return nil, resp.Error
	}
	return resp, nil
}

// BitswapStatOption configures the bitswap/stat command.
type BitswapStatOption func(RequestBuilder)

// BitswapStatVerbose sets the verbose option.
// Print extra information.
func BitswapStatVerbose(v bool) BitswapStatOption {
	return func(rb RequestBuilder) { rb.Option("verbose", v) }
}

// BitswapStatHuman sets the human option.
// Print sizes in human readable format (e.g., 1K 234M 2G).
func BitswapStatHuman(v bool) BitswapStatOption {
	return func(rb RequestBuilder) { rb.Option("human", v) }
}

// BitswapStat show some diagnostic information on the bitswap agent..
func (a *HttpApi) BitswapStat(ctx context.Context, opts ...BitswapStatOption) (*BitswapStatResponse, error) {
	req := a.Request("bitswap/stat")
	for _, o := range opts {
		o(req)
	}
	var resp BitswapStatResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// BitswapWantlistOption configures the bitswap/wantlist command.
type BitswapWantlistOption func(RequestBuilder)

// BitswapWantlistPeer sets the peer option.
// Specify which peer to show wantlist for. Default: self.
func BitswapWantlistPeer(v string) BitswapWantlistOption {
	return func(rb RequestBuilder) { rb.Option("peer", v) }
}

// BitswapWantlist show blocks currently on the wantlist..
func (a *HttpApi) BitswapWantlist(ctx context.Context, opts ...BitswapWantlistOption) (*BitswapWantlistResponse, error) {
	req := a.Request("bitswap/wantlist")
	for _, o := range opts {
		o(req)
	}
	var resp BitswapWantlistResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
