// Code generated by tools/gen-rpc-client; DO NOT EDIT.

package rpc

import (
	"context"
	"encoding/json"
	"iter"
)

type RepoGcResponse struct {
	Key   string `json:"Key,omitempty"`
	Error string `json:",omitempty"`
}

type RepoLsResponse struct {
	Ref string `json:"Ref,omitempty"`
	Err string `json:"Err,omitempty"`
}

type RepoStatResponse struct {
	RepoSize   uint64 `json:"RepoSize,omitempty"`
	StorageMax uint64 `json:"StorageMax,omitempty"`
	NumObjects uint64 `json:"NumObjects,omitempty"`
	RepoPath   string `json:"RepoPath,omitempty"`
	Version    string `json:"Version,omitempty"`
}

type RepoVerifyResponse struct {
	Msg      string `json:"Msg,omitempty"`
	Progress int    `json:"Progress,omitempty"`
}

type RepoVersionResponse struct {
	Version string `json:"Version,omitempty"`
}

// RepoGcOption configures the repo/gc command.
type RepoGcOption func(RequestBuilder)

// RepoGcStreamErrors sets the stream-errors option.
// Stream errors.
func RepoGcStreamErrors(v bool) RepoGcOption {
	return func(rb RequestBuilder) { rb.Option("stream-errors", v) }
}

// RepoGcQuiet sets the quiet option.
// Write minimal output.
func RepoGcQuiet(v bool) RepoGcOption {
	return func(rb RequestBuilder) { rb.Option("quiet", v) }
}

// RepoGcSilent sets the silent option.
// Write no output.
func RepoGcSilent(v bool) RepoGcOption {
	return func(rb RequestBuilder) { rb.Option("silent", v) }
}

// RepoGc perform a garbage collection sweep on the repo..
func (a *HttpApi) RepoGc(ctx context.Context, opts ...RepoGcOption) iter.Seq2[RepoGcResponse, error] {
	return func(yield func(RepoGcResponse, error) bool) {
		req := a.Request("repo/gc")
		for _, o := range opts {
			o(req)
		}
		resp, err := req.Send(ctx)
		if err != nil {
			yield(RepoGcResponse{}, err)
			return
		}
		defer resp.Close()
		if resp.Error != nil {
			yield(RepoGcResponse{}, resp.Error)
			return
		}
		dec := json.NewDecoder(resp.Output)
		for dec.More() {
			var item RepoGcResponse
			if err := dec.Decode(&item); err != nil {
				yield(RepoGcResponse{}, err)
				return
			}
			if !yield(item, nil) {
				return
			}
		}
	}
}

// RepoLs list all local references..
func (a *HttpApi) RepoLs(ctx context.Context) iter.Seq2[RepoLsResponse, error] {
	return func(yield func(RepoLsResponse, error) bool) {
		req := a.Request("repo/ls")
		resp, err := req.Send(ctx)
		if err != nil {
			yield(RepoLsResponse{}, err)
			return
		}
		defer resp.Close()
		if resp.Error != nil {
			yield(RepoLsResponse{}, resp.Error)
			return
		}
		dec := json.NewDecoder(resp.Output)
		for dec.More() {
			var item RepoLsResponse
			if err := dec.Decode(&item); err != nil {
				yield(RepoLsResponse{}, err)
				return
			}
			if !yield(item, nil) {
				return
			}
		}
	}
}

// RepoStatOption configures the repo/stat command.
type RepoStatOption func(RequestBuilder)

// RepoStatSizeOnly sets the size-only option.
// Only report RepoSize and StorageMax.
func RepoStatSizeOnly(v bool) RepoStatOption {
	return func(rb RequestBuilder) { rb.Option("size-only", v) }
}

// RepoStatHuman sets the human option.
// Print sizes in human readable format (e.g., 1K 234M 2G).
func RepoStatHuman(v bool) RepoStatOption {
	return func(rb RequestBuilder) { rb.Option("human", v) }
}

// RepoStat get stats for the currently used repo..
func (a *HttpApi) RepoStat(ctx context.Context, opts ...RepoStatOption) (*RepoStatResponse, error) {
	req := a.Request("repo/stat")
	for _, o := range opts {
		o(req)
	}
	var resp RepoStatResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// RepoVerifyOption configures the repo/verify command.
type RepoVerifyOption func(RequestBuilder)

// RepoVerifyDrop sets the drop option.
// Remove corrupt blocks from datastore (destructive operation).
func RepoVerifyDrop(v bool) RepoVerifyOption {
	return func(rb RequestBuilder) { rb.Option("drop", v) }
}

// RepoVerifyHeal sets the heal option.
// Remove corrupt blocks and re-fetch from network (destructive operation, implies --drop).
func RepoVerifyHeal(v bool) RepoVerifyOption {
	return func(rb RequestBuilder) { rb.Option("heal", v) }
}

// RepoVerifyHealTimeout sets the heal-timeout option.
// Maximum time to wait for each block heal (e.g., "30s"). Only applies with --heal. Default: 30s.
func RepoVerifyHealTimeout(v string) RepoVerifyOption {
	return func(rb RequestBuilder) { rb.Option("heal-timeout", v) }
}

// RepoVerify verify all blocks in repo are not corrupted..
func (a *HttpApi) RepoVerify(ctx context.Context, opts ...RepoVerifyOption) iter.Seq2[RepoVerifyResponse, error] {
	return func(yield func(RepoVerifyResponse, error) bool) {
		req := a.Request("repo/verify")
		for _, o := range opts {
			o(req)
		}
		resp, err := req.Send(ctx)
		if err != nil {
			yield(RepoVerifyResponse{}, err)
			return
		}
		defer resp.Close()
		if resp.Error != nil {
			yield(RepoVerifyResponse{}, resp.Error)
			return
		}
		dec := json.NewDecoder(resp.Output)
		for dec.More() {
			var item RepoVerifyResponse
			if err := dec.Decode(&item); err != nil {
				yield(RepoVerifyResponse{}, err)
				return
			}
			if !yield(item, nil) {
				return
			}
		}
	}
}

// RepoVersionOption configures the repo/version command.
type RepoVersionOption func(RequestBuilder)

// RepoVersionQuiet sets the quiet option.
// Write minimal output.
func RepoVersionQuiet(v bool) RepoVersionOption {
	return func(rb RequestBuilder) { rb.Option("quiet", v) }
}

// RepoVersion show the repo version..
func (a *HttpApi) RepoVersion(ctx context.Context, opts ...RepoVersionOption) (*RepoVersionResponse, error) {
	req := a.Request("repo/version")
	for _, o := range opts {
		o(req)
	}
	var resp RepoVersionResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
