// Code generated by tools/gen-rpc-client; DO NOT EDIT.

package rpc

import (
	"context"
	"encoding/json"
	"io"
	"iter"
)

type RoutingFindpeerResponse struct {
	ID        string                              `json:"ID,omitempty"`
	Type      int                                 `json:"Type,omitempty"`
	Responses []*RoutingFindpeerResponseResponses `json:"Responses,omitempty"`
	Extra     string                              `json:"Extra,omitempty"`
}

type RoutingFindpeerResponseResponses struct {
	ID    string   `json:"ID,omitempty"`
	Addrs []string `json:"Addrs,omitempty"`
}

type RoutingFindprovsResponse struct {
	ID        string                               `json:"ID,omitempty"`
	Type      int                                  `json:"Type,omitempty"`
	Responses []*RoutingFindprovsResponseResponses `json:"Responses,omitempty"`
	Extra     string                               `json:"Extra,omitempty"`
}

type RoutingFindprovsResponseResponses struct {
	ID    string   `json:"ID,omitempty"`
	Addrs []string `json:"Addrs,omitempty"`
}

type RoutingGetResponse struct {
	ID        string                         `json:"ID,omitempty"`
	Type      int                            `json:"Type,omitempty"`
	Responses []*RoutingGetResponseResponses `json:"Responses,omitempty"`
	Extra     string                         `json:"Extra,omitempty"`
}

type RoutingGetResponseResponses struct {
	ID    string   `json:"ID,omitempty"`
	Addrs []string `json:"Addrs,omitempty"`
}

type RoutingProvideResponse struct {
	ID        string                             `json:"ID,omitempty"`
	Type      int                                `json:"Type,omitempty"`
	Responses []*RoutingProvideResponseResponses `json:"Responses,omitempty"`
	Extra     string                             `json:"Extra,omitempty"`
}

type RoutingProvideResponseResponses struct {
	ID    string   `json:"ID,omitempty"`
	Addrs []string `json:"Addrs,omitempty"`
}

type RoutingPutResponse struct {
	ID        string                         `json:"ID,omitempty"`
	Type      int                            `json:"Type,omitempty"`
	Responses []*RoutingPutResponseResponses `json:"Responses,omitempty"`
	Extra     string                         `json:"Extra,omitempty"`
}

type RoutingPutResponseResponses struct {
	ID    string   `json:"ID,omitempty"`
	Addrs []string `json:"Addrs,omitempty"`
}

// RoutingFindpeerOption configures the routing/findpeer command.
type RoutingFindpeerOption func(RequestBuilder)

// RoutingFindpeerVerbose sets the verbose option.
// Print extra information.
func RoutingFindpeerVerbose(v bool) RoutingFindpeerOption {
	return func(rb RequestBuilder) { rb.Option("verbose", v) }
}

// RoutingFindpeer find the multiaddresses associated with a Peer ID..
func (a *HttpApi) RoutingFindpeer(ctx context.Context, peerID []string, opts ...RoutingFindpeerOption) iter.Seq2[RoutingFindpeerResponse, error] {
	return func(yield func(RoutingFindpeerResponse, error) bool) {
		req := a.Request("routing/findpeer").Arguments(peerID...)
		for _, o := range opts {
			o(req)
		}
		resp, err := req.Send(ctx)
		if err != nil {
			yield(RoutingFindpeerResponse{}, err)
			return
		}
		defer resp.Close()
		if resp.Error != nil {
			yield(RoutingFindpeerResponse{}, resp.Error)
			return
		}
		dec := json.NewDecoder(resp.Output)
		for dec.More() {
			var item RoutingFindpeerResponse
			if err := dec.Decode(&item); err != nil {
				yield(RoutingFindpeerResponse{}, err)
				return
			}
			if !yield(item, nil) {
				return
			}
		}
	}
}

// RoutingFindprovsOption configures the routing/findprovs command.
type RoutingFindprovsOption func(RequestBuilder)

// RoutingFindprovsVerbose sets the verbose option.
// Print extra information.
func RoutingFindprovsVerbose(v bool) RoutingFindprovsOption {
	return func(rb RequestBuilder) { rb.Option("verbose", v) }
}

// RoutingFindprovsNumProviders sets the num-providers option.
// The number of providers to find. Default: 20.
func RoutingFindprovsNumProviders(v int) RoutingFindprovsOption {
	return func(rb RequestBuilder) { rb.Option("num-providers", v) }
}

// RoutingFindprovs find peers that can provide a specific value, given a key..
func (a *HttpApi) RoutingFindprovs(ctx context.Context, key []string, opts ...RoutingFindprovsOption) iter.Seq2[RoutingFindprovsResponse, error] {
	return func(yield func(RoutingFindprovsResponse, error) bool) {
		req := a.Request("routing/findprovs").Arguments(key...)
		for _, o := range opts {
			o(req)
		}
		resp, err := req.Send(ctx)
		if err != nil {
			yield(RoutingFindprovsResponse{}, err)
			return
		}
		defer resp.Close()
		if resp.Error != nil {
			yield(RoutingFindprovsResponse{}, resp.Error)
			return
		}
		dec := json.NewDecoder(resp.Output)
		for dec.More() {
			var item RoutingFindprovsResponse
			if err := dec.Decode(&item); err != nil {
				yield(RoutingFindprovsResponse{}, err)
				return
			}
			if !yield(item, nil) {
				return
			}
		}
	}
}

// Experimental: RoutingGet is not yet stable.
// RoutingGet given a key, query the routing system for its best value..
func (a *HttpApi) RoutingGet(ctx context.Context, key ...string) (*RoutingGetResponse, error) {
	req := a.Request("routing/get").Arguments(key...)
	var resp RoutingGetResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// RoutingProvideOption configures the routing/provide command.
type RoutingProvideOption func(RequestBuilder)

// RoutingProvideVerbose sets the verbose option.
// Print extra information.
func RoutingProvideVerbose(v bool) RoutingProvideOption {
	return func(rb RequestBuilder) { rb.Option("verbose", v) }
}

// RoutingProvideRecursive sets the recursive option.
// Recursively provide entire graph.
func RoutingProvideRecursive(v bool) RoutingProvideOption {
	return func(rb RequestBuilder) { rb.Option("recursive", v) }
}

// Experimental: RoutingProvide is not yet stable.
// RoutingProvide announce to the network that you are providing given values..
func (a *HttpApi) RoutingProvide(ctx context.Context, key []string, opts ...RoutingProvideOption) iter.Seq2[RoutingProvideResponse, error] {
	return func(yield func(RoutingProvideResponse, error) bool) {
		req := a.Request("routing/provide").Arguments(key...)
		for _, o := range opts {
			o(req)
		}
		resp, err := req.Send(ctx)
		if err != nil {
			yield(RoutingProvideResponse{}, err)
			return
		}
		defer resp.Close()
		if resp.Error != nil {
			yield(RoutingProvideResponse{}, resp.Error)
			return
		}
		dec := json.NewDecoder(resp.Output)
		for dec.More() {
			var item RoutingProvideResponse
			if err := dec.Decode(&item); err != nil {
				yield(RoutingProvideResponse{}, err)
				return
			}
			if !yield(item, nil) {
				return
			}
		}
	}
}

// RoutingPutOption configures the routing/put command.
type RoutingPutOption func(RequestBuilder)

// RoutingPutAllowOffline sets the allow-offline option.
// When offline, save the IPNS record to the local datastore without broadcasting to the network instead of simply failing.
func RoutingPutAllowOffline(v bool) RoutingPutOption {
	return func(rb RequestBuilder) { rb.Option("allow-offline", v) }
}

// Experimental: RoutingPut is not yet stable.
// RoutingPut write a key/value pair to the routing system..
func (a *HttpApi) RoutingPut(ctx context.Context, key string, value_file io.Reader, opts ...RoutingPutOption) (*RoutingPutResponse, error) {
	req := a.Request("routing/put", key)
	req = req.FileBody(value_file).(RequestBuilder)
	for _, o := range opts {
		o(req)
	}
	var resp RoutingPutResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// Experimental: RoutingReprovide is not yet stable.
// RoutingReprovide trigger reprovider..
func (a *HttpApi) RoutingReprovide(ctx context.Context) (*Response, error) {
	req := a.Request("routing/reprovide")
	resp, err := req.Send(ctx)
	if err != nil {
		return nil, err
	}
	if resp.Error != nil {
		resp.Close()
		return nil, resp.Error
	}
	return resp, nil
}
