// Code generated by tools/gen-rpc-client; DO NOT EDIT.

package rpc

import (
	"context"
	"io"
)

type FilesFlushResponse struct {
	Cid string `json:"Cid,omitempty"`
}

type FilesLsResponse struct {
	Entries []FilesLsResponseEntries `json:"Entries,omitempty"`
}

type FilesLsResponseEntries struct {
	Name string `json:"Name,omitempty"`
	Type int    `json:"Type,omitempty"`
	Size int64  `json:"Size,omitempty"`
	Hash string `json:"Hash,omitempty"`
}

type FilesStatResponse struct {
	Hash           string `json:"Hash,omitempty"`
	Size           uint64 `json:"Size,omitempty"`
	CumulativeSize uint64 `json:"CumulativeSize,omitempty"`
	Blocks         int    `json:"Blocks,omitempty"`
	Type           string `json:"Type,omitempty"`
	WithLocality   bool   `json:",omitempty"`
	Local          bool   `json:",omitempty"`
	SizeLocal      uint64 `json:",omitempty"`
	Mode           uint32 `json:",omitempty"`
	Mtime          int64  `json:",omitempty"`
	MtimeNsecs     int    `json:",omitempty"`
}

// FilesChcidOption configures the files/chcid command.
type FilesChcidOption func(RequestBuilder)

// FilesChcidCidVersion sets the cid-version option.
// Cid version to use. (experimental).
func FilesChcidCidVersion(v int) FilesChcidOption {
	return func(rb RequestBuilder) { rb.Option("cid-version", v) }
}

// FilesChcidHash sets the hash option.
// Hash function to use. Will set Cid version to 1 if used. (experimental).
func FilesChcidHash(v string) FilesChcidOption {
	return func(rb RequestBuilder) { rb.Option("hash", v) }
}

// FilesChcid change the CID version or hash function of the root node of a given path..
func (a *HttpApi) FilesChcid(ctx context.Context, path string, opts ...FilesChcidOption) (*Response, error) {
	req := a.Request("files/chcid", path)
	for _, o := range opts {
		o(req)
	}
	resp, err := req.Send(ctx)
	if err != nil {
		return nil, err
	}
	if resp.Error != nil {
		resp.Close()
		return nil, resp.Error
	}
	return resp, nil
}

// Experimental: FilesChmod is not yet stable.
// FilesChmod change optional POSIX mode permissions.
func (a *HttpApi) FilesChmod(ctx context.Context, mode string, path string) (*Response, error) {
	req := a.Request("files/chmod", mode, path)
	resp, err := req.Send(ctx)
	if err != nil {
		return nil, err
	}
	if resp.Error != nil {
		resp.Close()
		return nil, resp.Error
	}
	return resp, nil
}

// FilesCpOption configures the files/cp command.
type FilesCpOption func(RequestBuilder)

// FilesCpForce sets the force option.
// Force overwrite of existing files.
func FilesCpForce(v bool) FilesCpOption {
	return func(rb RequestBuilder) { rb.Option("force", v) }
}

// FilesCpParents sets the parents option.
// Make parent directories as needed.
func FilesCpParents(v bool) FilesCpOption {
	return func(rb RequestBuilder) { rb.Option("parents", v) }
}

// FilesCp add references to IPFS files and directories in MFS (or copy within MFS)..
func (a *HttpApi) FilesCp(ctx context.Context, source string, dest string, opts ...FilesCpOption) (*Response, error) {
	req := a.Request("files/cp", source, dest)
	for _, o := range opts {
		o(req)
	}
	resp, err := req.Send(ctx)
	if err != nil {
		return nil, err
	}
	if resp.Error != nil {
		resp.Close()
		return nil, resp.Error
	}
	return resp, nil
}

// FilesFlush flush a given path's data to disk..
func (a *HttpApi) FilesFlush(ctx context.Context, path string) (*FilesFlushResponse, error) {
	req := a.Request("files/flush", path)
	var resp FilesFlushResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// FilesLsOption configures the files/ls command.
type FilesLsOption func(RequestBuilder)

// FilesLsLong sets the long option.
// Use long listing format.
func FilesLsLong(v bool) FilesLsOption {
	return func(rb RequestBuilder) { rb.Option("long", v) }
}

// FilesLsU sets the U option.
// Do not sort; list entries in directory order.
func FilesLsU(v bool) FilesLsOption {
	return func(rb RequestBuilder) { rb.Option("U", v) }
}

// FilesLs list directories in the local mutable namespace..
func (a *HttpApi) FilesLs(ctx context.Context, path string, opts ...FilesLsOption) (*FilesLsResponse, error) {
	req := a.Request("files/ls", path)
	for _, o := range opts {
		o(req)
	}
	var resp FilesLsResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// FilesMkdirOption configures the files/mkdir command.
type FilesMkdirOption func(RequestBuilder)

// FilesMkdirParents sets the parents option.
// No error if existing, make parent directories as needed.
func FilesMkdirParents(v bool) FilesMkdirOption {
	return func(rb RequestBuilder) { rb.Option("parents", v) }
}

// FilesMkdirCidVersion sets the cid-version option.
// Cid version to use. (experimental).
func FilesMkdirCidVersion(v int) FilesMkdirOption {
	return func(rb RequestBuilder) { rb.Option("cid-version", v) }
}

// FilesMkdirHash sets the hash option.
// Hash function to use. Will set Cid version to 1 if used. (experimental).
func FilesMkdirHash(v string) FilesMkdirOption {
	return func(rb RequestBuilder) { rb.Option("hash", v) }
}

// FilesMkdir make directories..
func (a *HttpApi) FilesMkdir(ctx context.Context, path string, opts ...FilesMkdirOption) (*Response, error) {
	req := a.Request("files/mkdir", path)
	for _, o := range opts {
		o(req)
	}
	resp, err := req.Send(ctx)
	if err != nil {
		return nil, err
	}
	if resp.Error != nil {
		resp.Close()
		return nil, resp.Error
	}
	return resp, nil
}

// FilesMv move files..
func (a *HttpApi) FilesMv(ctx context.Context, source string, dest string) (*Response, error) {
	req := a.Request("files/mv", source, dest)
	resp, err := req.Send(ctx)
	if err != nil {
		return nil, err
	}
	if resp.Error != nil {
		resp.Close()
		return nil, resp.Error
	}
	return resp, nil
}

// FilesReadOption configures the files/read command.
type FilesReadOption func(RequestBuilder)

// FilesReadOffset sets the offset option.
// Byte offset to begin reading from.
func FilesReadOffset(v int64) FilesReadOption {
	return func(rb RequestBuilder) { rb.Option("offset", v) }
}

// FilesReadCount sets the count option.
// Maximum number of bytes to read.
func FilesReadCount(v int64) FilesReadOption {
	return func(rb RequestBuilder) { rb.Option("count", v) }
}

// FilesRead read a file from MFS..
func (a *HttpApi) FilesRead(ctx context.Context, path string, opts ...FilesReadOption) (*Response, error) {
	req := a.Request("files/read", path)
	for _, o := range opts {
		o(req)
	}
	resp, err := req.Send(ctx)
	if err != nil {
		return nil, err
	}
	if resp.Error != nil {
		resp.Close()
		return nil, resp.Error
	}
	return resp, nil
}

// FilesRmOption configures the files/rm command.
type FilesRmOption func(RequestBuilder)

// FilesRmRecursive sets the recursive option.
// Recursively remove directories.
func FilesRmRecursive(v bool) FilesRmOption {
	return func(rb RequestBuilder) { rb.Option("recursive", v) }
}

// FilesRmForce sets the force option.
// Forcibly remove target at path; implies -r for directories.
func FilesRmForce(v bool) FilesRmOption {
	return func(rb RequestBuilder) { rb.Option("force", v) }
}

// FilesRm remove a file from MFS..
func (a *HttpApi) FilesRm(ctx context.Context, path []string, opts ...FilesRmOption) (*Response, error) {
	req := a.Request("files/rm").Arguments(path...)
	for _, o := range opts {
		o(req)
	}
	resp, err := req.Send(ctx)
	if err != nil {
		return nil, err
	}
	if resp.Error != nil {
		resp.Close()
		return nil, resp.Error
	}
	return resp, nil
}

// FilesStatOption configures the files/stat command.
type FilesStatOption func(RequestBuilder)

// FilesStatFormat sets the format option.
// Print statistics in given format. Allowed tokens: <hash> <size> <cumulsize> <type> <childs> and optional <mode> <mode-octal> <mtime> <mtime-secs> <mtime-nsecs>.Conflicts with other format options. Default: <hash> Size: <size> CumulativeSize: <cumulsize> ChildBlocks: <childs> Type: <type> Mode: <mode> (<mode-octal>) Mtime: <mtime>.
func FilesStatFormat(v string) FilesStatOption {
	return func(rb RequestBuilder) { rb.Option("format", v) }
}

// FilesStatHash sets the hash option.
// Print only hash. Implies '--format=<hash>'. Conflicts with other format options.
func FilesStatHash(v bool) FilesStatOption {
	return func(rb RequestBuilder) { rb.Option("hash", v) }
}

// FilesStatSize sets the size option.
// Print only size. Implies '--format=<cumulsize>'. Conflicts with other format options.
func FilesStatSize(v bool) FilesStatOption {
	return func(rb RequestBuilder) { rb.Option("size", v) }
}

// FilesStatWithLocal sets the with-local option.
// Compute the amount of the dag that is local, and if possible the total size.
func FilesStatWithLocal(v bool) FilesStatOption {
	return func(rb RequestBuilder) { rb.Option("with-local", v) }
}

// FilesStat display file status..
func (a *HttpApi) FilesStat(ctx context.Context, path string, opts ...FilesStatOption) (*FilesStatResponse, error) {
	req := a.Request("files/stat", path)
	for _, o := range opts {
		o(req)
	}
	var resp FilesStatResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// FilesTouchOption configures the files/touch command.
type FilesTouchOption func(RequestBuilder)

// FilesTouchMtime sets the mtime option.
// Modification time in seconds before or since the Unix Epoch to apply to created UnixFS entries.
func FilesTouchMtime(v int64) FilesTouchOption {
	return func(rb RequestBuilder) { rb.Option("mtime", v) }
}

// FilesTouchMtimeNsecs sets the mtime-nsecs option.
// Modification time fraction in nanoseconds.
func FilesTouchMtimeNsecs(v uint) FilesTouchOption {
	return func(rb RequestBuilder) { rb.Option("mtime-nsecs", v) }
}

// Experimental: FilesTouch is not yet stable.
// FilesTouch set or change optional POSIX modification times..
func (a *HttpApi) FilesTouch(ctx context.Context, path string, opts ...FilesTouchOption) (*Response, error) {
	req := a.Request("files/touch", path)
	for _, o := range opts {
		o(req)
	}
	resp, err := req.Send(ctx)
	if err != nil {
		return nil, err
	}
	if resp.Error != nil {
		resp.Close()
		return nil, resp.Error
	}
	return resp, nil
}

// FilesWriteOption configures the files/write command.
type FilesWriteOption func(RequestBuilder)

// FilesWriteOffset sets the offset option.
// Byte offset to begin writing at.
func FilesWriteOffset(v int64) FilesWriteOption {
	return func(rb RequestBuilder) { rb.Option("offset", v) }
}

// FilesWriteCreate sets the create option.
// Create the file if it does not exist.
func FilesWriteCreate(v bool) FilesWriteOption {
	return func(rb RequestBuilder) { rb.Option("create", v) }
}

// FilesWriteParents sets the parents option.
// Make parent directories as needed.
func FilesWriteParents(v bool) FilesWriteOption {
	return func(rb RequestBuilder) { rb.Option("parents", v) }
}

// FilesWriteTruncate sets the truncate option.
// Truncate the file to size zero before writing.
func FilesWriteTruncate(v bool) FilesWriteOption {
	return func(rb RequestBuilder) { rb.Option("truncate", v) }
}

// FilesWriteCount sets the count option.
// Maximum number of bytes to read.
func FilesWriteCount(v int64) FilesWriteOption {
	return func(rb RequestBuilder) { rb.Option("count", v) }
}

// FilesWriteRawLeaves sets the raw-leaves option.
// Use raw blocks for newly created leaf nodes. (experimental).
func FilesWriteRawLeaves(v bool) FilesWriteOption {
	return func(rb RequestBuilder) { rb.Option("raw-leaves", v) }
}

// FilesWriteCidVersion sets the cid-version option.
// Cid version to use. (experimental).
func FilesWriteCidVersion(v int) FilesWriteOption {
	return func(rb RequestBuilder) { rb.Option("cid-version", v) }
}

// FilesWriteHash sets the hash option.
// Hash function to use. Will set Cid version to 1 if used. (experimental).
func FilesWriteHash(v string) FilesWriteOption {
	return func(rb RequestBuilder) { rb.Option("hash", v) }
}

// FilesWrite append to (modify) a file in MFS..
func (a *HttpApi) FilesWrite(ctx context.Context, path string, data io.Reader, opts ...FilesWriteOption) (*Response, error) {
	req := a.Request("files/write", path)
	req = req.FileBody(data).(RequestBuilder)
	for _, o := range opts {
		o(req)
	}
	resp, err := req.Send(ctx)
	if err != nil {
		return nil, err
	}
	if resp.Error != nil {
		resp.Close()
		return nil, resp.Error
	}
	return resp, nil
}
