// Code generated by tools/gen-rpc-client; DO NOT EDIT.

package rpc

import (
	"context"
	"encoding/json"
	"io"
	"iter"
)

type PubsubLsResponse struct {
	Strings []string `json:"Strings,omitempty"`
}

type PubsubPeersResponse struct {
	Strings []string `json:"Strings,omitempty"`
}

type PubsubResetResponse struct {
	Deleted int64 `json:"deleted"`
}

type PubsubSubResponse struct {
	From     string   `json:"from,omitempty"`
	Data     string   `json:"data,omitempty"`
	Seqno    string   `json:"seqno,omitempty"`
	TopicIDs []string `json:"topicIDs,omitempty"`
}

// Experimental: PubsubLs is not yet stable.
// PubsubLs list subscribed topics by name..
func (a *HttpApi) PubsubLs(ctx context.Context) (*PubsubLsResponse, error) {
	req := a.Request("pubsub/ls")
	var resp PubsubLsResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// Experimental: PubsubPeers is not yet stable.
// PubsubPeers list peers we are currently pubsubbing with..
func (a *HttpApi) PubsubPeers(ctx context.Context, topic string) (*PubsubPeersResponse, error) {
	req := a.Request("pubsub/peers", topic)
	var resp PubsubPeersResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// Experimental: PubsubPub is not yet stable.
// PubsubPub publish data to a given pubsub topic..
func (a *HttpApi) PubsubPub(ctx context.Context, topic string, data io.Reader) (*Response, error) {
	req := a.Request("pubsub/pub", topic)
	req = req.FileBody(data).(RequestBuilder)
	resp, err := req.Send(ctx)
	if err != nil {
		return nil, err
	}
	if resp.Error != nil {
		resp.Close()
		return nil, resp.Error
	}
	return resp, nil
}

// PubsubResetOption configures the pubsub/reset command.
type PubsubResetOption func(RequestBuilder)

// PubsubResetPeer sets the peer option.
// Only reset state for this peer ID.
func PubsubResetPeer(v string) PubsubResetOption {
	return func(rb RequestBuilder) { rb.Option("peer", v) }
}

// Experimental: PubsubReset is not yet stable.
// PubsubReset reset pubsub validator state..
func (a *HttpApi) PubsubReset(ctx context.Context, opts ...PubsubResetOption) (*PubsubResetResponse, error) {
	req := a.Request("pubsub/reset")
	for _, o := range opts {
		o(req)
	}
	var resp PubsubResetResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// Experimental: PubsubSub is not yet stable.
// PubsubSub subscribe to messages on a given topic..
func (a *HttpApi) PubsubSub(ctx context.Context, topic string) iter.Seq2[PubsubSubResponse, error] {
	return func(yield func(PubsubSubResponse, error) bool) {
		req := a.Request("pubsub/sub", topic)
		resp, err := req.Send(ctx)
		if err != nil {
			yield(PubsubSubResponse{}, err)
			return
		}
		defer resp.Close()
		if resp.Error != nil {
			yield(PubsubSubResponse{}, resp.Error)
			return
		}
		dec := json.NewDecoder(resp.Output)
		for dec.More() {
			var item PubsubSubResponse
			if err := dec.Decode(&item); err != nil {
				yield(PubsubSubResponse{}, err)
				return
			}
			if !yield(item, nil) {
				return
			}
		}
	}
}
