// Code generated by tools/gen-rpc-client; DO NOT EDIT.

package rpc

import (
	"context"
	"encoding/json"
	"io"
)

type ConfigProfileApplyResponse struct {
	OldCfg map[string]json.RawMessage `json:"OldCfg,omitempty"`
	NewCfg map[string]json.RawMessage `json:"NewCfg,omitempty"`
}

type ConfigResponse struct {
	Key   string          `json:"Key,omitempty"`
	Value json.RawMessage `json:"Value,omitempty"`
}

// ConfigOption configures the config command.
type ConfigOption func(RequestBuilder)

// ConfigBool sets the bool option.
// Set a boolean value.
func ConfigBool(v bool) ConfigOption {
	return func(rb RequestBuilder) { rb.Option("bool", v) }
}

// ConfigJson sets the json option.
// Parse stringified JSON.
func ConfigJson(v bool) ConfigOption {
	return func(rb RequestBuilder) { rb.Option("json", v) }
}

// ConfigExpandAuto sets the expand-auto option.
// Expand 'auto' placeholders to their expanded values from AutoConf service.
func ConfigExpandAuto(v bool) ConfigOption {
	return func(rb RequestBuilder) { rb.Option("expand-auto", v) }
}

// Config get and set IPFS config values..
func (a *HttpApi) Config(ctx context.Context, key string, value string, opts ...ConfigOption) (*ConfigResponse, error) {
	req := a.Request("config", key, value)
	for _, o := range opts {
		o(req)
	}
	var resp ConfigResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// ConfigProfileApplyOption configures the config/profile/apply command.
type ConfigProfileApplyOption func(RequestBuilder)

// ConfigProfileApplyDryRun sets the dry-run option.
// print difference between the current config and the config that would be generated.
func ConfigProfileApplyDryRun(v bool) ConfigProfileApplyOption {
	return func(rb RequestBuilder) { rb.Option("dry-run", v) }
}

// ConfigProfileApply apply profile to config..
func (a *HttpApi) ConfigProfileApply(ctx context.Context, profile string, opts ...ConfigProfileApplyOption) (*ConfigProfileApplyResponse, error) {
	req := a.Request("config/profile/apply", profile)
	for _, o := range opts {
		o(req)
	}
	var resp ConfigProfileApplyResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// ConfigReplace replace the config with <file>..
func (a *HttpApi) ConfigReplace(ctx context.Context, file io.Reader) (*Response, error) {
	req := a.Request("config/replace")
	req = req.FileBody(file).(RequestBuilder)
	resp, err := req.Send(ctx)
	if err != nil {
		return nil, err
	}
	if resp.Error != nil {
		resp.Close()
		return nil, resp.Error
	}
	return resp, nil
}

// ConfigShow output config file contents..
func (a *HttpApi) ConfigShow(ctx context.Context) (*Response, error) {
	req := a.Request("config/show")
	resp, err := req.Send(ctx)
	if err != nil {
		return nil, err
	}
	if resp.Error != nil {
		resp.Close()
		return nil, resp.Error
	}
	return resp, nil
}
