// Code generated by tools/gen-rpc-client; DO NOT EDIT.

package rpc

import (
	"context"
)

type ProvideStatResponse struct {
	Sweep  *ProvideStatResponseSweep  `json:"Sweep,omitempty"`
	Legacy *ProvideStatResponseLegacy `json:"Legacy,omitempty"`
	FullRT bool                       `json:"FullRT,omitempty"`
}

type ProvideStatResponseLegacy struct {
	TotalReprovides        uint64 `json:"TotalReprovides,omitempty"`
	LastReprovideBatchSize uint64 `json:"LastReprovideBatchSize,omitempty"`
	ReprovideInterval      string `json:"ReprovideInterval,omitempty"`
	AvgReprovideDuration   string `json:"AvgReprovideDuration,omitempty"`
	LastReprovideDuration  string `json:"LastReprovideDuration,omitempty"`
	LastRun                string `json:"LastRun,omitempty"`
}

type ProvideStatResponseSweep struct {
	Closed       bool                                 `json:"closed"`
	Connectivity ProvideStatResponseSweepConnectivity `json:"connectivity"`
	Queues       ProvideStatResponseSweepQueues       `json:"queues"`
	Schedule     ProvideStatResponseSweepSchedule     `json:"schedule"`
	Workers      ProvideStatResponseSweepWorkers      `json:"workers"`
	Timing       ProvideStatResponseSweepTiming       `json:"timing"`
	Operations   ProvideStatResponseSweepOperations   `json:"operations"`
	Network      ProvideStatResponseSweepNetwork      `json:"network"`
}

type ProvideStatResponseSweepConnectivity struct {
	Status string `json:"status"`
	Since  string `json:"since"`
}

type ProvideStatResponseSweepNetwork struct {
	Peers                    int     `json:"peers"`
	Reachable                int     `json:"reachable"`
	CompleteKeyspaceCoverage bool    `json:"complete_keyspace_coverage"`
	AvgRegionSize            float64 `json:"avg_region_size"`
	AvgHolders               float64 `json:"avg_holders"`
	ReplicationFactor        int     `json:"replication_factor"`
}

type ProvideStatResponseSweepOperations struct {
	Ongoing ProvideStatResponseSweepOperationsOngoing `json:"ongoing"`
	Past    ProvideStatResponseSweepOperationsPast    `json:"past"`
}

type ProvideStatResponseSweepOperationsOngoing struct {
	RegionProvides   int `json:"region_provides"`
	KeyProvides      int `json:"key_provides"`
	RegionReprovides int `json:"region_reprovides"`
	KeyReprovides    int `json:"key_reprovides"`
}

type ProvideStatResponseSweepOperationsPast struct {
	RecordsProvided           int64   `json:"records_provided"`
	KeysProvided              int64   `json:"keys_provided"`
	KeysFailed                int64   `json:"keys_failed"`
	KeysProvidedPerMinute     float64 `json:"keys_provided_per_minute"`
	KeysReprovidedPerMinute   float64 `json:"keys_reprovided_per_minute"`
	RegionReprovideDuration   string  `json:"reprovide_duration"`
	AvgKeysPerReprovide       float64 `json:"avg_keys_per_reprovide"`
	RegionReprovidedLastCycle int64   `json:"regions_reprovided_last_cycle"`
}

type ProvideStatResponseSweepQueues struct {
	PendingKeyProvides      int64 `json:"pending_key_provides"`
	PendingRegionProvides   int64 `json:"pending_region_provides"`
	PendingRegionReprovides int64 `json:"pending_region_reprovides"`
}

type ProvideStatResponseSweepSchedule struct {
	Keys                int64   `json:"keys"`
	Regions             int64   `json:"regions"`
	AvgPrefixLength     float64 `json:"avg_prefix_length"`
	NextReprovideAt     string  `json:"next_reprovide_at"`
	NextReprovidePrefix string  `json:"next_reprovide_prefix"`
}

type ProvideStatResponseSweepTiming struct {
	Uptime             string `json:"uptime"`
	ReprovidesInterval string `json:"reprovides_interval"`
	CycleStart         string `json:"cycle_start"`
	CurrentTimeOffset  string `json:"current_time_offset"`
	MaxReprovideDelay  string `json:"max_reprovide_delay"`
}

type ProvideStatResponseSweepWorkers struct {
	Max                      int `json:"max"`
	Active                   int `json:"active"`
	ActivePeriodic           int `json:"active_periodic"`
	ActiveBurst              int `json:"active_burst"`
	DedicatedPeriodic        int `json:"dedicated_periodic"`
	DedicatedBurst           int `json:"dedicated_burst"`
	QueuedPeriodic           int `json:"queued_periodic"`
	QueuedBurst              int `json:"queued_burst"`
	MaxProvideConnsPerWorker int `json:"max_provide_conns_per_worker"`
}

// ProvideClearOption configures the provide/clear command.
type ProvideClearOption func(RequestBuilder)

// ProvideClearQuiet sets the quiet option.
// Do not write output.
func ProvideClearQuiet(v bool) ProvideClearOption {
	return func(rb RequestBuilder) { rb.Option("quiet", v) }
}

// Experimental: ProvideClear is not yet stable.
// ProvideClear clear all CIDs from the provide queue..
func (a *HttpApi) ProvideClear(ctx context.Context, opts ...ProvideClearOption) (*Response, error) {
	req := a.Request("provide/clear")
	for _, o := range opts {
		o(req)
	}
	resp, err := req.Send(ctx)
	if err != nil {
		return nil, err
	}
	if resp.Error != nil {
		resp.Close()
		return nil, resp.Error
	}
	return resp, nil
}

// ProvideStatOption configures the provide/stat command.
type ProvideStatOption func(RequestBuilder)

// ProvideStatLan sets the lan option.
// Show stats for LAN DHT only (for Sweep+Dual DHT only).
func ProvideStatLan(v bool) ProvideStatOption {
	return func(rb RequestBuilder) { rb.Option("lan", v) }
}

// ProvideStatAll sets the all option.
// Display all provide sweep stats.
func ProvideStatAll(v bool) ProvideStatOption {
	return func(rb RequestBuilder) { rb.Option("all", v) }
}

// ProvideStatCompact sets the compact option.
// Display stats in 2-column layout (requires --all).
func ProvideStatCompact(v bool) ProvideStatOption {
	return func(rb RequestBuilder) { rb.Option("compact", v) }
}

// ProvideStatConnectivity sets the connectivity option.
// Display DHT connectivity status.
func ProvideStatConnectivity(v bool) ProvideStatOption {
	return func(rb RequestBuilder) { rb.Option("connectivity", v) }
}

// ProvideStatNetwork sets the network option.
// Display network stats (peers, reachability, region size).
func ProvideStatNetwork(v bool) ProvideStatOption {
	return func(rb RequestBuilder) { rb.Option("network", v) }
}

// ProvideStatSchedule sets the schedule option.
// Display reprovide schedule (CIDs/regions scheduled, next reprovide time).
func ProvideStatSchedule(v bool) ProvideStatOption {
	return func(rb RequestBuilder) { rb.Option("schedule", v) }
}

// ProvideStatTimings sets the timings option.
// Display timing information (uptime, cycle start, reprovide interval).
func ProvideStatTimings(v bool) ProvideStatOption {
	return func(rb RequestBuilder) { rb.Option("timings", v) }
}

// ProvideStatWorkers sets the workers option.
// Display worker pool stats (active/available/queued workers).
func ProvideStatWorkers(v bool) ProvideStatOption {
	return func(rb RequestBuilder) { rb.Option("workers", v) }
}

// ProvideStatOperations sets the operations option.
// Display operation stats (ongoing/past provides, rates, errors).
func ProvideStatOperations(v bool) ProvideStatOption {
	return func(rb RequestBuilder) { rb.Option("operations", v) }
}

// ProvideStatQueues sets the queues option.
// Display provide and reprovide queue sizes.
func ProvideStatQueues(v bool) ProvideStatOption {
	return func(rb RequestBuilder) { rb.Option("queues", v) }
}

// Experimental: ProvideStat is not yet stable.
// ProvideStat show statistics about the provider system.
func (a *HttpApi) ProvideStat(ctx context.Context, opts ...ProvideStatOption) (*ProvideStatResponse, error) {
	req := a.Request("provide/stat")
	for _, o := range opts {
		o(req)
	}
	var resp ProvideStatResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
