// Code generated by tools/gen-rpc-client; DO NOT EDIT.

package rpc

import (
	"context"
)

type P2pForwardResponse struct {
	Status   string `json:"Status,omitempty"`
	Protocol string `json:"Protocol,omitempty"`
	Address  string `json:"Address,omitempty"`
}

type P2pListenResponse struct {
	Status   string `json:"Status,omitempty"`
	Protocol string `json:"Protocol,omitempty"`
	Address  string `json:"Address,omitempty"`
}

type P2pLsResponse struct {
	Listeners []P2pLsResponseListeners `json:"Listeners,omitempty"`
}

type P2pLsResponseListeners struct {
	Protocol      string `json:"Protocol,omitempty"`
	ListenAddress string `json:"ListenAddress,omitempty"`
	TargetAddress string `json:"TargetAddress,omitempty"`
}

type P2pStreamLsResponse struct {
	Streams []P2pStreamLsResponseStreams `json:"Streams,omitempty"`
}

type P2pStreamLsResponseStreams struct {
	HandlerID     string `json:"HandlerID,omitempty"`
	Protocol      string `json:"Protocol,omitempty"`
	OriginAddress string `json:"OriginAddress,omitempty"`
	TargetAddress string `json:"TargetAddress,omitempty"`
}

// P2pCloseOption configures the p2p/close command.
type P2pCloseOption func(RequestBuilder)

// P2pCloseAll sets the all option.
// Close all listeners.
func P2pCloseAll(v bool) P2pCloseOption {
	return func(rb RequestBuilder) { rb.Option("all", v) }
}

// P2pCloseProtocol sets the protocol option.
// Match protocol name.
func P2pCloseProtocol(v string) P2pCloseOption {
	return func(rb RequestBuilder) { rb.Option("protocol", v) }
}

// P2pCloseListenAddress sets the listen-address option.
// Match listen address.
func P2pCloseListenAddress(v string) P2pCloseOption {
	return func(rb RequestBuilder) { rb.Option("listen-address", v) }
}

// P2pCloseTargetAddress sets the target-address option.
// Match target address.
func P2pCloseTargetAddress(v string) P2pCloseOption {
	return func(rb RequestBuilder) { rb.Option("target-address", v) }
}

// Experimental: P2pClose is not yet stable.
// P2pClose stop listening for new connections to forward..
func (a *HttpApi) P2pClose(ctx context.Context, opts ...P2pCloseOption) (*Response, error) {
	req := a.Request("p2p/close")
	for _, o := range opts {
		o(req)
	}
	resp, err := req.Send(ctx)
	if err != nil {
		return nil, err
	}
	if resp.Error != nil {
		resp.Close()
		return nil, resp.Error
	}
	return resp, nil
}

// P2pForwardOption configures the p2p/forward command.
type P2pForwardOption func(RequestBuilder)

// P2pForwardAllowCustomProtocol sets the allow-custom-protocol option.
// Don't require /x/ prefix.
func P2pForwardAllowCustomProtocol(v bool) P2pForwardOption {
	return func(rb RequestBuilder) { rb.Option("allow-custom-protocol", v) }
}

// P2pForwardForeground sets the foreground option.
// Run in foreground; forwarder is removed when command exits.
func P2pForwardForeground(v bool) P2pForwardOption {
	return func(rb RequestBuilder) { rb.Option("foreground", v) }
}

// Experimental: P2pForward is not yet stable.
// P2pForward forward connections to libp2p service..
func (a *HttpApi) P2pForward(ctx context.Context, protocol string, listen_address string, target_address string, opts ...P2pForwardOption) (*P2pForwardResponse, error) {
	req := a.Request("p2p/forward", protocol, listen_address, target_address)
	for _, o := range opts {
		o(req)
	}
	var resp P2pForwardResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// P2pListenOption configures the p2p/listen command.
type P2pListenOption func(RequestBuilder)

// P2pListenAllowCustomProtocol sets the allow-custom-protocol option.
// Don't require /x/ prefix.
func P2pListenAllowCustomProtocol(v bool) P2pListenOption {
	return func(rb RequestBuilder) { rb.Option("allow-custom-protocol", v) }
}

// P2pListenReportPeerId sets the report-peer-id option.
// Send remote base58 peerid to target when a new connection is established.
func P2pListenReportPeerId(v bool) P2pListenOption {
	return func(rb RequestBuilder) { rb.Option("report-peer-id", v) }
}

// P2pListenForeground sets the foreground option.
// Run in foreground; listener is removed when command exits.
func P2pListenForeground(v bool) P2pListenOption {
	return func(rb RequestBuilder) { rb.Option("foreground", v) }
}

// Experimental: P2pListen is not yet stable.
// P2pListen create libp2p service..
func (a *HttpApi) P2pListen(ctx context.Context, protocol string, target_address string, opts ...P2pListenOption) (*P2pListenResponse, error) {
	req := a.Request("p2p/listen", protocol, target_address)
	for _, o := range opts {
		o(req)
	}
	var resp P2pListenResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// P2pLsOption configures the p2p/ls command.
type P2pLsOption func(RequestBuilder)

// P2pLsHeaders sets the headers option.
// Print table headers (Protocol, Listen, Target).
func P2pLsHeaders(v bool) P2pLsOption {
	return func(rb RequestBuilder) { rb.Option("headers", v) }
}

// Experimental: P2pLs is not yet stable.
// P2pLs list active p2p listeners..
func (a *HttpApi) P2pLs(ctx context.Context, opts ...P2pLsOption) (*P2pLsResponse, error) {
	req := a.Request("p2p/ls")
	for _, o := range opts {
		o(req)
	}
	var resp P2pLsResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// P2pStreamCloseOption configures the p2p/stream/close command.
type P2pStreamCloseOption func(RequestBuilder)

// P2pStreamCloseAll sets the all option.
// Close all streams.
func P2pStreamCloseAll(v bool) P2pStreamCloseOption {
	return func(rb RequestBuilder) { rb.Option("all", v) }
}

// Experimental: P2pStreamClose is not yet stable.
// P2pStreamClose close active p2p stream..
func (a *HttpApi) P2pStreamClose(ctx context.Context, id string, opts ...P2pStreamCloseOption) (*Response, error) {
	req := a.Request("p2p/stream/close", id)
	for _, o := range opts {
		o(req)
	}
	resp, err := req.Send(ctx)
	if err != nil {
		return nil, err
	}
	if resp.Error != nil {
		resp.Close()
		return nil, resp.Error
	}
	return resp, nil
}

// P2pStreamLsOption configures the p2p/stream/ls command.
type P2pStreamLsOption func(RequestBuilder)

// P2pStreamLsHeaders sets the headers option.
// Print table headers (ID, Protocol, Local, Remote).
func P2pStreamLsHeaders(v bool) P2pStreamLsOption {
	return func(rb RequestBuilder) { rb.Option("headers", v) }
}

// Experimental: P2pStreamLs is not yet stable.
// P2pStreamLs list active p2p streams..
func (a *HttpApi) P2pStreamLs(ctx context.Context, opts ...P2pStreamLsOption) (*P2pStreamLsResponse, error) {
	req := a.Request("p2p/stream/ls")
	for _, o := range opts {
		o(req)
	}
	var resp P2pStreamLsResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
