// Code generated by tools/gen-rpc-client; DO NOT EDIT.

package rpc

import (
	"context"
)

type FilestoreDupsResponse struct {
	Ref string `json:"Ref,omitempty"`
	Err string `json:"Err,omitempty"`
}

type FilestoreLsResponse struct {
	Status   int32  `json:"Status,omitempty"`
	ErrorMsg string `json:"ErrorMsg,omitempty"`
	Key      string `json:"Key,omitempty"`
	FilePath string `json:"FilePath,omitempty"`
	Offset   uint64 `json:"Offset,omitempty"`
	Size     uint64 `json:"Size,omitempty"`
}

type FilestoreVerifyResponse struct {
	Status   int32  `json:"Status,omitempty"`
	ErrorMsg string `json:"ErrorMsg,omitempty"`
	Key      string `json:"Key,omitempty"`
	FilePath string `json:"FilePath,omitempty"`
	Offset   uint64 `json:"Offset,omitempty"`
	Size     uint64 `json:"Size,omitempty"`
}

// FilestoreDups list blocks that are both in the filestore and standard block storage..
func (a *HttpApi) FilestoreDups(ctx context.Context) (*FilestoreDupsResponse, error) {
	req := a.Request("filestore/dups")
	var resp FilestoreDupsResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// FilestoreLsOption configures the filestore/ls command.
type FilestoreLsOption func(RequestBuilder)

// FilestoreLsFileOrder sets the file-order option.
// sort the results based on the path of the backing file.
func FilestoreLsFileOrder(v bool) FilestoreLsOption {
	return func(rb RequestBuilder) { rb.Option("file-order", v) }
}

// FilestoreLs list objects in filestore..
func (a *HttpApi) FilestoreLs(ctx context.Context, obj []string, opts ...FilestoreLsOption) (*FilestoreLsResponse, error) {
	req := a.Request("filestore/ls").Arguments(obj...)
	for _, o := range opts {
		o(req)
	}
	var resp FilestoreLsResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// FilestoreVerifyOption configures the filestore/verify command.
type FilestoreVerifyOption func(RequestBuilder)

// FilestoreVerifyFileOrder sets the file-order option.
// verify the objects based on the order of the backing file.
func FilestoreVerifyFileOrder(v bool) FilestoreVerifyOption {
	return func(rb RequestBuilder) { rb.Option("file-order", v) }
}

// FilestoreVerifyRemoveBadBlocks sets the remove-bad-blocks option.
// remove bad blocks. WARNING: This may remove pinned data. You should run 'ipfs pin verify' after running this command and correct any issues.
func FilestoreVerifyRemoveBadBlocks(v bool) FilestoreVerifyOption {
	return func(rb RequestBuilder) { rb.Option("remove-bad-blocks", v) }
}

// FilestoreVerify verify objects in filestore..
func (a *HttpApi) FilestoreVerify(ctx context.Context, obj []string, opts ...FilestoreVerifyOption) (*FilestoreVerifyResponse, error) {
	req := a.Request("filestore/verify").Arguments(obj...)
	for _, o := range opts {
		o(req)
	}
	var resp FilestoreVerifyResponse
	if err := req.Exec(ctx, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
