// Code generated by tools/gen-rpc-client; DO NOT EDIT.

package rpc

import (
	"context"
	"encoding/json"
	"iter"
)

type LsResponse struct {
	Objects []LsResponseObjects `json:"Objects,omitempty"`
}

type LsResponseObjects struct {
	Hash  string                   `json:"Hash,omitempty"`
	Links []LsResponseObjectsLinks `json:"Links,omitempty"`
}

type LsResponseObjectsLinks struct {
	Name    string `json:"Name,omitempty"`
	Hash    string `json:"Hash,omitempty"`
	Size    uint64 `json:"Size,omitempty"`
	Type    int32  `json:"Type,omitempty"`
	Target  string `json:"Target,omitempty"`
	Mode    uint32 `json:"Mode,omitempty"`
	ModTime string `json:"ModTime,omitempty"`
}

// LsOption configures the ls command.
type LsOption func(RequestBuilder)

// LsHeaders sets the headers option.
// Print table headers (Hash, Size, Name).
func LsHeaders(v bool) LsOption {
	return func(rb RequestBuilder) { rb.Option("headers", v) }
}

// LsResolveType sets the resolve-type option.
// Resolve linked objects to find out their types. Default: true.
func LsResolveType(v bool) LsOption {
	return func(rb RequestBuilder) { rb.Option("resolve-type", v) }
}

// LsSize sets the size option.
// Resolve linked objects to find out their file size. Default: true.
func LsSize(v bool) LsOption {
	return func(rb RequestBuilder) { rb.Option("size", v) }
}

// LsStream sets the stream option.
// Enable experimental streaming of directory entries as they are traversed.
func LsStream(v bool) LsOption {
	return func(rb RequestBuilder) { rb.Option("stream", v) }
}

// LsLong sets the long option.
// Use a long listing format, showing file mode and modification time.
func LsLong(v bool) LsOption {
	return func(rb RequestBuilder) { rb.Option("long", v) }
}

// Ls list directory contents for Unix filesystem objects..
func (a *HttpApi) Ls(ctx context.Context, ipfs_path []string, opts ...LsOption) iter.Seq2[LsResponse, error] {
	return func(yield func(LsResponse, error) bool) {
		req := a.Request("ls").Arguments(ipfs_path...)
		for _, o := range opts {
			o(req)
		}
		resp, err := req.Send(ctx)
		if err != nil {
			yield(LsResponse{}, err)
			return
		}
		defer resp.Close()
		if resp.Error != nil {
			yield(LsResponse{}, resp.Error)
			return
		}
		dec := json.NewDecoder(resp.Output)
		for dec.More() {
			var item LsResponse
			if err := dec.Decode(&item); err != nil {
				yield(LsResponse{}, err)
				return
			}
			if !yield(item, nil) {
				return
			}
		}
	}
}
