blank_issues_enabled: false
contact_links:
 - name: Getting Help on IPFS
   url: https://ipfs.io/help
   about: All information about how and where to get help on IPFS.
 - name: Go-ipfs configuration reference
   url: https://github.com/ipfs/go-ipfs/blob/master/docs/config.md
   about: Documentation on the different configuration settings
 - name: Go-ipfs experimental features docs
   url: https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md
   about: Documentation on Private Networks, Filestore and other experimental features.
 - name: HTTP API Reference
   url: https://docs-beta.ipfs.io/reference/http/api/#api-v0-add
   about: Documentation of all go-ipfs HTTP API endpoints.
 - name: IPFS Official Forum
   url: https://discuss.ipfs.io
   about: Please post general questions, support requests, and discussions here.
