// Code generated by protoc-gen-gogo.
// source: semver.proto
// DO NOT EDIT!

/*
Package handshake is a generated protocol buffer package.

It is generated from these files:
	semver.proto

It has these top-level messages:
	SemVer
*/
package handshake

import proto "code.google.com/p/gogoprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type SemVer struct {
	Major            *int64 `protobuf:"varint,1,opt,name=major" json:"major,omitempty"`
	Minor            *int64 `protobuf:"varint,2,opt,name=minor" json:"minor,omitempty"`
	Patch            *int64 `protobuf:"varint,3,opt,name=patch" json:"patch,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SemVer) Reset()         { *m = SemVer{} }
func (m *SemVer) String() string { return proto.CompactTextString(m) }
func (*SemVer) ProtoMessage()    {}

func (m *SemVer) GetMajor() int64 {
	if m != nil && m.Major != nil {
		return *m.Major
	}
	return 0
}

func (m *SemVer) GetMinor() int64 {
	if m != nil && m.Minor != nil {
		return *m.Minor
	}
	return 0
}

func (m *SemVer) GetPatch() int64 {
	if m != nil && m.Patch != nil {
		return *m.Patch
	}
	return 0
}

func init() {
}
