package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	corecmds "github.com/ipfs/kubo/core/commands"
)

func TestPathToGoName(t *testing.T) {
	tests := []struct {
		path string
		want string
	}{
		{"pin/add", "PinAdd"},
		{"pin/remote/add", "PinRemoteAdd"},
		{"version", "Version"},
		{"swarm/peers", "SwarmPeers"},
		{"stats/bw", "StatsBw"},
		{"dag/import", "DagImport"},
	}
	for _, tt := range tests {
		got := pathToGoName(tt.path)
		if got != tt.want {
			t.Errorf("pathToGoName(%q) = %q, want %q", tt.path, got, tt.want)
		}
	}
}

func TestToPascalCase(t *testing.T) {
	tests := []struct {
		input string
		want  string
	}{
		{"find-provs", "FindProvs"},
		{"bw", "Bw"},
		{"add", "Add"},
		{"cid-base", "CidBase"},
		{"repo-dir", "RepoDir"},
		{"resolve-type", "ResolveType"},
		{"num_providers", "NumProviders"},
	}
	for _, tt := range tests {
		got := toPascalCase(tt.input)
		if got != tt.want {
			t.Errorf("toPascalCase(%q) = %q, want %q", tt.input, got, tt.want)
		}
	}
}

func TestGroupName(t *testing.T) {
	tests := []struct {
		path string
		want string
	}{
		{"pin/add", "pin"},
		{"version", "version"},
		{"pin/remote/add", "pin"},
		{"dag/stat", "dag"},
	}
	for _, tt := range tests {
		got := groupName(tt.path)
		if got != tt.want {
			t.Errorf("groupName(%q) = %q, want %q", tt.path, got, tt.want)
		}
	}
}

func TestSanitizeArgName(t *testing.T) {
	tests := []struct {
		input string
		want  string
	}{
		{"ipfs-path", "ipfs_path"},
		{"object data", "object_data"},
		{"type", "typeArg"},
		{"key.name", "key_name"},
		{"normal", "normal"},
	}
	for _, tt := range tests {
		got := sanitizeArgName(tt.input)
		if got != tt.want {
			t.Errorf("sanitizeArgName(%q) = %q, want %q", tt.input, got, tt.want)
		}
	}
}

func TestSanitizeDescription(t *testing.T) {
	got := sanitizeDescription("line one\nline two\nline three")
	want := "line one line two line three"
	if got != want {
		t.Errorf("sanitizeDescription = %q, want %q", got, want)
	}
}

func TestWalkCommandTree(t *testing.T) {
	commands := walkCommandTree(corecmds.Root, "")

	if len(commands) == 0 {
		t.Fatal("walkCommandTree returned no commands")
	}

	// check some commands that must be present
	found := make(map[string]bool)
	for _, cmd := range commands {
		found[cmd.Path] = true
	}

	mustExist := []string{
		"pin/add", "pin/ls", "pin/rm",
		"block/get", "block/put", "block/stat",
		"version", "id", "cat",
		"swarm/peers", "swarm/connect",
	}
	for _, path := range mustExist {
		if !found[path] {
			t.Errorf("expected command %q not found in walk results", path)
		}
	}

	// verify no removed commands leak through
	for _, cmd := range commands {
		if cmd.GoName == "" {
			t.Errorf("command %q has empty GoName", cmd.Path)
		}
		if cmd.GroupName == "" {
			t.Errorf("command %q has empty GroupName", cmd.Path)
		}
	}
}

func TestWalkExcludesGlobalOptions(t *testing.T) {
	commands := walkCommandTree(corecmds.Root, "")

	for _, cmd := range commands {
		for _, opt := range cmd.Options {
			if isGlobalOption(opt.Name) {
				t.Errorf("command %q includes global option %q", cmd.Path, opt.Name)
			}
		}
	}
}

func TestReflectResponseType(t *testing.T) {
	type Simple struct {
		Name string `json:"Name,omitempty"`
		Size int    `json:"Size,omitempty"`
	}

	types := reflectResponseType("Test", reflect.TypeOf(Simple{}))
	if len(types) == 0 {
		t.Fatal("reflectResponseType returned no types")
	}
	if types[0].Name != "TestResponse" {
		t.Errorf("type name = %q, want %q", types[0].Name, "TestResponse")
	}
	if len(types[0].Fields) != 2 {
		t.Errorf("field count = %d, want 2", len(types[0].Fields))
	}

	fieldNames := make(map[string]bool)
	for _, f := range types[0].Fields {
		fieldNames[f.Name] = true
	}
	if !fieldNames["Name"] || !fieldNames["Size"] {
		t.Errorf("expected fields Name and Size, got %v", fieldNames)
	}
}

func TestReflectResponseTypeNil(t *testing.T) {
	types := reflectResponseType("Test", nil)
	if types != nil {
		t.Errorf("expected nil for nil input, got %v", types)
	}
}

func TestGenerateFiles(t *testing.T) {
	commands := walkCommandTree(corecmds.Root, "")
	files, err := generateFiles(commands)
	if err != nil {
		t.Fatalf("generateFiles failed: %v", err)
	}

	if len(files) == 0 {
		t.Fatal("generateFiles produced no files")
	}

	// every file should have the generated header
	for name, content := range files {
		if !strings.HasPrefix(name, "gen_") {
			t.Errorf("file %q does not start with gen_", name)
		}
		if !strings.HasSuffix(name, ".go") {
			t.Errorf("file %q does not end with .go", name)
		}
		if !strings.Contains(string(content), "Code generated by tools/gen-rpc-client; DO NOT EDIT.") {
			t.Errorf("file %q missing generation header", name)
		}
		if !strings.Contains(string(content), "package rpc") {
			t.Errorf("file %q missing package declaration", name)
		}
	}

	// verify well-known files exist
	for _, name := range []string{"gen_pin.go", "gen_block.go", "gen_version.go", "gen_swarm.go"} {
		if _, ok := files[name]; !ok {
			t.Errorf("expected file %q not generated", name)
		}
	}
}

func TestGenerateAndCompile(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping compilation test in short mode")
	}

	commands := walkCommandTree(corecmds.Root, "")
	files, err := generateFiles(commands)
	if err != nil {
		t.Fatalf("generateFiles failed: %v", err)
	}

	// write generated files to client/rpc in a temp copy, then compile
	tmpDir := t.TempDir()

	// copy existing non-generated client/rpc files
	repoRoot := findRepoRoot(t)
	rpcDir := filepath.Join(repoRoot, "client", "rpc")
	entries, err := os.ReadDir(rpcDir)
	if err != nil {
		t.Fatalf("reading %s: %v", rpcDir, err)
	}

	outDir := filepath.Join(tmpDir, "client", "rpc")
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		t.Fatal(err)
	}

	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		// skip existing gen_ files and test files
		if strings.HasPrefix(e.Name(), "gen_") || strings.HasSuffix(e.Name(), "_test.go") {
			continue
		}
		data, err := os.ReadFile(filepath.Join(rpcDir, e.Name()))
		if err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(outDir, e.Name()), data, 0o644); err != nil {
			t.Fatal(err)
		}
	}

	// copy auth subpackage
	authSrc := filepath.Join(rpcDir, "auth")
	if _, err := os.Stat(authSrc); err == nil {
		authDst := filepath.Join(outDir, "auth")
		if err := os.MkdirAll(authDst, 0o755); err != nil {
			t.Fatal(err)
		}
		authEntries, err := os.ReadDir(authSrc)
		if err != nil {
			t.Fatal(err)
		}
		for _, e := range authEntries {
			if e.IsDir() || strings.HasSuffix(e.Name(), "_test.go") {
				continue
			}
			data, err := os.ReadFile(filepath.Join(authSrc, e.Name()))
			if err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(filepath.Join(authDst, e.Name()), data, 0o644); err != nil {
				t.Fatal(err)
			}
		}
	}

	// write generated files
	for name, content := range files {
		if err := os.WriteFile(filepath.Join(outDir, name), content, 0o644); err != nil {
			t.Fatal(err)
		}
	}

	// try to compile the package using "go build" pointing at the real module
	cmd := exec.Command("go", "build", "./client/rpc/...")
	cmd.Dir = repoRoot
	cmd.Env = append(os.Environ(), "GOFLAGS=-mod=mod")
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("go build failed: %v\n%s", err, out)
	}
}

func findRepoRoot(t *testing.T) string {
	t.Helper()
	dir, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatal("could not find repo root (no go.mod)")
		}
		dir = parent
	}
}
