package main

import "text/template"

// allFuncMap contains all template functions. Functions that depend on
// generate.go are registered as stubs here and replaced at execution time.
// This is needed because template.Must runs at init() before other funcs
// are available.
var allFuncMap = template.FuncMap{
	"responseTypeName":     func(CommandInfo) string { return "" },
	"optionTypes":          func(CommandInfo) string { return "" },
	"methodFunc":           func(CommandInfo) string { return "" },
	"argParams":            func(CommandInfo) string { return "" },
	"argValues":            func(CommandInfo) string { return "" },
	"returnType":           func(CommandInfo) string { return "" },
	"streamReturnType":     func(CommandInfo) string { return "" },
	"streamItemType":       func(CommandInfo) string { return "" },
	"streamZero":           func(CommandInfo) string { return "" },
	"hasStructResponse":    func(CommandInfo) bool { return false },
	"hasSliceResponse":     func(CommandInfo) bool { return false },
	"fileBodySetup":        func(CommandInfo) string { return "" },
	"toLower":              func(string) string { return "" },
	"sanitizeDescription":  func(string) string { return "" },
	"hasPrimitiveResponse": func(CommandInfo) bool { return false },
}

// fileTemplateStr is the main template for one gen_*.go file.
const fileTemplateStr = `// Code generated by tools/gen-rpc-client; DO NOT EDIT.

package rpc

import (
	"context"
{{- if .NeedsIO}}
	"io"
{{- end}}
{{- if .NeedsJSON}}
	"encoding/json"
{{- end}}
{{- if .NeedsIter}}
	"iter"
{{- end}}
)

{{range .Types}}
{{- if .Fields}}
type {{.Name}} struct {
{{- range .Fields}}
	{{.Name}} {{.Type}} ` + "`" + `json:"{{.JSONTag}}"` + "`" + `
{{- end}}
}
{{end}}
{{end}}

{{- range .Commands}}
{{optionTypes .}}
{{methodFunc .}}
{{end}}
`

// optionTypesTemplateStr generates the option type and option funcs for a command.
const optionTypesTemplateStr = `
{{- if .Options}}
// {{.GoName}}Option configures the {{.Path}} command.
type {{.GoName}}Option func(RequestBuilder)
{{range .Options}}
// {{$.GoName}}{{.GoName}} sets the {{.Name}} option.
{{- if .Description}}
// {{sanitizeDescription .Description}}
{{- end}}
func {{$.GoName}}{{.GoName}}(v {{.Type}}) {{$.GoName}}Option {
	return func(rb RequestBuilder) { rb.Option("{{.Name}}", v) }
}
{{end}}
{{- end}}
`

// singleMethodTemplateStr generates a method for a single-response command.
const singleMethodTemplateStr = `
{{- if eq .Status 2}}
// Deprecated: {{.GoName}} may be removed in a future release.
{{- end}}
{{- if eq .Status 1}}
// Experimental: {{.GoName}} is not yet stable.
{{- end}}
{{- if .Tagline}}
// {{.GoName}} {{toLower .Tagline}}.
{{- end}}
func (a *HttpApi) {{.GoName}}(ctx context.Context{{argParams .}}{{if .Options}}, opts ...{{.GoName}}Option{{end}}) ({{returnType .}}) {
	req := a.Request("{{.Path}}"{{argValues .}})
{{- if .HasFileArg}}
	{{fileBodySetup .}}
{{- end}}
{{- if .Options}}
	for _, o := range opts { o(req) }
{{- end}}
{{- if hasStructResponse .}}
	var resp {{responseTypeName .}}
	if err := req.Exec(ctx, &resp); err != nil { return nil, err }
	return &resp, nil
{{- else if hasSliceResponse .}}
	var resp {{responseTypeName .}}
	if err := req.Exec(ctx, &resp); err != nil { return nil, err }
	return resp, nil
{{- else}}
	return req.Exec(ctx, nil)
{{- end}}
}
`

// streamMethodTemplateStr generates a method for a streaming command.
const streamMethodTemplateStr = `
{{- if eq .Status 2}}
// Deprecated: {{.GoName}} may be removed in a future release.
{{- end}}
{{- if eq .Status 1}}
// Experimental: {{.GoName}} is not yet stable.
{{- end}}
{{- if .Tagline}}
// {{.GoName}} {{toLower .Tagline}}.
{{- end}}
func (a *HttpApi) {{.GoName}}(ctx context.Context{{argParams .}}{{if .Options}}, opts ...{{.GoName}}Option{{end}}) {{streamReturnType .}} {
	return func(yield func({{streamItemType .}}, error) bool) {
		req := a.Request("{{.Path}}"{{argValues .}})
{{- if .HasFileArg}}
		{{fileBodySetup .}}
{{- end}}
{{- if .Options}}
		for _, o := range opts { o(req) }
{{- end}}
		resp, err := req.Send(ctx)
		if err != nil { yield({{streamZero .}}, err); return }
		defer resp.Close()
		if resp.Error != nil { yield({{streamZero .}}, resp.Error); return }
		dec := json.NewDecoder(resp.Output)
		for dec.More() {
			var item {{streamItemType .}}
			if err := dec.Decode(&item); err != nil { yield({{streamZero .}}, err); return }
			if !yield(item, nil) { return }
		}
	}
}
`

// binaryMethodTemplateStr generates a method for a binary-output command.
const binaryMethodTemplateStr = `
{{- if eq .Status 2}}
// Deprecated: {{.GoName}} may be removed in a future release.
{{- end}}
{{- if eq .Status 1}}
// Experimental: {{.GoName}} is not yet stable.
{{- end}}
{{- if .Tagline}}
// {{.GoName}} {{toLower .Tagline}}.
{{- end}}
func (a *HttpApi) {{.GoName}}(ctx context.Context{{argParams .}}{{if .Options}}, opts ...{{.GoName}}Option{{end}}) (*Response, error) {
	req := a.Request("{{.Path}}"{{argValues .}})
{{- if .HasFileArg}}
	{{fileBodySetup .}}
{{- end}}
{{- if .Options}}
	for _, o := range opts { o(req) }
{{- end}}
	resp, err := req.Send(ctx)
	if err != nil { return nil, err }
	if resp.Error != nil { resp.Close(); return nil, resp.Error }
	return resp, nil
}
`

// voidMethodTemplateStr generates a method for a command with no response body.
const voidMethodTemplateStr = `
{{- if eq .Status 2}}
// Deprecated: {{.GoName}} may be removed in a future release.
{{- end}}
{{- if eq .Status 1}}
// Experimental: {{.GoName}} is not yet stable.
{{- end}}
{{- if .Tagline}}
// {{.GoName}} {{toLower .Tagline}}.
{{- end}}
func (a *HttpApi) {{.GoName}}(ctx context.Context{{argParams .}}{{if .Options}}, opts ...{{.GoName}}Option{{end}}) error {
	req := a.Request("{{.Path}}"{{argValues .}})
{{- if .HasFileArg}}
	{{fileBodySetup .}}
{{- end}}
{{- if .Options}}
	for _, o := range opts { o(req) }
{{- end}}
	return req.Exec(ctx, nil)
}
`
