name: Close and mark stale issue

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    uses: pl-strflt/.github/.github/workflows/reusable-stale-issue.yml@v0.3
