name: Staticmajor
on: [push,workflow_dispatch,pull_request]
jobs:
  run_staticmajor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
      - name: Staticmajor action
        id: staticmajor
        uses: orijtech/staticmajor-action@main
        with:
            packages: ./...
